// Code generated by ent, DO NOT EDIT.

package l1tokenoutputwithdrawal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldUpdateTime, v))
}

// BitcoinVout applies equality check predicate on the "bitcoin_vout" field. It's identical to BitcoinVoutEQ.
func BitcoinVout(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldBitcoinVout, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLTE(FieldUpdateTime, v))
}

// BitcoinVoutEQ applies the EQ predicate on the "bitcoin_vout" field.
func BitcoinVoutEQ(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldEQ(FieldBitcoinVout, v))
}

// BitcoinVoutNEQ applies the NEQ predicate on the "bitcoin_vout" field.
func BitcoinVoutNEQ(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNEQ(FieldBitcoinVout, v))
}

// BitcoinVoutIn applies the In predicate on the "bitcoin_vout" field.
func BitcoinVoutIn(vs ...uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldIn(FieldBitcoinVout, vs...))
}

// BitcoinVoutNotIn applies the NotIn predicate on the "bitcoin_vout" field.
func BitcoinVoutNotIn(vs ...uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldNotIn(FieldBitcoinVout, vs...))
}

// BitcoinVoutGT applies the GT predicate on the "bitcoin_vout" field.
func BitcoinVoutGT(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGT(FieldBitcoinVout, v))
}

// BitcoinVoutGTE applies the GTE predicate on the "bitcoin_vout" field.
func BitcoinVoutGTE(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldGTE(FieldBitcoinVout, v))
}

// BitcoinVoutLT applies the LT predicate on the "bitcoin_vout" field.
func BitcoinVoutLT(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLT(FieldBitcoinVout, v))
}

// BitcoinVoutLTE applies the LTE predicate on the "bitcoin_vout" field.
func BitcoinVoutLTE(v uint16) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.FieldLTE(FieldBitcoinVout, v))
}

// HasTokenOutput applies the HasEdge predicate on the "token_output" edge.
func HasTokenOutput() predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TokenOutputTable, TokenOutputColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokenOutputWith applies the HasEdge predicate on the "token_output" edge with a given conditions (other predicates).
func HasTokenOutputWith(preds ...predicate.TokenOutput) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(func(s *sql.Selector) {
		step := newTokenOutputStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasL1WithdrawalTransaction applies the HasEdge predicate on the "l1_withdrawal_transaction" edge.
func HasL1WithdrawalTransaction() predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, L1WithdrawalTransactionTable, L1WithdrawalTransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasL1WithdrawalTransactionWith applies the HasEdge predicate on the "l1_withdrawal_transaction" edge with a given conditions (other predicates).
func HasL1WithdrawalTransactionWith(preds ...predicate.L1WithdrawalTransaction) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(func(s *sql.Selector) {
		step := newL1WithdrawalTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJusticeTx applies the HasEdge predicate on the "justice_tx" edge.
func HasJusticeTx() predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, JusticeTxTable, JusticeTxColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJusticeTxWith applies the HasEdge predicate on the "justice_tx" edge with a given conditions (other predicates).
func HasJusticeTxWith(preds ...predicate.L1TokenJusticeTransaction) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(func(s *sql.Selector) {
		step := newJusticeTxStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.L1TokenOutputWithdrawal) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.L1TokenOutputWithdrawal) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.L1TokenOutputWithdrawal) predicate.L1TokenOutputWithdrawal {
	return predicate.L1TokenOutputWithdrawal(sql.NotPredicates(p))
}
