// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/eventmessage"
)

// EventMessage is the model entity for the EventMessage schema.
type EventMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The channel on which the event was emitted.
	Channel string `json:"channel,omitempty"`
	// The JSON payload describing the even that occurred (i.e. the ent that was updated & relevant details).
	Payload      string `json:"payload,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventmessage.FieldChannel, eventmessage.FieldPayload:
			values[i] = new(sql.NullString)
		case eventmessage.FieldCreateTime, eventmessage.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case eventmessage.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventMessage fields.
func (em *EventMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventmessage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				em.ID = *value
			}
		case eventmessage.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				em.CreateTime = value.Time
			}
		case eventmessage.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				em.UpdateTime = value.Time
			}
		case eventmessage.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				em.Channel = value.String
			}
		case eventmessage.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				em.Payload = value.String
			}
		default:
			em.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventMessage.
// This includes values selected through modifiers, order, etc.
func (em *EventMessage) Value(name string) (ent.Value, error) {
	return em.selectValues.Get(name)
}

// Update returns a builder for updating this EventMessage.
// Note that you need to call EventMessage.Unwrap() before calling this method if this EventMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (em *EventMessage) Update() *EventMessageUpdateOne {
	return NewEventMessageClient(em.config).UpdateOne(em)
}

// Unwrap unwraps the EventMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (em *EventMessage) Unwrap() *EventMessage {
	_tx, ok := em.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventMessage is not a transactional entity")
	}
	em.config.driver = _tx.drv
	return em
}

// String implements the fmt.Stringer.
func (em *EventMessage) String() string {
	var builder strings.Builder
	builder.WriteString("EventMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", em.ID))
	builder.WriteString("create_time=")
	builder.WriteString(em.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(em.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(em.Channel)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(em.Payload)
	builder.WriteByte(')')
	return builder.String()
}

// EventMessages is a parsable slice of EventMessage.
type EventMessages []*EventMessage
