// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/idempotencykey"
)

// IdempotencyKeyCreate is the builder for creating a IdempotencyKey entity.
type IdempotencyKeyCreate struct {
	config
	mutation *IdempotencyKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (ikc *IdempotencyKeyCreate) SetCreateTime(t time.Time) *IdempotencyKeyCreate {
	ikc.mutation.SetCreateTime(t)
	return ikc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ikc *IdempotencyKeyCreate) SetNillableCreateTime(t *time.Time) *IdempotencyKeyCreate {
	if t != nil {
		ikc.SetCreateTime(*t)
	}
	return ikc
}

// SetUpdateTime sets the "update_time" field.
func (ikc *IdempotencyKeyCreate) SetUpdateTime(t time.Time) *IdempotencyKeyCreate {
	ikc.mutation.SetUpdateTime(t)
	return ikc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ikc *IdempotencyKeyCreate) SetNillableUpdateTime(t *time.Time) *IdempotencyKeyCreate {
	if t != nil {
		ikc.SetUpdateTime(*t)
	}
	return ikc
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (ikc *IdempotencyKeyCreate) SetIdempotencyKey(s string) *IdempotencyKeyCreate {
	ikc.mutation.SetIdempotencyKey(s)
	return ikc
}

// SetMethodName sets the "method_name" field.
func (ikc *IdempotencyKeyCreate) SetMethodName(s string) *IdempotencyKeyCreate {
	ikc.mutation.SetMethodName(s)
	return ikc
}

// SetResponse sets the "response" field.
func (ikc *IdempotencyKeyCreate) SetResponse(jm json.RawMessage) *IdempotencyKeyCreate {
	ikc.mutation.SetResponse(jm)
	return ikc
}

// SetID sets the "id" field.
func (ikc *IdempotencyKeyCreate) SetID(u uuid.UUID) *IdempotencyKeyCreate {
	ikc.mutation.SetID(u)
	return ikc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ikc *IdempotencyKeyCreate) SetNillableID(u *uuid.UUID) *IdempotencyKeyCreate {
	if u != nil {
		ikc.SetID(*u)
	}
	return ikc
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (ikc *IdempotencyKeyCreate) Mutation() *IdempotencyKeyMutation {
	return ikc.mutation
}

// Save creates the IdempotencyKey in the database.
func (ikc *IdempotencyKeyCreate) Save(ctx context.Context) (*IdempotencyKey, error) {
	ikc.defaults()
	return withHooks(ctx, ikc.sqlSave, ikc.mutation, ikc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ikc *IdempotencyKeyCreate) SaveX(ctx context.Context) *IdempotencyKey {
	v, err := ikc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ikc *IdempotencyKeyCreate) Exec(ctx context.Context) error {
	_, err := ikc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ikc *IdempotencyKeyCreate) ExecX(ctx context.Context) {
	if err := ikc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ikc *IdempotencyKeyCreate) defaults() {
	if _, ok := ikc.mutation.CreateTime(); !ok {
		v := idempotencykey.DefaultCreateTime()
		ikc.mutation.SetCreateTime(v)
	}
	if _, ok := ikc.mutation.UpdateTime(); !ok {
		v := idempotencykey.DefaultUpdateTime()
		ikc.mutation.SetUpdateTime(v)
	}
	if _, ok := ikc.mutation.ID(); !ok {
		v := idempotencykey.DefaultID()
		ikc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ikc *IdempotencyKeyCreate) check() error {
	if _, ok := ikc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "IdempotencyKey.create_time"`)}
	}
	if _, ok := ikc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "IdempotencyKey.update_time"`)}
	}
	if _, ok := ikc.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "IdempotencyKey.idempotency_key"`)}
	}
	if v, ok := ikc.mutation.IdempotencyKey(); ok {
		if err := idempotencykey.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.idempotency_key": %w`, err)}
		}
	}
	if _, ok := ikc.mutation.MethodName(); !ok {
		return &ValidationError{Name: "method_name", err: errors.New(`ent: missing required field "IdempotencyKey.method_name"`)}
	}
	if v, ok := ikc.mutation.MethodName(); ok {
		if err := idempotencykey.MethodNameValidator(v); err != nil {
			return &ValidationError{Name: "method_name", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.method_name": %w`, err)}
		}
	}
	return nil
}

func (ikc *IdempotencyKeyCreate) sqlSave(ctx context.Context) (*IdempotencyKey, error) {
	if err := ikc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ikc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ikc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ikc.mutation.id = &_node.ID
	ikc.mutation.done = true
	return _node, nil
}

func (ikc *IdempotencyKeyCreate) createSpec() (*IdempotencyKey, *sqlgraph.CreateSpec) {
	var (
		_node = &IdempotencyKey{config: ikc.config}
		_spec = sqlgraph.NewCreateSpec(idempotencykey.Table, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = ikc.conflict
	if id, ok := ikc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ikc.mutation.CreateTime(); ok {
		_spec.SetField(idempotencykey.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := ikc.mutation.UpdateTime(); ok {
		_spec.SetField(idempotencykey.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := ikc.mutation.IdempotencyKey(); ok {
		_spec.SetField(idempotencykey.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := ikc.mutation.MethodName(); ok {
		_spec.SetField(idempotencykey.FieldMethodName, field.TypeString, value)
		_node.MethodName = value
	}
	if value, ok := ikc.mutation.Response(); ok {
		_spec.SetField(idempotencykey.FieldResponse, field.TypeJSON, value)
		_node.Response = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IdempotencyKey.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdempotencyKeyUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (ikc *IdempotencyKeyCreate) OnConflict(opts ...sql.ConflictOption) *IdempotencyKeyUpsertOne {
	ikc.conflict = opts
	return &IdempotencyKeyUpsertOne{
		create: ikc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IdempotencyKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ikc *IdempotencyKeyCreate) OnConflictColumns(columns ...string) *IdempotencyKeyUpsertOne {
	ikc.conflict = append(ikc.conflict, sql.ConflictColumns(columns...))
	return &IdempotencyKeyUpsertOne{
		create: ikc,
	}
}

type (
	// IdempotencyKeyUpsertOne is the builder for "upsert"-ing
	//  one IdempotencyKey node.
	IdempotencyKeyUpsertOne struct {
		create *IdempotencyKeyCreate
	}

	// IdempotencyKeyUpsert is the "OnConflict" setter.
	IdempotencyKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *IdempotencyKeyUpsert) SetUpdateTime(v time.Time) *IdempotencyKeyUpsert {
	u.Set(idempotencykey.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IdempotencyKeyUpsert) UpdateUpdateTime() *IdempotencyKeyUpsert {
	u.SetExcluded(idempotencykey.FieldUpdateTime)
	return u
}

// SetResponse sets the "response" field.
func (u *IdempotencyKeyUpsert) SetResponse(v json.RawMessage) *IdempotencyKeyUpsert {
	u.Set(idempotencykey.FieldResponse, v)
	return u
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *IdempotencyKeyUpsert) UpdateResponse() *IdempotencyKeyUpsert {
	u.SetExcluded(idempotencykey.FieldResponse)
	return u
}

// ClearResponse clears the value of the "response" field.
func (u *IdempotencyKeyUpsert) ClearResponse() *IdempotencyKeyUpsert {
	u.SetNull(idempotencykey.FieldResponse)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IdempotencyKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(idempotencykey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdempotencyKeyUpsertOne) UpdateNewValues() *IdempotencyKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(idempotencykey.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(idempotencykey.FieldCreateTime)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(idempotencykey.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.MethodName(); exists {
			s.SetIgnore(idempotencykey.FieldMethodName)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IdempotencyKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IdempotencyKeyUpsertOne) Ignore() *IdempotencyKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdempotencyKeyUpsertOne) DoNothing() *IdempotencyKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdempotencyKeyCreate.OnConflict
// documentation for more info.
func (u *IdempotencyKeyUpsertOne) Update(set func(*IdempotencyKeyUpsert)) *IdempotencyKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdempotencyKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *IdempotencyKeyUpsertOne) SetUpdateTime(v time.Time) *IdempotencyKeyUpsertOne {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IdempotencyKeyUpsertOne) UpdateUpdateTime() *IdempotencyKeyUpsertOne {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetResponse sets the "response" field.
func (u *IdempotencyKeyUpsertOne) SetResponse(v json.RawMessage) *IdempotencyKeyUpsertOne {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *IdempotencyKeyUpsertOne) UpdateResponse() *IdempotencyKeyUpsertOne {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.UpdateResponse()
	})
}

// ClearResponse clears the value of the "response" field.
func (u *IdempotencyKeyUpsertOne) ClearResponse() *IdempotencyKeyUpsertOne {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.ClearResponse()
	})
}

// Exec executes the query.
func (u *IdempotencyKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdempotencyKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdempotencyKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IdempotencyKeyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IdempotencyKeyUpsertOne.ID is not supported by MySQL driver. Use IdempotencyKeyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IdempotencyKeyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IdempotencyKeyCreateBulk is the builder for creating many IdempotencyKey entities in bulk.
type IdempotencyKeyCreateBulk struct {
	config
	err      error
	builders []*IdempotencyKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the IdempotencyKey entities in the database.
func (ikcb *IdempotencyKeyCreateBulk) Save(ctx context.Context) ([]*IdempotencyKey, error) {
	if ikcb.err != nil {
		return nil, ikcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ikcb.builders))
	nodes := make([]*IdempotencyKey, len(ikcb.builders))
	mutators := make([]Mutator, len(ikcb.builders))
	for i := range ikcb.builders {
		func(i int, root context.Context) {
			builder := ikcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdempotencyKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ikcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ikcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ikcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ikcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ikcb *IdempotencyKeyCreateBulk) SaveX(ctx context.Context) []*IdempotencyKey {
	v, err := ikcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ikcb *IdempotencyKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := ikcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ikcb *IdempotencyKeyCreateBulk) ExecX(ctx context.Context) {
	if err := ikcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IdempotencyKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdempotencyKeyUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (ikcb *IdempotencyKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *IdempotencyKeyUpsertBulk {
	ikcb.conflict = opts
	return &IdempotencyKeyUpsertBulk{
		create: ikcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IdempotencyKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ikcb *IdempotencyKeyCreateBulk) OnConflictColumns(columns ...string) *IdempotencyKeyUpsertBulk {
	ikcb.conflict = append(ikcb.conflict, sql.ConflictColumns(columns...))
	return &IdempotencyKeyUpsertBulk{
		create: ikcb,
	}
}

// IdempotencyKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of IdempotencyKey nodes.
type IdempotencyKeyUpsertBulk struct {
	create *IdempotencyKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IdempotencyKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(idempotencykey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdempotencyKeyUpsertBulk) UpdateNewValues() *IdempotencyKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(idempotencykey.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(idempotencykey.FieldCreateTime)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(idempotencykey.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.MethodName(); exists {
				s.SetIgnore(idempotencykey.FieldMethodName)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IdempotencyKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IdempotencyKeyUpsertBulk) Ignore() *IdempotencyKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdempotencyKeyUpsertBulk) DoNothing() *IdempotencyKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdempotencyKeyCreateBulk.OnConflict
// documentation for more info.
func (u *IdempotencyKeyUpsertBulk) Update(set func(*IdempotencyKeyUpsert)) *IdempotencyKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdempotencyKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *IdempotencyKeyUpsertBulk) SetUpdateTime(v time.Time) *IdempotencyKeyUpsertBulk {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IdempotencyKeyUpsertBulk) UpdateUpdateTime() *IdempotencyKeyUpsertBulk {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetResponse sets the "response" field.
func (u *IdempotencyKeyUpsertBulk) SetResponse(v json.RawMessage) *IdempotencyKeyUpsertBulk {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *IdempotencyKeyUpsertBulk) UpdateResponse() *IdempotencyKeyUpsertBulk {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.UpdateResponse()
	})
}

// ClearResponse clears the value of the "response" field.
func (u *IdempotencyKeyUpsertBulk) ClearResponse() *IdempotencyKeyUpsertBulk {
	return u.Update(func(s *IdempotencyKeyUpsert) {
		s.ClearResponse()
	})
}

// Exec executes the query.
func (u *IdempotencyKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IdempotencyKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdempotencyKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdempotencyKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
