// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/idempotencykey"
)

// IdempotencyKey is the model entity for the IdempotencyKey schema.
type IdempotencyKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Client-provided idempotency key for deduplication. Multiple requests with the same key return the same response.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// Method name used for the API call.
	MethodName string `json:"method_name,omitempty"`
	// JSON-Marshalled proto response to return for subsequent requests with the same idempotency key. A NULL value indicates we're not done processing the request.
	Response     json.RawMessage `json:"response,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdempotencyKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case idempotencykey.FieldResponse:
			values[i] = new([]byte)
		case idempotencykey.FieldIdempotencyKey, idempotencykey.FieldMethodName:
			values[i] = new(sql.NullString)
		case idempotencykey.FieldCreateTime, idempotencykey.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case idempotencykey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdempotencyKey fields.
func (ik *IdempotencyKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case idempotencykey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ik.ID = *value
			}
		case idempotencykey.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ik.CreateTime = value.Time
			}
		case idempotencykey.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ik.UpdateTime = value.Time
			}
		case idempotencykey.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				ik.IdempotencyKey = value.String
			}
		case idempotencykey.FieldMethodName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method_name", values[i])
			} else if value.Valid {
				ik.MethodName = value.String
			}
		case idempotencykey.FieldResponse:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ik.Response); err != nil {
					return fmt.Errorf("unmarshal field response: %w", err)
				}
			}
		default:
			ik.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdempotencyKey.
// This includes values selected through modifiers, order, etc.
func (ik *IdempotencyKey) Value(name string) (ent.Value, error) {
	return ik.selectValues.Get(name)
}

// Update returns a builder for updating this IdempotencyKey.
// Note that you need to call IdempotencyKey.Unwrap() before calling this method if this IdempotencyKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (ik *IdempotencyKey) Update() *IdempotencyKeyUpdateOne {
	return NewIdempotencyKeyClient(ik.config).UpdateOne(ik)
}

// Unwrap unwraps the IdempotencyKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ik *IdempotencyKey) Unwrap() *IdempotencyKey {
	_tx, ok := ik.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdempotencyKey is not a transactional entity")
	}
	ik.config.driver = _tx.drv
	return ik
}

// String implements the fmt.Stringer.
func (ik *IdempotencyKey) String() string {
	var builder strings.Builder
	builder.WriteString("IdempotencyKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ik.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ik.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ik.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(ik.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("method_name=")
	builder.WriteString(ik.MethodName)
	builder.WriteString(", ")
	builder.WriteString("response=")
	builder.WriteString(fmt.Sprintf("%v", ik.Response))
	builder.WriteByte(')')
	return builder.String()
}

// IdempotencyKeys is a parsable slice of IdempotencyKey.
type IdempotencyKeys []*IdempotencyKey
