// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/idempotencykey"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// IdempotencyKeyDelete is the builder for deleting a IdempotencyKey entity.
type IdempotencyKeyDelete struct {
	config
	hooks    []Hook
	mutation *IdempotencyKeyMutation
}

// Where appends a list predicates to the IdempotencyKeyDelete builder.
func (ikd *IdempotencyKeyDelete) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyDelete {
	ikd.mutation.Where(ps...)
	return ikd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ikd *IdempotencyKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ikd.sqlExec, ikd.mutation, ikd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ikd *IdempotencyKeyDelete) ExecX(ctx context.Context) int {
	n, err := ikd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ikd *IdempotencyKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(idempotencykey.Table, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	if ps := ikd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ikd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ikd.mutation.done = true
	return affected, err
}

// IdempotencyKeyDeleteOne is the builder for deleting a single IdempotencyKey entity.
type IdempotencyKeyDeleteOne struct {
	ikd *IdempotencyKeyDelete
}

// Where appends a list predicates to the IdempotencyKeyDelete builder.
func (ikdo *IdempotencyKeyDeleteOne) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyDeleteOne {
	ikdo.ikd.mutation.Where(ps...)
	return ikdo
}

// Exec executes the deletion query.
func (ikdo *IdempotencyKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := ikdo.ikd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{idempotencykey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ikdo *IdempotencyKeyDeleteOne) ExecX(ctx context.Context) {
	if err := ikdo.Exec(ctx); err != nil {
		panic(err)
	}
}
