// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/idempotencykey"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// IdempotencyKeyQuery is the builder for querying IdempotencyKey entities.
type IdempotencyKeyQuery struct {
	config
	ctx        *QueryContext
	order      []idempotencykey.OrderOption
	inters     []Interceptor
	predicates []predicate.IdempotencyKey
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IdempotencyKeyQuery builder.
func (ikq *IdempotencyKeyQuery) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyQuery {
	ikq.predicates = append(ikq.predicates, ps...)
	return ikq
}

// Limit the number of records to be returned by this query.
func (ikq *IdempotencyKeyQuery) Limit(limit int) *IdempotencyKeyQuery {
	ikq.ctx.Limit = &limit
	return ikq
}

// Offset to start from.
func (ikq *IdempotencyKeyQuery) Offset(offset int) *IdempotencyKeyQuery {
	ikq.ctx.Offset = &offset
	return ikq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ikq *IdempotencyKeyQuery) Unique(unique bool) *IdempotencyKeyQuery {
	ikq.ctx.Unique = &unique
	return ikq
}

// Order specifies how the records should be ordered.
func (ikq *IdempotencyKeyQuery) Order(o ...idempotencykey.OrderOption) *IdempotencyKeyQuery {
	ikq.order = append(ikq.order, o...)
	return ikq
}

// First returns the first IdempotencyKey entity from the query.
// Returns a *NotFoundError when no IdempotencyKey was found.
func (ikq *IdempotencyKeyQuery) First(ctx context.Context) (*IdempotencyKey, error) {
	nodes, err := ikq.Limit(1).All(setContextOp(ctx, ikq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{idempotencykey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) FirstX(ctx context.Context) *IdempotencyKey {
	node, err := ikq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IdempotencyKey ID from the query.
// Returns a *NotFoundError when no IdempotencyKey ID was found.
func (ikq *IdempotencyKeyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ikq.Limit(1).IDs(setContextOp(ctx, ikq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{idempotencykey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ikq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IdempotencyKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IdempotencyKey entity is found.
// Returns a *NotFoundError when no IdempotencyKey entities are found.
func (ikq *IdempotencyKeyQuery) Only(ctx context.Context) (*IdempotencyKey, error) {
	nodes, err := ikq.Limit(2).All(setContextOp(ctx, ikq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{idempotencykey.Label}
	default:
		return nil, &NotSingularError{idempotencykey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) OnlyX(ctx context.Context) *IdempotencyKey {
	node, err := ikq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IdempotencyKey ID in the query.
// Returns a *NotSingularError when more than one IdempotencyKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (ikq *IdempotencyKeyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ikq.Limit(2).IDs(setContextOp(ctx, ikq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{idempotencykey.Label}
	default:
		err = &NotSingularError{idempotencykey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ikq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IdempotencyKeys.
func (ikq *IdempotencyKeyQuery) All(ctx context.Context) ([]*IdempotencyKey, error) {
	ctx = setContextOp(ctx, ikq.ctx, ent.OpQueryAll)
	if err := ikq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IdempotencyKey, *IdempotencyKeyQuery]()
	return withInterceptors[[]*IdempotencyKey](ctx, ikq, qr, ikq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) AllX(ctx context.Context) []*IdempotencyKey {
	nodes, err := ikq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IdempotencyKey IDs.
func (ikq *IdempotencyKeyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ikq.ctx.Unique == nil && ikq.path != nil {
		ikq.Unique(true)
	}
	ctx = setContextOp(ctx, ikq.ctx, ent.OpQueryIDs)
	if err = ikq.Select(idempotencykey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ikq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ikq *IdempotencyKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ikq.ctx, ent.OpQueryCount)
	if err := ikq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ikq, querierCount[*IdempotencyKeyQuery](), ikq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) CountX(ctx context.Context) int {
	count, err := ikq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ikq *IdempotencyKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ikq.ctx, ent.OpQueryExist)
	switch _, err := ikq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ikq *IdempotencyKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := ikq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IdempotencyKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ikq *IdempotencyKeyQuery) Clone() *IdempotencyKeyQuery {
	if ikq == nil {
		return nil
	}
	return &IdempotencyKeyQuery{
		config:     ikq.config,
		ctx:        ikq.ctx.Clone(),
		order:      append([]idempotencykey.OrderOption{}, ikq.order...),
		inters:     append([]Interceptor{}, ikq.inters...),
		predicates: append([]predicate.IdempotencyKey{}, ikq.predicates...),
		// clone intermediate query.
		sql:       ikq.sql.Clone(),
		path:      ikq.path,
		modifiers: append([]func(*sql.Selector){}, ikq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IdempotencyKey.Query().
//		GroupBy(idempotencykey.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ikq *IdempotencyKeyQuery) GroupBy(field string, fields ...string) *IdempotencyKeyGroupBy {
	ikq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IdempotencyKeyGroupBy{build: ikq}
	grbuild.flds = &ikq.ctx.Fields
	grbuild.label = idempotencykey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.IdempotencyKey.Query().
//		Select(idempotencykey.FieldCreateTime).
//		Scan(ctx, &v)
func (ikq *IdempotencyKeyQuery) Select(fields ...string) *IdempotencyKeySelect {
	ikq.ctx.Fields = append(ikq.ctx.Fields, fields...)
	sbuild := &IdempotencyKeySelect{IdempotencyKeyQuery: ikq}
	sbuild.label = idempotencykey.Label
	sbuild.flds, sbuild.scan = &ikq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IdempotencyKeySelect configured with the given aggregations.
func (ikq *IdempotencyKeyQuery) Aggregate(fns ...AggregateFunc) *IdempotencyKeySelect {
	return ikq.Select().Aggregate(fns...)
}

func (ikq *IdempotencyKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ikq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ikq); err != nil {
				return err
			}
		}
	}
	for _, f := range ikq.ctx.Fields {
		if !idempotencykey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ikq.path != nil {
		prev, err := ikq.path(ctx)
		if err != nil {
			return err
		}
		ikq.sql = prev
	}
	return nil
}

func (ikq *IdempotencyKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IdempotencyKey, error) {
	var (
		nodes = []*IdempotencyKey{}
		_spec = ikq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IdempotencyKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IdempotencyKey{config: ikq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ikq.modifiers) > 0 {
		_spec.Modifiers = ikq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ikq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ikq *IdempotencyKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ikq.querySpec()
	if len(ikq.modifiers) > 0 {
		_spec.Modifiers = ikq.modifiers
	}
	_spec.Node.Columns = ikq.ctx.Fields
	if len(ikq.ctx.Fields) > 0 {
		_spec.Unique = ikq.ctx.Unique != nil && *ikq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ikq.driver, _spec)
}

func (ikq *IdempotencyKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	_spec.From = ikq.sql
	if unique := ikq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ikq.path != nil {
		_spec.Unique = true
	}
	if fields := ikq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idempotencykey.FieldID)
		for i := range fields {
			if fields[i] != idempotencykey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ikq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ikq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ikq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ikq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ikq *IdempotencyKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ikq.driver.Dialect())
	t1 := builder.Table(idempotencykey.Table)
	columns := ikq.ctx.Fields
	if len(columns) == 0 {
		columns = idempotencykey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ikq.sql != nil {
		selector = ikq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ikq.ctx.Unique != nil && *ikq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ikq.modifiers {
		m(selector)
	}
	for _, p := range ikq.predicates {
		p(selector)
	}
	for _, p := range ikq.order {
		p(selector)
	}
	if offset := ikq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ikq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ikq *IdempotencyKeyQuery) ForUpdate(opts ...sql.LockOption) *IdempotencyKeyQuery {
	if ikq.driver.Dialect() == dialect.Postgres {
		ikq.Unique(false)
	}
	ikq.modifiers = append(ikq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ikq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ikq *IdempotencyKeyQuery) ForShare(opts ...sql.LockOption) *IdempotencyKeyQuery {
	if ikq.driver.Dialect() == dialect.Postgres {
		ikq.Unique(false)
	}
	ikq.modifiers = append(ikq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ikq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ikq *IdempotencyKeyQuery) Modify(modifiers ...func(s *sql.Selector)) *IdempotencyKeySelect {
	ikq.modifiers = append(ikq.modifiers, modifiers...)
	return ikq.Select()
}

// IdempotencyKeyGroupBy is the group-by builder for IdempotencyKey entities.
type IdempotencyKeyGroupBy struct {
	selector
	build *IdempotencyKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ikgb *IdempotencyKeyGroupBy) Aggregate(fns ...AggregateFunc) *IdempotencyKeyGroupBy {
	ikgb.fns = append(ikgb.fns, fns...)
	return ikgb
}

// Scan applies the selector query and scans the result into the given value.
func (ikgb *IdempotencyKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ikgb.build.ctx, ent.OpQueryGroupBy)
	if err := ikgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IdempotencyKeyQuery, *IdempotencyKeyGroupBy](ctx, ikgb.build, ikgb, ikgb.build.inters, v)
}

func (ikgb *IdempotencyKeyGroupBy) sqlScan(ctx context.Context, root *IdempotencyKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ikgb.fns))
	for _, fn := range ikgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ikgb.flds)+len(ikgb.fns))
		for _, f := range *ikgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ikgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ikgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IdempotencyKeySelect is the builder for selecting fields of IdempotencyKey entities.
type IdempotencyKeySelect struct {
	*IdempotencyKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (iks *IdempotencyKeySelect) Aggregate(fns ...AggregateFunc) *IdempotencyKeySelect {
	iks.fns = append(iks.fns, fns...)
	return iks
}

// Scan applies the selector query and scans the result into the given value.
func (iks *IdempotencyKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iks.ctx, ent.OpQuerySelect)
	if err := iks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IdempotencyKeyQuery, *IdempotencyKeySelect](ctx, iks.IdempotencyKeyQuery, iks, iks.inters, v)
}

func (iks *IdempotencyKeySelect) sqlScan(ctx context.Context, root *IdempotencyKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(iks.fns))
	for _, fn := range iks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*iks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (iks *IdempotencyKeySelect) Modify(modifiers ...func(s *sql.Selector)) *IdempotencyKeySelect {
	iks.modifiers = append(iks.modifiers, modifiers...)
	return iks
}
