// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/idempotencykey"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// IdempotencyKeyUpdate is the builder for updating IdempotencyKey entities.
type IdempotencyKeyUpdate struct {
	config
	hooks     []Hook
	mutation  *IdempotencyKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the IdempotencyKeyUpdate builder.
func (iku *IdempotencyKeyUpdate) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyUpdate {
	iku.mutation.Where(ps...)
	return iku
}

// SetUpdateTime sets the "update_time" field.
func (iku *IdempotencyKeyUpdate) SetUpdateTime(t time.Time) *IdempotencyKeyUpdate {
	iku.mutation.SetUpdateTime(t)
	return iku
}

// SetResponse sets the "response" field.
func (iku *IdempotencyKeyUpdate) SetResponse(jm json.RawMessage) *IdempotencyKeyUpdate {
	iku.mutation.SetResponse(jm)
	return iku
}

// AppendResponse appends jm to the "response" field.
func (iku *IdempotencyKeyUpdate) AppendResponse(jm json.RawMessage) *IdempotencyKeyUpdate {
	iku.mutation.AppendResponse(jm)
	return iku
}

// ClearResponse clears the value of the "response" field.
func (iku *IdempotencyKeyUpdate) ClearResponse() *IdempotencyKeyUpdate {
	iku.mutation.ClearResponse()
	return iku
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (iku *IdempotencyKeyUpdate) Mutation() *IdempotencyKeyMutation {
	return iku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iku *IdempotencyKeyUpdate) Save(ctx context.Context) (int, error) {
	iku.defaults()
	return withHooks(ctx, iku.sqlSave, iku.mutation, iku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iku *IdempotencyKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := iku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iku *IdempotencyKeyUpdate) Exec(ctx context.Context) error {
	_, err := iku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iku *IdempotencyKeyUpdate) ExecX(ctx context.Context) {
	if err := iku.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iku *IdempotencyKeyUpdate) defaults() {
	if _, ok := iku.mutation.UpdateTime(); !ok {
		v := idempotencykey.UpdateDefaultUpdateTime()
		iku.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iku *IdempotencyKeyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IdempotencyKeyUpdate {
	iku.modifiers = append(iku.modifiers, modifiers...)
	return iku
}

func (iku *IdempotencyKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	if ps := iku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iku.mutation.UpdateTime(); ok {
		_spec.SetField(idempotencykey.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := iku.mutation.Response(); ok {
		_spec.SetField(idempotencykey.FieldResponse, field.TypeJSON, value)
	}
	if value, ok := iku.mutation.AppendedResponse(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idempotencykey.FieldResponse, value)
		})
	}
	if iku.mutation.ResponseCleared() {
		_spec.ClearField(idempotencykey.FieldResponse, field.TypeJSON)
	}
	_spec.AddModifiers(iku.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, iku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencykey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iku.mutation.done = true
	return n, nil
}

// IdempotencyKeyUpdateOne is the builder for updating a single IdempotencyKey entity.
type IdempotencyKeyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *IdempotencyKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (ikuo *IdempotencyKeyUpdateOne) SetUpdateTime(t time.Time) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetUpdateTime(t)
	return ikuo
}

// SetResponse sets the "response" field.
func (ikuo *IdempotencyKeyUpdateOne) SetResponse(jm json.RawMessage) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetResponse(jm)
	return ikuo
}

// AppendResponse appends jm to the "response" field.
func (ikuo *IdempotencyKeyUpdateOne) AppendResponse(jm json.RawMessage) *IdempotencyKeyUpdateOne {
	ikuo.mutation.AppendResponse(jm)
	return ikuo
}

// ClearResponse clears the value of the "response" field.
func (ikuo *IdempotencyKeyUpdateOne) ClearResponse() *IdempotencyKeyUpdateOne {
	ikuo.mutation.ClearResponse()
	return ikuo
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (ikuo *IdempotencyKeyUpdateOne) Mutation() *IdempotencyKeyMutation {
	return ikuo.mutation
}

// Where appends a list predicates to the IdempotencyKeyUpdate builder.
func (ikuo *IdempotencyKeyUpdateOne) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyUpdateOne {
	ikuo.mutation.Where(ps...)
	return ikuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ikuo *IdempotencyKeyUpdateOne) Select(field string, fields ...string) *IdempotencyKeyUpdateOne {
	ikuo.fields = append([]string{field}, fields...)
	return ikuo
}

// Save executes the query and returns the updated IdempotencyKey entity.
func (ikuo *IdempotencyKeyUpdateOne) Save(ctx context.Context) (*IdempotencyKey, error) {
	ikuo.defaults()
	return withHooks(ctx, ikuo.sqlSave, ikuo.mutation, ikuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ikuo *IdempotencyKeyUpdateOne) SaveX(ctx context.Context) *IdempotencyKey {
	node, err := ikuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ikuo *IdempotencyKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := ikuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ikuo *IdempotencyKeyUpdateOne) ExecX(ctx context.Context) {
	if err := ikuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ikuo *IdempotencyKeyUpdateOne) defaults() {
	if _, ok := ikuo.mutation.UpdateTime(); !ok {
		v := idempotencykey.UpdateDefaultUpdateTime()
		ikuo.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ikuo *IdempotencyKeyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IdempotencyKeyUpdateOne {
	ikuo.modifiers = append(ikuo.modifiers, modifiers...)
	return ikuo
}

func (ikuo *IdempotencyKeyUpdateOne) sqlSave(ctx context.Context) (_node *IdempotencyKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeUUID))
	id, ok := ikuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdempotencyKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ikuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idempotencykey.FieldID)
		for _, f := range fields {
			if !idempotencykey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idempotencykey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ikuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ikuo.mutation.UpdateTime(); ok {
		_spec.SetField(idempotencykey.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ikuo.mutation.Response(); ok {
		_spec.SetField(idempotencykey.FieldResponse, field.TypeJSON, value)
	}
	if value, ok := ikuo.mutation.AppendedResponse(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idempotencykey.FieldResponse, value)
		})
	}
	if ikuo.mutation.ResponseCleared() {
		_spec.ClearField(idempotencykey.FieldResponse, field.TypeJSON)
	}
	_spec.AddModifiers(ikuo.modifiers...)
	_node = &IdempotencyKey{config: ikuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ikuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencykey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ikuo.mutation.done = true
	return _node, nil
}
