// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenJusticeTransactionQuery is the builder for querying L1TokenJusticeTransaction entities.
type L1TokenJusticeTransactionQuery struct {
	config
	ctx                         *QueryContext
	order                       []l1tokenjusticetransaction.OrderOption
	inters                      []Interceptor
	predicates                  []predicate.L1TokenJusticeTransaction
	withTokenOutput             *TokenOutputQuery
	withL1TokenOutputWithdrawal *L1TokenOutputWithdrawalQuery
	withFKs                     bool
	modifiers                   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the L1TokenJusticeTransactionQuery builder.
func (ljtq *L1TokenJusticeTransactionQuery) Where(ps ...predicate.L1TokenJusticeTransaction) *L1TokenJusticeTransactionQuery {
	ljtq.predicates = append(ljtq.predicates, ps...)
	return ljtq
}

// Limit the number of records to be returned by this query.
func (ljtq *L1TokenJusticeTransactionQuery) Limit(limit int) *L1TokenJusticeTransactionQuery {
	ljtq.ctx.Limit = &limit
	return ljtq
}

// Offset to start from.
func (ljtq *L1TokenJusticeTransactionQuery) Offset(offset int) *L1TokenJusticeTransactionQuery {
	ljtq.ctx.Offset = &offset
	return ljtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ljtq *L1TokenJusticeTransactionQuery) Unique(unique bool) *L1TokenJusticeTransactionQuery {
	ljtq.ctx.Unique = &unique
	return ljtq
}

// Order specifies how the records should be ordered.
func (ljtq *L1TokenJusticeTransactionQuery) Order(o ...l1tokenjusticetransaction.OrderOption) *L1TokenJusticeTransactionQuery {
	ljtq.order = append(ljtq.order, o...)
	return ljtq
}

// QueryTokenOutput chains the current query on the "token_output" edge.
func (ljtq *L1TokenJusticeTransactionQuery) QueryTokenOutput() *TokenOutputQuery {
	query := (&TokenOutputClient{config: ljtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ljtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ljtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(l1tokenjusticetransaction.Table, l1tokenjusticetransaction.FieldID, selector),
			sqlgraph.To(tokenoutput.Table, tokenoutput.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, l1tokenjusticetransaction.TokenOutputTable, l1tokenjusticetransaction.TokenOutputColumn),
		)
		fromU = sqlgraph.SetNeighbors(ljtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryL1TokenOutputWithdrawal chains the current query on the "l1_token_output_withdrawal" edge.
func (ljtq *L1TokenJusticeTransactionQuery) QueryL1TokenOutputWithdrawal() *L1TokenOutputWithdrawalQuery {
	query := (&L1TokenOutputWithdrawalClient{config: ljtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ljtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ljtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(l1tokenjusticetransaction.Table, l1tokenjusticetransaction.FieldID, selector),
			sqlgraph.To(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, l1tokenjusticetransaction.L1TokenOutputWithdrawalTable, l1tokenjusticetransaction.L1TokenOutputWithdrawalColumn),
		)
		fromU = sqlgraph.SetNeighbors(ljtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first L1TokenJusticeTransaction entity from the query.
// Returns a *NotFoundError when no L1TokenJusticeTransaction was found.
func (ljtq *L1TokenJusticeTransactionQuery) First(ctx context.Context) (*L1TokenJusticeTransaction, error) {
	nodes, err := ljtq.Limit(1).All(setContextOp(ctx, ljtq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{l1tokenjusticetransaction.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) FirstX(ctx context.Context) *L1TokenJusticeTransaction {
	node, err := ljtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first L1TokenJusticeTransaction ID from the query.
// Returns a *NotFoundError when no L1TokenJusticeTransaction ID was found.
func (ljtq *L1TokenJusticeTransactionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ljtq.Limit(1).IDs(setContextOp(ctx, ljtq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{l1tokenjusticetransaction.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ljtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single L1TokenJusticeTransaction entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one L1TokenJusticeTransaction entity is found.
// Returns a *NotFoundError when no L1TokenJusticeTransaction entities are found.
func (ljtq *L1TokenJusticeTransactionQuery) Only(ctx context.Context) (*L1TokenJusticeTransaction, error) {
	nodes, err := ljtq.Limit(2).All(setContextOp(ctx, ljtq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{l1tokenjusticetransaction.Label}
	default:
		return nil, &NotSingularError{l1tokenjusticetransaction.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) OnlyX(ctx context.Context) *L1TokenJusticeTransaction {
	node, err := ljtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only L1TokenJusticeTransaction ID in the query.
// Returns a *NotSingularError when more than one L1TokenJusticeTransaction ID is found.
// Returns a *NotFoundError when no entities are found.
func (ljtq *L1TokenJusticeTransactionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ljtq.Limit(2).IDs(setContextOp(ctx, ljtq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{l1tokenjusticetransaction.Label}
	default:
		err = &NotSingularError{l1tokenjusticetransaction.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ljtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of L1TokenJusticeTransactions.
func (ljtq *L1TokenJusticeTransactionQuery) All(ctx context.Context) ([]*L1TokenJusticeTransaction, error) {
	ctx = setContextOp(ctx, ljtq.ctx, ent.OpQueryAll)
	if err := ljtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*L1TokenJusticeTransaction, *L1TokenJusticeTransactionQuery]()
	return withInterceptors[[]*L1TokenJusticeTransaction](ctx, ljtq, qr, ljtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) AllX(ctx context.Context) []*L1TokenJusticeTransaction {
	nodes, err := ljtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of L1TokenJusticeTransaction IDs.
func (ljtq *L1TokenJusticeTransactionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ljtq.ctx.Unique == nil && ljtq.path != nil {
		ljtq.Unique(true)
	}
	ctx = setContextOp(ctx, ljtq.ctx, ent.OpQueryIDs)
	if err = ljtq.Select(l1tokenjusticetransaction.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ljtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ljtq *L1TokenJusticeTransactionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ljtq.ctx, ent.OpQueryCount)
	if err := ljtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ljtq, querierCount[*L1TokenJusticeTransactionQuery](), ljtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) CountX(ctx context.Context) int {
	count, err := ljtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ljtq *L1TokenJusticeTransactionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ljtq.ctx, ent.OpQueryExist)
	switch _, err := ljtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ljtq *L1TokenJusticeTransactionQuery) ExistX(ctx context.Context) bool {
	exist, err := ljtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the L1TokenJusticeTransactionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ljtq *L1TokenJusticeTransactionQuery) Clone() *L1TokenJusticeTransactionQuery {
	if ljtq == nil {
		return nil
	}
	return &L1TokenJusticeTransactionQuery{
		config:                      ljtq.config,
		ctx:                         ljtq.ctx.Clone(),
		order:                       append([]l1tokenjusticetransaction.OrderOption{}, ljtq.order...),
		inters:                      append([]Interceptor{}, ljtq.inters...),
		predicates:                  append([]predicate.L1TokenJusticeTransaction{}, ljtq.predicates...),
		withTokenOutput:             ljtq.withTokenOutput.Clone(),
		withL1TokenOutputWithdrawal: ljtq.withL1TokenOutputWithdrawal.Clone(),
		// clone intermediate query.
		sql:       ljtq.sql.Clone(),
		path:      ljtq.path,
		modifiers: append([]func(*sql.Selector){}, ljtq.modifiers...),
	}
}

// WithTokenOutput tells the query-builder to eager-load the nodes that are connected to
// the "token_output" edge. The optional arguments are used to configure the query builder of the edge.
func (ljtq *L1TokenJusticeTransactionQuery) WithTokenOutput(opts ...func(*TokenOutputQuery)) *L1TokenJusticeTransactionQuery {
	query := (&TokenOutputClient{config: ljtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ljtq.withTokenOutput = query
	return ljtq
}

// WithL1TokenOutputWithdrawal tells the query-builder to eager-load the nodes that are connected to
// the "l1_token_output_withdrawal" edge. The optional arguments are used to configure the query builder of the edge.
func (ljtq *L1TokenJusticeTransactionQuery) WithL1TokenOutputWithdrawal(opts ...func(*L1TokenOutputWithdrawalQuery)) *L1TokenJusticeTransactionQuery {
	query := (&L1TokenOutputWithdrawalClient{config: ljtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ljtq.withL1TokenOutputWithdrawal = query
	return ljtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.L1TokenJusticeTransaction.Query().
//		GroupBy(l1tokenjusticetransaction.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ljtq *L1TokenJusticeTransactionQuery) GroupBy(field string, fields ...string) *L1TokenJusticeTransactionGroupBy {
	ljtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &L1TokenJusticeTransactionGroupBy{build: ljtq}
	grbuild.flds = &ljtq.ctx.Fields
	grbuild.label = l1tokenjusticetransaction.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.L1TokenJusticeTransaction.Query().
//		Select(l1tokenjusticetransaction.FieldCreateTime).
//		Scan(ctx, &v)
func (ljtq *L1TokenJusticeTransactionQuery) Select(fields ...string) *L1TokenJusticeTransactionSelect {
	ljtq.ctx.Fields = append(ljtq.ctx.Fields, fields...)
	sbuild := &L1TokenJusticeTransactionSelect{L1TokenJusticeTransactionQuery: ljtq}
	sbuild.label = l1tokenjusticetransaction.Label
	sbuild.flds, sbuild.scan = &ljtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a L1TokenJusticeTransactionSelect configured with the given aggregations.
func (ljtq *L1TokenJusticeTransactionQuery) Aggregate(fns ...AggregateFunc) *L1TokenJusticeTransactionSelect {
	return ljtq.Select().Aggregate(fns...)
}

func (ljtq *L1TokenJusticeTransactionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ljtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ljtq); err != nil {
				return err
			}
		}
	}
	for _, f := range ljtq.ctx.Fields {
		if !l1tokenjusticetransaction.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ljtq.path != nil {
		prev, err := ljtq.path(ctx)
		if err != nil {
			return err
		}
		ljtq.sql = prev
	}
	return nil
}

func (ljtq *L1TokenJusticeTransactionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*L1TokenJusticeTransaction, error) {
	var (
		nodes       = []*L1TokenJusticeTransaction{}
		withFKs     = ljtq.withFKs
		_spec       = ljtq.querySpec()
		loadedTypes = [2]bool{
			ljtq.withTokenOutput != nil,
			ljtq.withL1TokenOutputWithdrawal != nil,
		}
	)
	if ljtq.withTokenOutput != nil || ljtq.withL1TokenOutputWithdrawal != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, l1tokenjusticetransaction.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*L1TokenJusticeTransaction).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &L1TokenJusticeTransaction{config: ljtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ljtq.modifiers) > 0 {
		_spec.Modifiers = ljtq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ljtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ljtq.withTokenOutput; query != nil {
		if err := ljtq.loadTokenOutput(ctx, query, nodes, nil,
			func(n *L1TokenJusticeTransaction, e *TokenOutput) { n.Edges.TokenOutput = e }); err != nil {
			return nil, err
		}
	}
	if query := ljtq.withL1TokenOutputWithdrawal; query != nil {
		if err := ljtq.loadL1TokenOutputWithdrawal(ctx, query, nodes, nil,
			func(n *L1TokenJusticeTransaction, e *L1TokenOutputWithdrawal) { n.Edges.L1TokenOutputWithdrawal = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ljtq *L1TokenJusticeTransactionQuery) loadTokenOutput(ctx context.Context, query *TokenOutputQuery, nodes []*L1TokenJusticeTransaction, init func(*L1TokenJusticeTransaction), assign func(*L1TokenJusticeTransaction, *TokenOutput)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*L1TokenJusticeTransaction)
	for i := range nodes {
		if nodes[i].token_output_justice_tx == nil {
			continue
		}
		fk := *nodes[i].token_output_justice_tx
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tokenoutput.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_output_justice_tx" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ljtq *L1TokenJusticeTransactionQuery) loadL1TokenOutputWithdrawal(ctx context.Context, query *L1TokenOutputWithdrawalQuery, nodes []*L1TokenJusticeTransaction, init func(*L1TokenJusticeTransaction), assign func(*L1TokenJusticeTransaction, *L1TokenOutputWithdrawal)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*L1TokenJusticeTransaction)
	for i := range nodes {
		if nodes[i].l1token_output_withdrawal_justice_tx == nil {
			continue
		}
		fk := *nodes[i].l1token_output_withdrawal_justice_tx
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(l1tokenoutputwithdrawal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "l1token_output_withdrawal_justice_tx" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ljtq *L1TokenJusticeTransactionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ljtq.querySpec()
	if len(ljtq.modifiers) > 0 {
		_spec.Modifiers = ljtq.modifiers
	}
	_spec.Node.Columns = ljtq.ctx.Fields
	if len(ljtq.ctx.Fields) > 0 {
		_spec.Unique = ljtq.ctx.Unique != nil && *ljtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ljtq.driver, _spec)
}

func (ljtq *L1TokenJusticeTransactionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(l1tokenjusticetransaction.Table, l1tokenjusticetransaction.Columns, sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID))
	_spec.From = ljtq.sql
	if unique := ljtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ljtq.path != nil {
		_spec.Unique = true
	}
	if fields := ljtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, l1tokenjusticetransaction.FieldID)
		for i := range fields {
			if fields[i] != l1tokenjusticetransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ljtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ljtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ljtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ljtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ljtq *L1TokenJusticeTransactionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ljtq.driver.Dialect())
	t1 := builder.Table(l1tokenjusticetransaction.Table)
	columns := ljtq.ctx.Fields
	if len(columns) == 0 {
		columns = l1tokenjusticetransaction.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ljtq.sql != nil {
		selector = ljtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ljtq.ctx.Unique != nil && *ljtq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ljtq.modifiers {
		m(selector)
	}
	for _, p := range ljtq.predicates {
		p(selector)
	}
	for _, p := range ljtq.order {
		p(selector)
	}
	if offset := ljtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ljtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ljtq *L1TokenJusticeTransactionQuery) ForUpdate(opts ...sql.LockOption) *L1TokenJusticeTransactionQuery {
	if ljtq.driver.Dialect() == dialect.Postgres {
		ljtq.Unique(false)
	}
	ljtq.modifiers = append(ljtq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ljtq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ljtq *L1TokenJusticeTransactionQuery) ForShare(opts ...sql.LockOption) *L1TokenJusticeTransactionQuery {
	if ljtq.driver.Dialect() == dialect.Postgres {
		ljtq.Unique(false)
	}
	ljtq.modifiers = append(ljtq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ljtq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ljtq *L1TokenJusticeTransactionQuery) Modify(modifiers ...func(s *sql.Selector)) *L1TokenJusticeTransactionSelect {
	ljtq.modifiers = append(ljtq.modifiers, modifiers...)
	return ljtq.Select()
}

// L1TokenJusticeTransactionGroupBy is the group-by builder for L1TokenJusticeTransaction entities.
type L1TokenJusticeTransactionGroupBy struct {
	selector
	build *L1TokenJusticeTransactionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ljtgb *L1TokenJusticeTransactionGroupBy) Aggregate(fns ...AggregateFunc) *L1TokenJusticeTransactionGroupBy {
	ljtgb.fns = append(ljtgb.fns, fns...)
	return ljtgb
}

// Scan applies the selector query and scans the result into the given value.
func (ljtgb *L1TokenJusticeTransactionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ljtgb.build.ctx, ent.OpQueryGroupBy)
	if err := ljtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*L1TokenJusticeTransactionQuery, *L1TokenJusticeTransactionGroupBy](ctx, ljtgb.build, ljtgb, ljtgb.build.inters, v)
}

func (ljtgb *L1TokenJusticeTransactionGroupBy) sqlScan(ctx context.Context, root *L1TokenJusticeTransactionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ljtgb.fns))
	for _, fn := range ljtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ljtgb.flds)+len(ljtgb.fns))
		for _, f := range *ljtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ljtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ljtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// L1TokenJusticeTransactionSelect is the builder for selecting fields of L1TokenJusticeTransaction entities.
type L1TokenJusticeTransactionSelect struct {
	*L1TokenJusticeTransactionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ljts *L1TokenJusticeTransactionSelect) Aggregate(fns ...AggregateFunc) *L1TokenJusticeTransactionSelect {
	ljts.fns = append(ljts.fns, fns...)
	return ljts
}

// Scan applies the selector query and scans the result into the given value.
func (ljts *L1TokenJusticeTransactionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ljts.ctx, ent.OpQuerySelect)
	if err := ljts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*L1TokenJusticeTransactionQuery, *L1TokenJusticeTransactionSelect](ctx, ljts.L1TokenJusticeTransactionQuery, ljts, ljts.inters, v)
}

func (ljts *L1TokenJusticeTransactionSelect) sqlScan(ctx context.Context, root *L1TokenJusticeTransactionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ljts.fns))
	for _, fn := range ljts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ljts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ljts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ljts *L1TokenJusticeTransactionSelect) Modify(modifiers ...func(s *sql.Selector)) *L1TokenJusticeTransactionSelect {
	ljts.modifiers = append(ljts.modifiers, modifiers...)
	return ljts
}
