// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenJusticeTransactionUpdate is the builder for updating L1TokenJusticeTransaction entities.
type L1TokenJusticeTransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *L1TokenJusticeTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the L1TokenJusticeTransactionUpdate builder.
func (ljtu *L1TokenJusticeTransactionUpdate) Where(ps ...predicate.L1TokenJusticeTransaction) *L1TokenJusticeTransactionUpdate {
	ljtu.mutation.Where(ps...)
	return ljtu
}

// SetUpdateTime sets the "update_time" field.
func (ljtu *L1TokenJusticeTransactionUpdate) SetUpdateTime(t time.Time) *L1TokenJusticeTransactionUpdate {
	ljtu.mutation.SetUpdateTime(t)
	return ljtu
}

// SetTokenOutputID sets the "token_output" edge to the TokenOutput entity by ID.
func (ljtu *L1TokenJusticeTransactionUpdate) SetTokenOutputID(id uuid.UUID) *L1TokenJusticeTransactionUpdate {
	ljtu.mutation.SetTokenOutputID(id)
	return ljtu
}

// SetTokenOutput sets the "token_output" edge to the TokenOutput entity.
func (ljtu *L1TokenJusticeTransactionUpdate) SetTokenOutput(t *TokenOutput) *L1TokenJusticeTransactionUpdate {
	return ljtu.SetTokenOutputID(t.ID)
}

// SetL1TokenOutputWithdrawalID sets the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity by ID.
func (ljtu *L1TokenJusticeTransactionUpdate) SetL1TokenOutputWithdrawalID(id uuid.UUID) *L1TokenJusticeTransactionUpdate {
	ljtu.mutation.SetL1TokenOutputWithdrawalID(id)
	return ljtu
}

// SetL1TokenOutputWithdrawal sets the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity.
func (ljtu *L1TokenJusticeTransactionUpdate) SetL1TokenOutputWithdrawal(l *L1TokenOutputWithdrawal) *L1TokenJusticeTransactionUpdate {
	return ljtu.SetL1TokenOutputWithdrawalID(l.ID)
}

// Mutation returns the L1TokenJusticeTransactionMutation object of the builder.
func (ljtu *L1TokenJusticeTransactionUpdate) Mutation() *L1TokenJusticeTransactionMutation {
	return ljtu.mutation
}

// ClearTokenOutput clears the "token_output" edge to the TokenOutput entity.
func (ljtu *L1TokenJusticeTransactionUpdate) ClearTokenOutput() *L1TokenJusticeTransactionUpdate {
	ljtu.mutation.ClearTokenOutput()
	return ljtu
}

// ClearL1TokenOutputWithdrawal clears the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity.
func (ljtu *L1TokenJusticeTransactionUpdate) ClearL1TokenOutputWithdrawal() *L1TokenJusticeTransactionUpdate {
	ljtu.mutation.ClearL1TokenOutputWithdrawal()
	return ljtu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ljtu *L1TokenJusticeTransactionUpdate) Save(ctx context.Context) (int, error) {
	ljtu.defaults()
	return withHooks(ctx, ljtu.sqlSave, ljtu.mutation, ljtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ljtu *L1TokenJusticeTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := ljtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ljtu *L1TokenJusticeTransactionUpdate) Exec(ctx context.Context) error {
	_, err := ljtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ljtu *L1TokenJusticeTransactionUpdate) ExecX(ctx context.Context) {
	if err := ljtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ljtu *L1TokenJusticeTransactionUpdate) defaults() {
	if _, ok := ljtu.mutation.UpdateTime(); !ok {
		v := l1tokenjusticetransaction.UpdateDefaultUpdateTime()
		ljtu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ljtu *L1TokenJusticeTransactionUpdate) check() error {
	if ljtu.mutation.TokenOutputCleared() && len(ljtu.mutation.TokenOutputIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenJusticeTransaction.token_output"`)
	}
	if ljtu.mutation.L1TokenOutputWithdrawalCleared() && len(ljtu.mutation.L1TokenOutputWithdrawalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenJusticeTransaction.l1_token_output_withdrawal"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ljtu *L1TokenJusticeTransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *L1TokenJusticeTransactionUpdate {
	ljtu.modifiers = append(ljtu.modifiers, modifiers...)
	return ljtu
}

func (ljtu *L1TokenJusticeTransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ljtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(l1tokenjusticetransaction.Table, l1tokenjusticetransaction.Columns, sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID))
	if ps := ljtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ljtu.mutation.UpdateTime(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldUpdateTime, field.TypeTime, value)
	}
	if ljtu.mutation.TokenOutputCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.TokenOutputTable,
			Columns: []string{l1tokenjusticetransaction.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ljtu.mutation.TokenOutputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.TokenOutputTable,
			Columns: []string{l1tokenjusticetransaction.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ljtu.mutation.L1TokenOutputWithdrawalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.L1TokenOutputWithdrawalTable,
			Columns: []string{l1tokenjusticetransaction.L1TokenOutputWithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ljtu.mutation.L1TokenOutputWithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.L1TokenOutputWithdrawalTable,
			Columns: []string{l1tokenjusticetransaction.L1TokenOutputWithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ljtu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ljtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{l1tokenjusticetransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ljtu.mutation.done = true
	return n, nil
}

// L1TokenJusticeTransactionUpdateOne is the builder for updating a single L1TokenJusticeTransaction entity.
type L1TokenJusticeTransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *L1TokenJusticeTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) SetUpdateTime(t time.Time) *L1TokenJusticeTransactionUpdateOne {
	ljtuo.mutation.SetUpdateTime(t)
	return ljtuo
}

// SetTokenOutputID sets the "token_output" edge to the TokenOutput entity by ID.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) SetTokenOutputID(id uuid.UUID) *L1TokenJusticeTransactionUpdateOne {
	ljtuo.mutation.SetTokenOutputID(id)
	return ljtuo
}

// SetTokenOutput sets the "token_output" edge to the TokenOutput entity.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) SetTokenOutput(t *TokenOutput) *L1TokenJusticeTransactionUpdateOne {
	return ljtuo.SetTokenOutputID(t.ID)
}

// SetL1TokenOutputWithdrawalID sets the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity by ID.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) SetL1TokenOutputWithdrawalID(id uuid.UUID) *L1TokenJusticeTransactionUpdateOne {
	ljtuo.mutation.SetL1TokenOutputWithdrawalID(id)
	return ljtuo
}

// SetL1TokenOutputWithdrawal sets the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) SetL1TokenOutputWithdrawal(l *L1TokenOutputWithdrawal) *L1TokenJusticeTransactionUpdateOne {
	return ljtuo.SetL1TokenOutputWithdrawalID(l.ID)
}

// Mutation returns the L1TokenJusticeTransactionMutation object of the builder.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) Mutation() *L1TokenJusticeTransactionMutation {
	return ljtuo.mutation
}

// ClearTokenOutput clears the "token_output" edge to the TokenOutput entity.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) ClearTokenOutput() *L1TokenJusticeTransactionUpdateOne {
	ljtuo.mutation.ClearTokenOutput()
	return ljtuo
}

// ClearL1TokenOutputWithdrawal clears the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) ClearL1TokenOutputWithdrawal() *L1TokenJusticeTransactionUpdateOne {
	ljtuo.mutation.ClearL1TokenOutputWithdrawal()
	return ljtuo
}

// Where appends a list predicates to the L1TokenJusticeTransactionUpdate builder.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) Where(ps ...predicate.L1TokenJusticeTransaction) *L1TokenJusticeTransactionUpdateOne {
	ljtuo.mutation.Where(ps...)
	return ljtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) Select(field string, fields ...string) *L1TokenJusticeTransactionUpdateOne {
	ljtuo.fields = append([]string{field}, fields...)
	return ljtuo
}

// Save executes the query and returns the updated L1TokenJusticeTransaction entity.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) Save(ctx context.Context) (*L1TokenJusticeTransaction, error) {
	ljtuo.defaults()
	return withHooks(ctx, ljtuo.sqlSave, ljtuo.mutation, ljtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) SaveX(ctx context.Context) *L1TokenJusticeTransaction {
	node, err := ljtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := ljtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := ljtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) defaults() {
	if _, ok := ljtuo.mutation.UpdateTime(); !ok {
		v := l1tokenjusticetransaction.UpdateDefaultUpdateTime()
		ljtuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) check() error {
	if ljtuo.mutation.TokenOutputCleared() && len(ljtuo.mutation.TokenOutputIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenJusticeTransaction.token_output"`)
	}
	if ljtuo.mutation.L1TokenOutputWithdrawalCleared() && len(ljtuo.mutation.L1TokenOutputWithdrawalIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenJusticeTransaction.l1_token_output_withdrawal"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ljtuo *L1TokenJusticeTransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *L1TokenJusticeTransactionUpdateOne {
	ljtuo.modifiers = append(ljtuo.modifiers, modifiers...)
	return ljtuo
}

func (ljtuo *L1TokenJusticeTransactionUpdateOne) sqlSave(ctx context.Context) (_node *L1TokenJusticeTransaction, err error) {
	if err := ljtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(l1tokenjusticetransaction.Table, l1tokenjusticetransaction.Columns, sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID))
	id, ok := ljtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "L1TokenJusticeTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ljtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, l1tokenjusticetransaction.FieldID)
		for _, f := range fields {
			if !l1tokenjusticetransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != l1tokenjusticetransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ljtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ljtuo.mutation.UpdateTime(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldUpdateTime, field.TypeTime, value)
	}
	if ljtuo.mutation.TokenOutputCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.TokenOutputTable,
			Columns: []string{l1tokenjusticetransaction.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ljtuo.mutation.TokenOutputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.TokenOutputTable,
			Columns: []string{l1tokenjusticetransaction.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ljtuo.mutation.L1TokenOutputWithdrawalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.L1TokenOutputWithdrawalTable,
			Columns: []string{l1tokenjusticetransaction.L1TokenOutputWithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ljtuo.mutation.L1TokenOutputWithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.L1TokenOutputWithdrawalTable,
			Columns: []string{l1tokenjusticetransaction.L1TokenOutputWithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(ljtuo.modifiers...)
	_node = &L1TokenJusticeTransaction{config: ljtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ljtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{l1tokenjusticetransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ljtuo.mutation.done = true
	return _node, nil
}
