// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/l1withdrawaltransaction"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenOutputWithdrawalQuery is the builder for querying L1TokenOutputWithdrawal entities.
type L1TokenOutputWithdrawalQuery struct {
	config
	ctx                         *QueryContext
	order                       []l1tokenoutputwithdrawal.OrderOption
	inters                      []Interceptor
	predicates                  []predicate.L1TokenOutputWithdrawal
	withTokenOutput             *TokenOutputQuery
	withL1WithdrawalTransaction *L1WithdrawalTransactionQuery
	withJusticeTx               *L1TokenJusticeTransactionQuery
	withFKs                     bool
	modifiers                   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the L1TokenOutputWithdrawalQuery builder.
func (lowq *L1TokenOutputWithdrawalQuery) Where(ps ...predicate.L1TokenOutputWithdrawal) *L1TokenOutputWithdrawalQuery {
	lowq.predicates = append(lowq.predicates, ps...)
	return lowq
}

// Limit the number of records to be returned by this query.
func (lowq *L1TokenOutputWithdrawalQuery) Limit(limit int) *L1TokenOutputWithdrawalQuery {
	lowq.ctx.Limit = &limit
	return lowq
}

// Offset to start from.
func (lowq *L1TokenOutputWithdrawalQuery) Offset(offset int) *L1TokenOutputWithdrawalQuery {
	lowq.ctx.Offset = &offset
	return lowq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lowq *L1TokenOutputWithdrawalQuery) Unique(unique bool) *L1TokenOutputWithdrawalQuery {
	lowq.ctx.Unique = &unique
	return lowq
}

// Order specifies how the records should be ordered.
func (lowq *L1TokenOutputWithdrawalQuery) Order(o ...l1tokenoutputwithdrawal.OrderOption) *L1TokenOutputWithdrawalQuery {
	lowq.order = append(lowq.order, o...)
	return lowq
}

// QueryTokenOutput chains the current query on the "token_output" edge.
func (lowq *L1TokenOutputWithdrawalQuery) QueryTokenOutput() *TokenOutputQuery {
	query := (&TokenOutputClient{config: lowq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lowq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lowq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.FieldID, selector),
			sqlgraph.To(tokenoutput.Table, tokenoutput.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, l1tokenoutputwithdrawal.TokenOutputTable, l1tokenoutputwithdrawal.TokenOutputColumn),
		)
		fromU = sqlgraph.SetNeighbors(lowq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryL1WithdrawalTransaction chains the current query on the "l1_withdrawal_transaction" edge.
func (lowq *L1TokenOutputWithdrawalQuery) QueryL1WithdrawalTransaction() *L1WithdrawalTransactionQuery {
	query := (&L1WithdrawalTransactionClient{config: lowq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lowq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lowq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.FieldID, selector),
			sqlgraph.To(l1withdrawaltransaction.Table, l1withdrawaltransaction.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, l1tokenoutputwithdrawal.L1WithdrawalTransactionTable, l1tokenoutputwithdrawal.L1WithdrawalTransactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(lowq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJusticeTx chains the current query on the "justice_tx" edge.
func (lowq *L1TokenOutputWithdrawalQuery) QueryJusticeTx() *L1TokenJusticeTransactionQuery {
	query := (&L1TokenJusticeTransactionClient{config: lowq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lowq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lowq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.FieldID, selector),
			sqlgraph.To(l1tokenjusticetransaction.Table, l1tokenjusticetransaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, l1tokenoutputwithdrawal.JusticeTxTable, l1tokenoutputwithdrawal.JusticeTxColumn),
		)
		fromU = sqlgraph.SetNeighbors(lowq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first L1TokenOutputWithdrawal entity from the query.
// Returns a *NotFoundError when no L1TokenOutputWithdrawal was found.
func (lowq *L1TokenOutputWithdrawalQuery) First(ctx context.Context) (*L1TokenOutputWithdrawal, error) {
	nodes, err := lowq.Limit(1).All(setContextOp(ctx, lowq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{l1tokenoutputwithdrawal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) FirstX(ctx context.Context) *L1TokenOutputWithdrawal {
	node, err := lowq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first L1TokenOutputWithdrawal ID from the query.
// Returns a *NotFoundError when no L1TokenOutputWithdrawal ID was found.
func (lowq *L1TokenOutputWithdrawalQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lowq.Limit(1).IDs(setContextOp(ctx, lowq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{l1tokenoutputwithdrawal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := lowq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single L1TokenOutputWithdrawal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one L1TokenOutputWithdrawal entity is found.
// Returns a *NotFoundError when no L1TokenOutputWithdrawal entities are found.
func (lowq *L1TokenOutputWithdrawalQuery) Only(ctx context.Context) (*L1TokenOutputWithdrawal, error) {
	nodes, err := lowq.Limit(2).All(setContextOp(ctx, lowq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{l1tokenoutputwithdrawal.Label}
	default:
		return nil, &NotSingularError{l1tokenoutputwithdrawal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) OnlyX(ctx context.Context) *L1TokenOutputWithdrawal {
	node, err := lowq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only L1TokenOutputWithdrawal ID in the query.
// Returns a *NotSingularError when more than one L1TokenOutputWithdrawal ID is found.
// Returns a *NotFoundError when no entities are found.
func (lowq *L1TokenOutputWithdrawalQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lowq.Limit(2).IDs(setContextOp(ctx, lowq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{l1tokenoutputwithdrawal.Label}
	default:
		err = &NotSingularError{l1tokenoutputwithdrawal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := lowq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of L1TokenOutputWithdrawals.
func (lowq *L1TokenOutputWithdrawalQuery) All(ctx context.Context) ([]*L1TokenOutputWithdrawal, error) {
	ctx = setContextOp(ctx, lowq.ctx, ent.OpQueryAll)
	if err := lowq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*L1TokenOutputWithdrawal, *L1TokenOutputWithdrawalQuery]()
	return withInterceptors[[]*L1TokenOutputWithdrawal](ctx, lowq, qr, lowq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) AllX(ctx context.Context) []*L1TokenOutputWithdrawal {
	nodes, err := lowq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of L1TokenOutputWithdrawal IDs.
func (lowq *L1TokenOutputWithdrawalQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if lowq.ctx.Unique == nil && lowq.path != nil {
		lowq.Unique(true)
	}
	ctx = setContextOp(ctx, lowq.ctx, ent.OpQueryIDs)
	if err = lowq.Select(l1tokenoutputwithdrawal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := lowq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lowq *L1TokenOutputWithdrawalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lowq.ctx, ent.OpQueryCount)
	if err := lowq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lowq, querierCount[*L1TokenOutputWithdrawalQuery](), lowq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) CountX(ctx context.Context) int {
	count, err := lowq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lowq *L1TokenOutputWithdrawalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lowq.ctx, ent.OpQueryExist)
	switch _, err := lowq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lowq *L1TokenOutputWithdrawalQuery) ExistX(ctx context.Context) bool {
	exist, err := lowq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the L1TokenOutputWithdrawalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lowq *L1TokenOutputWithdrawalQuery) Clone() *L1TokenOutputWithdrawalQuery {
	if lowq == nil {
		return nil
	}
	return &L1TokenOutputWithdrawalQuery{
		config:                      lowq.config,
		ctx:                         lowq.ctx.Clone(),
		order:                       append([]l1tokenoutputwithdrawal.OrderOption{}, lowq.order...),
		inters:                      append([]Interceptor{}, lowq.inters...),
		predicates:                  append([]predicate.L1TokenOutputWithdrawal{}, lowq.predicates...),
		withTokenOutput:             lowq.withTokenOutput.Clone(),
		withL1WithdrawalTransaction: lowq.withL1WithdrawalTransaction.Clone(),
		withJusticeTx:               lowq.withJusticeTx.Clone(),
		// clone intermediate query.
		sql:       lowq.sql.Clone(),
		path:      lowq.path,
		modifiers: append([]func(*sql.Selector){}, lowq.modifiers...),
	}
}

// WithTokenOutput tells the query-builder to eager-load the nodes that are connected to
// the "token_output" edge. The optional arguments are used to configure the query builder of the edge.
func (lowq *L1TokenOutputWithdrawalQuery) WithTokenOutput(opts ...func(*TokenOutputQuery)) *L1TokenOutputWithdrawalQuery {
	query := (&TokenOutputClient{config: lowq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lowq.withTokenOutput = query
	return lowq
}

// WithL1WithdrawalTransaction tells the query-builder to eager-load the nodes that are connected to
// the "l1_withdrawal_transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (lowq *L1TokenOutputWithdrawalQuery) WithL1WithdrawalTransaction(opts ...func(*L1WithdrawalTransactionQuery)) *L1TokenOutputWithdrawalQuery {
	query := (&L1WithdrawalTransactionClient{config: lowq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lowq.withL1WithdrawalTransaction = query
	return lowq
}

// WithJusticeTx tells the query-builder to eager-load the nodes that are connected to
// the "justice_tx" edge. The optional arguments are used to configure the query builder of the edge.
func (lowq *L1TokenOutputWithdrawalQuery) WithJusticeTx(opts ...func(*L1TokenJusticeTransactionQuery)) *L1TokenOutputWithdrawalQuery {
	query := (&L1TokenJusticeTransactionClient{config: lowq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lowq.withJusticeTx = query
	return lowq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.L1TokenOutputWithdrawal.Query().
//		GroupBy(l1tokenoutputwithdrawal.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lowq *L1TokenOutputWithdrawalQuery) GroupBy(field string, fields ...string) *L1TokenOutputWithdrawalGroupBy {
	lowq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &L1TokenOutputWithdrawalGroupBy{build: lowq}
	grbuild.flds = &lowq.ctx.Fields
	grbuild.label = l1tokenoutputwithdrawal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.L1TokenOutputWithdrawal.Query().
//		Select(l1tokenoutputwithdrawal.FieldCreateTime).
//		Scan(ctx, &v)
func (lowq *L1TokenOutputWithdrawalQuery) Select(fields ...string) *L1TokenOutputWithdrawalSelect {
	lowq.ctx.Fields = append(lowq.ctx.Fields, fields...)
	sbuild := &L1TokenOutputWithdrawalSelect{L1TokenOutputWithdrawalQuery: lowq}
	sbuild.label = l1tokenoutputwithdrawal.Label
	sbuild.flds, sbuild.scan = &lowq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a L1TokenOutputWithdrawalSelect configured with the given aggregations.
func (lowq *L1TokenOutputWithdrawalQuery) Aggregate(fns ...AggregateFunc) *L1TokenOutputWithdrawalSelect {
	return lowq.Select().Aggregate(fns...)
}

func (lowq *L1TokenOutputWithdrawalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lowq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lowq); err != nil {
				return err
			}
		}
	}
	for _, f := range lowq.ctx.Fields {
		if !l1tokenoutputwithdrawal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lowq.path != nil {
		prev, err := lowq.path(ctx)
		if err != nil {
			return err
		}
		lowq.sql = prev
	}
	return nil
}

func (lowq *L1TokenOutputWithdrawalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*L1TokenOutputWithdrawal, error) {
	var (
		nodes       = []*L1TokenOutputWithdrawal{}
		withFKs     = lowq.withFKs
		_spec       = lowq.querySpec()
		loadedTypes = [3]bool{
			lowq.withTokenOutput != nil,
			lowq.withL1WithdrawalTransaction != nil,
			lowq.withJusticeTx != nil,
		}
	)
	if lowq.withTokenOutput != nil || lowq.withL1WithdrawalTransaction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, l1tokenoutputwithdrawal.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*L1TokenOutputWithdrawal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &L1TokenOutputWithdrawal{config: lowq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(lowq.modifiers) > 0 {
		_spec.Modifiers = lowq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lowq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lowq.withTokenOutput; query != nil {
		if err := lowq.loadTokenOutput(ctx, query, nodes, nil,
			func(n *L1TokenOutputWithdrawal, e *TokenOutput) { n.Edges.TokenOutput = e }); err != nil {
			return nil, err
		}
	}
	if query := lowq.withL1WithdrawalTransaction; query != nil {
		if err := lowq.loadL1WithdrawalTransaction(ctx, query, nodes, nil,
			func(n *L1TokenOutputWithdrawal, e *L1WithdrawalTransaction) { n.Edges.L1WithdrawalTransaction = e }); err != nil {
			return nil, err
		}
	}
	if query := lowq.withJusticeTx; query != nil {
		if err := lowq.loadJusticeTx(ctx, query, nodes, nil,
			func(n *L1TokenOutputWithdrawal, e *L1TokenJusticeTransaction) { n.Edges.JusticeTx = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lowq *L1TokenOutputWithdrawalQuery) loadTokenOutput(ctx context.Context, query *TokenOutputQuery, nodes []*L1TokenOutputWithdrawal, init func(*L1TokenOutputWithdrawal), assign func(*L1TokenOutputWithdrawal, *TokenOutput)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*L1TokenOutputWithdrawal)
	for i := range nodes {
		if nodes[i].token_output_withdrawal == nil {
			continue
		}
		fk := *nodes[i].token_output_withdrawal
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tokenoutput.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_output_withdrawal" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (lowq *L1TokenOutputWithdrawalQuery) loadL1WithdrawalTransaction(ctx context.Context, query *L1WithdrawalTransactionQuery, nodes []*L1TokenOutputWithdrawal, init func(*L1TokenOutputWithdrawal), assign func(*L1TokenOutputWithdrawal, *L1WithdrawalTransaction)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*L1TokenOutputWithdrawal)
	for i := range nodes {
		if nodes[i].l1withdrawal_transaction_withdrawals == nil {
			continue
		}
		fk := *nodes[i].l1withdrawal_transaction_withdrawals
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(l1withdrawaltransaction.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "l1withdrawal_transaction_withdrawals" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (lowq *L1TokenOutputWithdrawalQuery) loadJusticeTx(ctx context.Context, query *L1TokenJusticeTransactionQuery, nodes []*L1TokenOutputWithdrawal, init func(*L1TokenOutputWithdrawal), assign func(*L1TokenOutputWithdrawal, *L1TokenJusticeTransaction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*L1TokenOutputWithdrawal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.L1TokenJusticeTransaction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(l1tokenoutputwithdrawal.JusticeTxColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.l1token_output_withdrawal_justice_tx
		if fk == nil {
			return fmt.Errorf(`foreign-key "l1token_output_withdrawal_justice_tx" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "l1token_output_withdrawal_justice_tx" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lowq *L1TokenOutputWithdrawalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lowq.querySpec()
	if len(lowq.modifiers) > 0 {
		_spec.Modifiers = lowq.modifiers
	}
	_spec.Node.Columns = lowq.ctx.Fields
	if len(lowq.ctx.Fields) > 0 {
		_spec.Unique = lowq.ctx.Unique != nil && *lowq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lowq.driver, _spec)
}

func (lowq *L1TokenOutputWithdrawalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.Columns, sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID))
	_spec.From = lowq.sql
	if unique := lowq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lowq.path != nil {
		_spec.Unique = true
	}
	if fields := lowq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, l1tokenoutputwithdrawal.FieldID)
		for i := range fields {
			if fields[i] != l1tokenoutputwithdrawal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lowq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lowq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lowq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lowq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lowq *L1TokenOutputWithdrawalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lowq.driver.Dialect())
	t1 := builder.Table(l1tokenoutputwithdrawal.Table)
	columns := lowq.ctx.Fields
	if len(columns) == 0 {
		columns = l1tokenoutputwithdrawal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lowq.sql != nil {
		selector = lowq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lowq.ctx.Unique != nil && *lowq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range lowq.modifiers {
		m(selector)
	}
	for _, p := range lowq.predicates {
		p(selector)
	}
	for _, p := range lowq.order {
		p(selector)
	}
	if offset := lowq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lowq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (lowq *L1TokenOutputWithdrawalQuery) ForUpdate(opts ...sql.LockOption) *L1TokenOutputWithdrawalQuery {
	if lowq.driver.Dialect() == dialect.Postgres {
		lowq.Unique(false)
	}
	lowq.modifiers = append(lowq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return lowq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (lowq *L1TokenOutputWithdrawalQuery) ForShare(opts ...sql.LockOption) *L1TokenOutputWithdrawalQuery {
	if lowq.driver.Dialect() == dialect.Postgres {
		lowq.Unique(false)
	}
	lowq.modifiers = append(lowq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return lowq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lowq *L1TokenOutputWithdrawalQuery) Modify(modifiers ...func(s *sql.Selector)) *L1TokenOutputWithdrawalSelect {
	lowq.modifiers = append(lowq.modifiers, modifiers...)
	return lowq.Select()
}

// L1TokenOutputWithdrawalGroupBy is the group-by builder for L1TokenOutputWithdrawal entities.
type L1TokenOutputWithdrawalGroupBy struct {
	selector
	build *L1TokenOutputWithdrawalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lowgb *L1TokenOutputWithdrawalGroupBy) Aggregate(fns ...AggregateFunc) *L1TokenOutputWithdrawalGroupBy {
	lowgb.fns = append(lowgb.fns, fns...)
	return lowgb
}

// Scan applies the selector query and scans the result into the given value.
func (lowgb *L1TokenOutputWithdrawalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lowgb.build.ctx, ent.OpQueryGroupBy)
	if err := lowgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*L1TokenOutputWithdrawalQuery, *L1TokenOutputWithdrawalGroupBy](ctx, lowgb.build, lowgb, lowgb.build.inters, v)
}

func (lowgb *L1TokenOutputWithdrawalGroupBy) sqlScan(ctx context.Context, root *L1TokenOutputWithdrawalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lowgb.fns))
	for _, fn := range lowgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lowgb.flds)+len(lowgb.fns))
		for _, f := range *lowgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lowgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lowgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// L1TokenOutputWithdrawalSelect is the builder for selecting fields of L1TokenOutputWithdrawal entities.
type L1TokenOutputWithdrawalSelect struct {
	*L1TokenOutputWithdrawalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lows *L1TokenOutputWithdrawalSelect) Aggregate(fns ...AggregateFunc) *L1TokenOutputWithdrawalSelect {
	lows.fns = append(lows.fns, fns...)
	return lows
}

// Scan applies the selector query and scans the result into the given value.
func (lows *L1TokenOutputWithdrawalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lows.ctx, ent.OpQuerySelect)
	if err := lows.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*L1TokenOutputWithdrawalQuery, *L1TokenOutputWithdrawalSelect](ctx, lows.L1TokenOutputWithdrawalQuery, lows, lows.inters, v)
}

func (lows *L1TokenOutputWithdrawalSelect) sqlScan(ctx context.Context, root *L1TokenOutputWithdrawalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lows.fns))
	for _, fn := range lows.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lows.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lows.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (lows *L1TokenOutputWithdrawalSelect) Modify(modifiers ...func(s *sql.Selector)) *L1TokenOutputWithdrawalSelect {
	lows.modifiers = append(lows.modifiers, modifiers...)
	return lows
}
