// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenJusticeTransactionCreate is the builder for creating a L1TokenJusticeTransaction entity.
type L1TokenJusticeTransactionCreate struct {
	config
	mutation *L1TokenJusticeTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetCreateTime(t time.Time) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetCreateTime(t)
	return ljtc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ljtc *L1TokenJusticeTransactionCreate) SetNillableCreateTime(t *time.Time) *L1TokenJusticeTransactionCreate {
	if t != nil {
		ljtc.SetCreateTime(*t)
	}
	return ljtc
}

// SetUpdateTime sets the "update_time" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetUpdateTime(t time.Time) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetUpdateTime(t)
	return ljtc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ljtc *L1TokenJusticeTransactionCreate) SetNillableUpdateTime(t *time.Time) *L1TokenJusticeTransactionCreate {
	if t != nil {
		ljtc.SetUpdateTime(*t)
	}
	return ljtc
}

// SetJusticeTxHash sets the "justice_tx_hash" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetJusticeTxHash(si schematype.TxID) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetJusticeTxHash(si)
	return ljtc
}

// SetBroadcastAt sets the "broadcast_at" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetBroadcastAt(t time.Time) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetBroadcastAt(t)
	return ljtc
}

// SetAmountSats sets the "amount_sats" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetAmountSats(u uint64) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetAmountSats(u)
	return ljtc
}

// SetTxCostSats sets the "tx_cost_sats" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetTxCostSats(u uint64) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetTxCostSats(u)
	return ljtc
}

// SetID sets the "id" field.
func (ljtc *L1TokenJusticeTransactionCreate) SetID(u uuid.UUID) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetID(u)
	return ljtc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ljtc *L1TokenJusticeTransactionCreate) SetNillableID(u *uuid.UUID) *L1TokenJusticeTransactionCreate {
	if u != nil {
		ljtc.SetID(*u)
	}
	return ljtc
}

// SetTokenOutputID sets the "token_output" edge to the TokenOutput entity by ID.
func (ljtc *L1TokenJusticeTransactionCreate) SetTokenOutputID(id uuid.UUID) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetTokenOutputID(id)
	return ljtc
}

// SetTokenOutput sets the "token_output" edge to the TokenOutput entity.
func (ljtc *L1TokenJusticeTransactionCreate) SetTokenOutput(t *TokenOutput) *L1TokenJusticeTransactionCreate {
	return ljtc.SetTokenOutputID(t.ID)
}

// SetL1TokenOutputWithdrawalID sets the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity by ID.
func (ljtc *L1TokenJusticeTransactionCreate) SetL1TokenOutputWithdrawalID(id uuid.UUID) *L1TokenJusticeTransactionCreate {
	ljtc.mutation.SetL1TokenOutputWithdrawalID(id)
	return ljtc
}

// SetL1TokenOutputWithdrawal sets the "l1_token_output_withdrawal" edge to the L1TokenOutputWithdrawal entity.
func (ljtc *L1TokenJusticeTransactionCreate) SetL1TokenOutputWithdrawal(l *L1TokenOutputWithdrawal) *L1TokenJusticeTransactionCreate {
	return ljtc.SetL1TokenOutputWithdrawalID(l.ID)
}

// Mutation returns the L1TokenJusticeTransactionMutation object of the builder.
func (ljtc *L1TokenJusticeTransactionCreate) Mutation() *L1TokenJusticeTransactionMutation {
	return ljtc.mutation
}

// Save creates the L1TokenJusticeTransaction in the database.
func (ljtc *L1TokenJusticeTransactionCreate) Save(ctx context.Context) (*L1TokenJusticeTransaction, error) {
	ljtc.defaults()
	return withHooks(ctx, ljtc.sqlSave, ljtc.mutation, ljtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ljtc *L1TokenJusticeTransactionCreate) SaveX(ctx context.Context) *L1TokenJusticeTransaction {
	v, err := ljtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ljtc *L1TokenJusticeTransactionCreate) Exec(ctx context.Context) error {
	_, err := ljtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ljtc *L1TokenJusticeTransactionCreate) ExecX(ctx context.Context) {
	if err := ljtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ljtc *L1TokenJusticeTransactionCreate) defaults() {
	if _, ok := ljtc.mutation.CreateTime(); !ok {
		v := l1tokenjusticetransaction.DefaultCreateTime()
		ljtc.mutation.SetCreateTime(v)
	}
	if _, ok := ljtc.mutation.UpdateTime(); !ok {
		v := l1tokenjusticetransaction.DefaultUpdateTime()
		ljtc.mutation.SetUpdateTime(v)
	}
	if _, ok := ljtc.mutation.ID(); !ok {
		v := l1tokenjusticetransaction.DefaultID()
		ljtc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ljtc *L1TokenJusticeTransactionCreate) check() error {
	if _, ok := ljtc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "L1TokenJusticeTransaction.create_time"`)}
	}
	if _, ok := ljtc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "L1TokenJusticeTransaction.update_time"`)}
	}
	if _, ok := ljtc.mutation.JusticeTxHash(); !ok {
		return &ValidationError{Name: "justice_tx_hash", err: errors.New(`ent: missing required field "L1TokenJusticeTransaction.justice_tx_hash"`)}
	}
	if _, ok := ljtc.mutation.BroadcastAt(); !ok {
		return &ValidationError{Name: "broadcast_at", err: errors.New(`ent: missing required field "L1TokenJusticeTransaction.broadcast_at"`)}
	}
	if _, ok := ljtc.mutation.AmountSats(); !ok {
		return &ValidationError{Name: "amount_sats", err: errors.New(`ent: missing required field "L1TokenJusticeTransaction.amount_sats"`)}
	}
	if _, ok := ljtc.mutation.TxCostSats(); !ok {
		return &ValidationError{Name: "tx_cost_sats", err: errors.New(`ent: missing required field "L1TokenJusticeTransaction.tx_cost_sats"`)}
	}
	if len(ljtc.mutation.TokenOutputIDs()) == 0 {
		return &ValidationError{Name: "token_output", err: errors.New(`ent: missing required edge "L1TokenJusticeTransaction.token_output"`)}
	}
	if len(ljtc.mutation.L1TokenOutputWithdrawalIDs()) == 0 {
		return &ValidationError{Name: "l1_token_output_withdrawal", err: errors.New(`ent: missing required edge "L1TokenJusticeTransaction.l1_token_output_withdrawal"`)}
	}
	return nil
}

func (ljtc *L1TokenJusticeTransactionCreate) sqlSave(ctx context.Context) (*L1TokenJusticeTransaction, error) {
	if err := ljtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ljtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ljtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ljtc.mutation.id = &_node.ID
	ljtc.mutation.done = true
	return _node, nil
}

func (ljtc *L1TokenJusticeTransactionCreate) createSpec() (*L1TokenJusticeTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &L1TokenJusticeTransaction{config: ljtc.config}
		_spec = sqlgraph.NewCreateSpec(l1tokenjusticetransaction.Table, sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = ljtc.conflict
	if id, ok := ljtc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ljtc.mutation.CreateTime(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := ljtc.mutation.UpdateTime(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := ljtc.mutation.JusticeTxHash(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldJusticeTxHash, field.TypeBytes, value)
		_node.JusticeTxHash = value
	}
	if value, ok := ljtc.mutation.BroadcastAt(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldBroadcastAt, field.TypeTime, value)
		_node.BroadcastAt = value
	}
	if value, ok := ljtc.mutation.AmountSats(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldAmountSats, field.TypeUint64, value)
		_node.AmountSats = value
	}
	if value, ok := ljtc.mutation.TxCostSats(); ok {
		_spec.SetField(l1tokenjusticetransaction.FieldTxCostSats, field.TypeUint64, value)
		_node.TxCostSats = value
	}
	if nodes := ljtc.mutation.TokenOutputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.TokenOutputTable,
			Columns: []string{l1tokenjusticetransaction.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.token_output_justice_tx = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ljtc.mutation.L1TokenOutputWithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenjusticetransaction.L1TokenOutputWithdrawalTable,
			Columns: []string{l1tokenjusticetransaction.L1TokenOutputWithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.l1token_output_withdrawal_justice_tx = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.L1TokenJusticeTransaction.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.L1TokenJusticeTransactionUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (ljtc *L1TokenJusticeTransactionCreate) OnConflict(opts ...sql.ConflictOption) *L1TokenJusticeTransactionUpsertOne {
	ljtc.conflict = opts
	return &L1TokenJusticeTransactionUpsertOne{
		create: ljtc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.L1TokenJusticeTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ljtc *L1TokenJusticeTransactionCreate) OnConflictColumns(columns ...string) *L1TokenJusticeTransactionUpsertOne {
	ljtc.conflict = append(ljtc.conflict, sql.ConflictColumns(columns...))
	return &L1TokenJusticeTransactionUpsertOne{
		create: ljtc,
	}
}

type (
	// L1TokenJusticeTransactionUpsertOne is the builder for "upsert"-ing
	//  one L1TokenJusticeTransaction node.
	L1TokenJusticeTransactionUpsertOne struct {
		create *L1TokenJusticeTransactionCreate
	}

	// L1TokenJusticeTransactionUpsert is the "OnConflict" setter.
	L1TokenJusticeTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *L1TokenJusticeTransactionUpsert) SetUpdateTime(v time.Time) *L1TokenJusticeTransactionUpsert {
	u.Set(l1tokenjusticetransaction.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *L1TokenJusticeTransactionUpsert) UpdateUpdateTime() *L1TokenJusticeTransactionUpsert {
	u.SetExcluded(l1tokenjusticetransaction.FieldUpdateTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.L1TokenJusticeTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(l1tokenjusticetransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *L1TokenJusticeTransactionUpsertOne) UpdateNewValues() *L1TokenJusticeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(l1tokenjusticetransaction.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(l1tokenjusticetransaction.FieldCreateTime)
		}
		if _, exists := u.create.mutation.JusticeTxHash(); exists {
			s.SetIgnore(l1tokenjusticetransaction.FieldJusticeTxHash)
		}
		if _, exists := u.create.mutation.BroadcastAt(); exists {
			s.SetIgnore(l1tokenjusticetransaction.FieldBroadcastAt)
		}
		if _, exists := u.create.mutation.AmountSats(); exists {
			s.SetIgnore(l1tokenjusticetransaction.FieldAmountSats)
		}
		if _, exists := u.create.mutation.TxCostSats(); exists {
			s.SetIgnore(l1tokenjusticetransaction.FieldTxCostSats)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.L1TokenJusticeTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *L1TokenJusticeTransactionUpsertOne) Ignore() *L1TokenJusticeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *L1TokenJusticeTransactionUpsertOne) DoNothing() *L1TokenJusticeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the L1TokenJusticeTransactionCreate.OnConflict
// documentation for more info.
func (u *L1TokenJusticeTransactionUpsertOne) Update(set func(*L1TokenJusticeTransactionUpsert)) *L1TokenJusticeTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&L1TokenJusticeTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *L1TokenJusticeTransactionUpsertOne) SetUpdateTime(v time.Time) *L1TokenJusticeTransactionUpsertOne {
	return u.Update(func(s *L1TokenJusticeTransactionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *L1TokenJusticeTransactionUpsertOne) UpdateUpdateTime() *L1TokenJusticeTransactionUpsertOne {
	return u.Update(func(s *L1TokenJusticeTransactionUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *L1TokenJusticeTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for L1TokenJusticeTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *L1TokenJusticeTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *L1TokenJusticeTransactionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: L1TokenJusticeTransactionUpsertOne.ID is not supported by MySQL driver. Use L1TokenJusticeTransactionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *L1TokenJusticeTransactionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// L1TokenJusticeTransactionCreateBulk is the builder for creating many L1TokenJusticeTransaction entities in bulk.
type L1TokenJusticeTransactionCreateBulk struct {
	config
	err      error
	builders []*L1TokenJusticeTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the L1TokenJusticeTransaction entities in the database.
func (ljtcb *L1TokenJusticeTransactionCreateBulk) Save(ctx context.Context) ([]*L1TokenJusticeTransaction, error) {
	if ljtcb.err != nil {
		return nil, ljtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ljtcb.builders))
	nodes := make([]*L1TokenJusticeTransaction, len(ljtcb.builders))
	mutators := make([]Mutator, len(ljtcb.builders))
	for i := range ljtcb.builders {
		func(i int, root context.Context) {
			builder := ljtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*L1TokenJusticeTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ljtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ljtcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ljtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ljtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ljtcb *L1TokenJusticeTransactionCreateBulk) SaveX(ctx context.Context) []*L1TokenJusticeTransaction {
	v, err := ljtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ljtcb *L1TokenJusticeTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := ljtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ljtcb *L1TokenJusticeTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := ljtcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.L1TokenJusticeTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.L1TokenJusticeTransactionUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (ljtcb *L1TokenJusticeTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *L1TokenJusticeTransactionUpsertBulk {
	ljtcb.conflict = opts
	return &L1TokenJusticeTransactionUpsertBulk{
		create: ljtcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.L1TokenJusticeTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ljtcb *L1TokenJusticeTransactionCreateBulk) OnConflictColumns(columns ...string) *L1TokenJusticeTransactionUpsertBulk {
	ljtcb.conflict = append(ljtcb.conflict, sql.ConflictColumns(columns...))
	return &L1TokenJusticeTransactionUpsertBulk{
		create: ljtcb,
	}
}

// L1TokenJusticeTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of L1TokenJusticeTransaction nodes.
type L1TokenJusticeTransactionUpsertBulk struct {
	create *L1TokenJusticeTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.L1TokenJusticeTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(l1tokenjusticetransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *L1TokenJusticeTransactionUpsertBulk) UpdateNewValues() *L1TokenJusticeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(l1tokenjusticetransaction.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(l1tokenjusticetransaction.FieldCreateTime)
			}
			if _, exists := b.mutation.JusticeTxHash(); exists {
				s.SetIgnore(l1tokenjusticetransaction.FieldJusticeTxHash)
			}
			if _, exists := b.mutation.BroadcastAt(); exists {
				s.SetIgnore(l1tokenjusticetransaction.FieldBroadcastAt)
			}
			if _, exists := b.mutation.AmountSats(); exists {
				s.SetIgnore(l1tokenjusticetransaction.FieldAmountSats)
			}
			if _, exists := b.mutation.TxCostSats(); exists {
				s.SetIgnore(l1tokenjusticetransaction.FieldTxCostSats)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.L1TokenJusticeTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *L1TokenJusticeTransactionUpsertBulk) Ignore() *L1TokenJusticeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *L1TokenJusticeTransactionUpsertBulk) DoNothing() *L1TokenJusticeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the L1TokenJusticeTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *L1TokenJusticeTransactionUpsertBulk) Update(set func(*L1TokenJusticeTransactionUpsert)) *L1TokenJusticeTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&L1TokenJusticeTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *L1TokenJusticeTransactionUpsertBulk) SetUpdateTime(v time.Time) *L1TokenJusticeTransactionUpsertBulk {
	return u.Update(func(s *L1TokenJusticeTransactionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *L1TokenJusticeTransactionUpsertBulk) UpdateUpdateTime() *L1TokenJusticeTransactionUpsertBulk {
	return u.Update(func(s *L1TokenJusticeTransactionUpsert) {
		s.UpdateUpdateTime()
	})
}

// Exec executes the query.
func (u *L1TokenJusticeTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the L1TokenJusticeTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for L1TokenJusticeTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *L1TokenJusticeTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
