// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/l1withdrawaltransaction"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenOutputWithdrawal is the model entity for the L1TokenOutputWithdrawal schema.
type L1TokenOutputWithdrawal struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Output index in the L1 transaction where the withdrawn tokens were sent.
	BitcoinVout uint16 `json:"bitcoin_vout,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the L1TokenOutputWithdrawalQuery when eager-loading is set.
	Edges                                L1TokenOutputWithdrawalEdges `json:"edges"`
	l1withdrawal_transaction_withdrawals *uuid.UUID
	token_output_withdrawal              *uuid.UUID
	selectValues                         sql.SelectValues
}

// L1TokenOutputWithdrawalEdges holds the relations/edges for other nodes in the graph.
type L1TokenOutputWithdrawalEdges struct {
	// The token output that was withdrawn.
	TokenOutput *TokenOutput `json:"token_output,omitempty"`
	// The L1 transaction containing this withdrawal.
	L1WithdrawalTransaction *L1WithdrawalTransaction `json:"l1_withdrawal_transaction,omitempty"`
	// The justice transaction if this withdrawal was invalid and punished.
	JusticeTx *L1TokenJusticeTransaction `json:"justice_tx,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TokenOutputOrErr returns the TokenOutput value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e L1TokenOutputWithdrawalEdges) TokenOutputOrErr() (*TokenOutput, error) {
	if e.TokenOutput != nil {
		return e.TokenOutput, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tokenoutput.Label}
	}
	return nil, &NotLoadedError{edge: "token_output"}
}

// L1WithdrawalTransactionOrErr returns the L1WithdrawalTransaction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e L1TokenOutputWithdrawalEdges) L1WithdrawalTransactionOrErr() (*L1WithdrawalTransaction, error) {
	if e.L1WithdrawalTransaction != nil {
		return e.L1WithdrawalTransaction, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: l1withdrawaltransaction.Label}
	}
	return nil, &NotLoadedError{edge: "l1_withdrawal_transaction"}
}

// JusticeTxOrErr returns the JusticeTx value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e L1TokenOutputWithdrawalEdges) JusticeTxOrErr() (*L1TokenJusticeTransaction, error) {
	if e.JusticeTx != nil {
		return e.JusticeTx, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: l1tokenjusticetransaction.Label}
	}
	return nil, &NotLoadedError{edge: "justice_tx"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*L1TokenOutputWithdrawal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case l1tokenoutputwithdrawal.FieldBitcoinVout:
			values[i] = new(sql.NullInt64)
		case l1tokenoutputwithdrawal.FieldCreateTime, l1tokenoutputwithdrawal.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case l1tokenoutputwithdrawal.FieldID:
			values[i] = new(uuid.UUID)
		case l1tokenoutputwithdrawal.ForeignKeys[0]: // l1withdrawal_transaction_withdrawals
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case l1tokenoutputwithdrawal.ForeignKeys[1]: // token_output_withdrawal
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the L1TokenOutputWithdrawal fields.
func (low *L1TokenOutputWithdrawal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case l1tokenoutputwithdrawal.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				low.ID = *value
			}
		case l1tokenoutputwithdrawal.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				low.CreateTime = value.Time
			}
		case l1tokenoutputwithdrawal.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				low.UpdateTime = value.Time
			}
		case l1tokenoutputwithdrawal.FieldBitcoinVout:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bitcoin_vout", values[i])
			} else if value.Valid {
				low.BitcoinVout = uint16(value.Int64)
			}
		case l1tokenoutputwithdrawal.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field l1withdrawal_transaction_withdrawals", values[i])
			} else if value.Valid {
				low.l1withdrawal_transaction_withdrawals = new(uuid.UUID)
				*low.l1withdrawal_transaction_withdrawals = *value.S.(*uuid.UUID)
			}
		case l1tokenoutputwithdrawal.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field token_output_withdrawal", values[i])
			} else if value.Valid {
				low.token_output_withdrawal = new(uuid.UUID)
				*low.token_output_withdrawal = *value.S.(*uuid.UUID)
			}
		default:
			low.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the L1TokenOutputWithdrawal.
// This includes values selected through modifiers, order, etc.
func (low *L1TokenOutputWithdrawal) Value(name string) (ent.Value, error) {
	return low.selectValues.Get(name)
}

// QueryTokenOutput queries the "token_output" edge of the L1TokenOutputWithdrawal entity.
func (low *L1TokenOutputWithdrawal) QueryTokenOutput() *TokenOutputQuery {
	return NewL1TokenOutputWithdrawalClient(low.config).QueryTokenOutput(low)
}

// QueryL1WithdrawalTransaction queries the "l1_withdrawal_transaction" edge of the L1TokenOutputWithdrawal entity.
func (low *L1TokenOutputWithdrawal) QueryL1WithdrawalTransaction() *L1WithdrawalTransactionQuery {
	return NewL1TokenOutputWithdrawalClient(low.config).QueryL1WithdrawalTransaction(low)
}

// QueryJusticeTx queries the "justice_tx" edge of the L1TokenOutputWithdrawal entity.
func (low *L1TokenOutputWithdrawal) QueryJusticeTx() *L1TokenJusticeTransactionQuery {
	return NewL1TokenOutputWithdrawalClient(low.config).QueryJusticeTx(low)
}

// Update returns a builder for updating this L1TokenOutputWithdrawal.
// Note that you need to call L1TokenOutputWithdrawal.Unwrap() before calling this method if this L1TokenOutputWithdrawal
// was returned from a transaction, and the transaction was committed or rolled back.
func (low *L1TokenOutputWithdrawal) Update() *L1TokenOutputWithdrawalUpdateOne {
	return NewL1TokenOutputWithdrawalClient(low.config).UpdateOne(low)
}

// Unwrap unwraps the L1TokenOutputWithdrawal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (low *L1TokenOutputWithdrawal) Unwrap() *L1TokenOutputWithdrawal {
	_tx, ok := low.config.driver.(*txDriver)
	if !ok {
		panic("ent: L1TokenOutputWithdrawal is not a transactional entity")
	}
	low.config.driver = _tx.drv
	return low
}

// String implements the fmt.Stringer.
func (low *L1TokenOutputWithdrawal) String() string {
	var builder strings.Builder
	builder.WriteString("L1TokenOutputWithdrawal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", low.ID))
	builder.WriteString("create_time=")
	builder.WriteString(low.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(low.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("bitcoin_vout=")
	builder.WriteString(fmt.Sprintf("%v", low.BitcoinVout))
	builder.WriteByte(')')
	return builder.String()
}

// L1TokenOutputWithdrawals is a parsable slice of L1TokenOutputWithdrawal.
type L1TokenOutputWithdrawals []*L1TokenOutputWithdrawal
