// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/l1withdrawaltransaction"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenOutputWithdrawalUpdate is the builder for updating L1TokenOutputWithdrawal entities.
type L1TokenOutputWithdrawalUpdate struct {
	config
	hooks     []Hook
	mutation  *L1TokenOutputWithdrawalMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the L1TokenOutputWithdrawalUpdate builder.
func (lowu *L1TokenOutputWithdrawalUpdate) Where(ps ...predicate.L1TokenOutputWithdrawal) *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.Where(ps...)
	return lowu
}

// SetUpdateTime sets the "update_time" field.
func (lowu *L1TokenOutputWithdrawalUpdate) SetUpdateTime(t time.Time) *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.SetUpdateTime(t)
	return lowu
}

// SetTokenOutputID sets the "token_output" edge to the TokenOutput entity by ID.
func (lowu *L1TokenOutputWithdrawalUpdate) SetTokenOutputID(id uuid.UUID) *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.SetTokenOutputID(id)
	return lowu
}

// SetTokenOutput sets the "token_output" edge to the TokenOutput entity.
func (lowu *L1TokenOutputWithdrawalUpdate) SetTokenOutput(t *TokenOutput) *L1TokenOutputWithdrawalUpdate {
	return lowu.SetTokenOutputID(t.ID)
}

// SetL1WithdrawalTransactionID sets the "l1_withdrawal_transaction" edge to the L1WithdrawalTransaction entity by ID.
func (lowu *L1TokenOutputWithdrawalUpdate) SetL1WithdrawalTransactionID(id uuid.UUID) *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.SetL1WithdrawalTransactionID(id)
	return lowu
}

// SetL1WithdrawalTransaction sets the "l1_withdrawal_transaction" edge to the L1WithdrawalTransaction entity.
func (lowu *L1TokenOutputWithdrawalUpdate) SetL1WithdrawalTransaction(l *L1WithdrawalTransaction) *L1TokenOutputWithdrawalUpdate {
	return lowu.SetL1WithdrawalTransactionID(l.ID)
}

// SetJusticeTxID sets the "justice_tx" edge to the L1TokenJusticeTransaction entity by ID.
func (lowu *L1TokenOutputWithdrawalUpdate) SetJusticeTxID(id uuid.UUID) *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.SetJusticeTxID(id)
	return lowu
}

// SetNillableJusticeTxID sets the "justice_tx" edge to the L1TokenJusticeTransaction entity by ID if the given value is not nil.
func (lowu *L1TokenOutputWithdrawalUpdate) SetNillableJusticeTxID(id *uuid.UUID) *L1TokenOutputWithdrawalUpdate {
	if id != nil {
		lowu = lowu.SetJusticeTxID(*id)
	}
	return lowu
}

// SetJusticeTx sets the "justice_tx" edge to the L1TokenJusticeTransaction entity.
func (lowu *L1TokenOutputWithdrawalUpdate) SetJusticeTx(l *L1TokenJusticeTransaction) *L1TokenOutputWithdrawalUpdate {
	return lowu.SetJusticeTxID(l.ID)
}

// Mutation returns the L1TokenOutputWithdrawalMutation object of the builder.
func (lowu *L1TokenOutputWithdrawalUpdate) Mutation() *L1TokenOutputWithdrawalMutation {
	return lowu.mutation
}

// ClearTokenOutput clears the "token_output" edge to the TokenOutput entity.
func (lowu *L1TokenOutputWithdrawalUpdate) ClearTokenOutput() *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.ClearTokenOutput()
	return lowu
}

// ClearL1WithdrawalTransaction clears the "l1_withdrawal_transaction" edge to the L1WithdrawalTransaction entity.
func (lowu *L1TokenOutputWithdrawalUpdate) ClearL1WithdrawalTransaction() *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.ClearL1WithdrawalTransaction()
	return lowu
}

// ClearJusticeTx clears the "justice_tx" edge to the L1TokenJusticeTransaction entity.
func (lowu *L1TokenOutputWithdrawalUpdate) ClearJusticeTx() *L1TokenOutputWithdrawalUpdate {
	lowu.mutation.ClearJusticeTx()
	return lowu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lowu *L1TokenOutputWithdrawalUpdate) Save(ctx context.Context) (int, error) {
	lowu.defaults()
	return withHooks(ctx, lowu.sqlSave, lowu.mutation, lowu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lowu *L1TokenOutputWithdrawalUpdate) SaveX(ctx context.Context) int {
	affected, err := lowu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lowu *L1TokenOutputWithdrawalUpdate) Exec(ctx context.Context) error {
	_, err := lowu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lowu *L1TokenOutputWithdrawalUpdate) ExecX(ctx context.Context) {
	if err := lowu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lowu *L1TokenOutputWithdrawalUpdate) defaults() {
	if _, ok := lowu.mutation.UpdateTime(); !ok {
		v := l1tokenoutputwithdrawal.UpdateDefaultUpdateTime()
		lowu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lowu *L1TokenOutputWithdrawalUpdate) check() error {
	if lowu.mutation.TokenOutputCleared() && len(lowu.mutation.TokenOutputIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenOutputWithdrawal.token_output"`)
	}
	if lowu.mutation.L1WithdrawalTransactionCleared() && len(lowu.mutation.L1WithdrawalTransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenOutputWithdrawal.l1_withdrawal_transaction"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lowu *L1TokenOutputWithdrawalUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *L1TokenOutputWithdrawalUpdate {
	lowu.modifiers = append(lowu.modifiers, modifiers...)
	return lowu
}

func (lowu *L1TokenOutputWithdrawalUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lowu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.Columns, sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID))
	if ps := lowu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lowu.mutation.UpdateTime(); ok {
		_spec.SetField(l1tokenoutputwithdrawal.FieldUpdateTime, field.TypeTime, value)
	}
	if lowu.mutation.TokenOutputCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.TokenOutputTable,
			Columns: []string{l1tokenoutputwithdrawal.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lowu.mutation.TokenOutputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.TokenOutputTable,
			Columns: []string{l1tokenoutputwithdrawal.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lowu.mutation.L1WithdrawalTransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.L1WithdrawalTransactionTable,
			Columns: []string{l1tokenoutputwithdrawal.L1WithdrawalTransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1withdrawaltransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lowu.mutation.L1WithdrawalTransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.L1WithdrawalTransactionTable,
			Columns: []string{l1tokenoutputwithdrawal.L1WithdrawalTransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1withdrawaltransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lowu.mutation.JusticeTxCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   l1tokenoutputwithdrawal.JusticeTxTable,
			Columns: []string{l1tokenoutputwithdrawal.JusticeTxColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lowu.mutation.JusticeTxIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   l1tokenoutputwithdrawal.JusticeTxTable,
			Columns: []string{l1tokenoutputwithdrawal.JusticeTxColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(lowu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, lowu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{l1tokenoutputwithdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lowu.mutation.done = true
	return n, nil
}

// L1TokenOutputWithdrawalUpdateOne is the builder for updating a single L1TokenOutputWithdrawal entity.
type L1TokenOutputWithdrawalUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *L1TokenOutputWithdrawalMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetUpdateTime(t time.Time) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.SetUpdateTime(t)
	return lowuo
}

// SetTokenOutputID sets the "token_output" edge to the TokenOutput entity by ID.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetTokenOutputID(id uuid.UUID) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.SetTokenOutputID(id)
	return lowuo
}

// SetTokenOutput sets the "token_output" edge to the TokenOutput entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetTokenOutput(t *TokenOutput) *L1TokenOutputWithdrawalUpdateOne {
	return lowuo.SetTokenOutputID(t.ID)
}

// SetL1WithdrawalTransactionID sets the "l1_withdrawal_transaction" edge to the L1WithdrawalTransaction entity by ID.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetL1WithdrawalTransactionID(id uuid.UUID) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.SetL1WithdrawalTransactionID(id)
	return lowuo
}

// SetL1WithdrawalTransaction sets the "l1_withdrawal_transaction" edge to the L1WithdrawalTransaction entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetL1WithdrawalTransaction(l *L1WithdrawalTransaction) *L1TokenOutputWithdrawalUpdateOne {
	return lowuo.SetL1WithdrawalTransactionID(l.ID)
}

// SetJusticeTxID sets the "justice_tx" edge to the L1TokenJusticeTransaction entity by ID.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetJusticeTxID(id uuid.UUID) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.SetJusticeTxID(id)
	return lowuo
}

// SetNillableJusticeTxID sets the "justice_tx" edge to the L1TokenJusticeTransaction entity by ID if the given value is not nil.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetNillableJusticeTxID(id *uuid.UUID) *L1TokenOutputWithdrawalUpdateOne {
	if id != nil {
		lowuo = lowuo.SetJusticeTxID(*id)
	}
	return lowuo
}

// SetJusticeTx sets the "justice_tx" edge to the L1TokenJusticeTransaction entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SetJusticeTx(l *L1TokenJusticeTransaction) *L1TokenOutputWithdrawalUpdateOne {
	return lowuo.SetJusticeTxID(l.ID)
}

// Mutation returns the L1TokenOutputWithdrawalMutation object of the builder.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) Mutation() *L1TokenOutputWithdrawalMutation {
	return lowuo.mutation
}

// ClearTokenOutput clears the "token_output" edge to the TokenOutput entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) ClearTokenOutput() *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.ClearTokenOutput()
	return lowuo
}

// ClearL1WithdrawalTransaction clears the "l1_withdrawal_transaction" edge to the L1WithdrawalTransaction entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) ClearL1WithdrawalTransaction() *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.ClearL1WithdrawalTransaction()
	return lowuo
}

// ClearJusticeTx clears the "justice_tx" edge to the L1TokenJusticeTransaction entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) ClearJusticeTx() *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.ClearJusticeTx()
	return lowuo
}

// Where appends a list predicates to the L1TokenOutputWithdrawalUpdate builder.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) Where(ps ...predicate.L1TokenOutputWithdrawal) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.mutation.Where(ps...)
	return lowuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) Select(field string, fields ...string) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.fields = append([]string{field}, fields...)
	return lowuo
}

// Save executes the query and returns the updated L1TokenOutputWithdrawal entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) Save(ctx context.Context) (*L1TokenOutputWithdrawal, error) {
	lowuo.defaults()
	return withHooks(ctx, lowuo.sqlSave, lowuo.mutation, lowuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) SaveX(ctx context.Context) *L1TokenOutputWithdrawal {
	node, err := lowuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) Exec(ctx context.Context) error {
	_, err := lowuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) ExecX(ctx context.Context) {
	if err := lowuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) defaults() {
	if _, ok := lowuo.mutation.UpdateTime(); !ok {
		v := l1tokenoutputwithdrawal.UpdateDefaultUpdateTime()
		lowuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) check() error {
	if lowuo.mutation.TokenOutputCleared() && len(lowuo.mutation.TokenOutputIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenOutputWithdrawal.token_output"`)
	}
	if lowuo.mutation.L1WithdrawalTransactionCleared() && len(lowuo.mutation.L1WithdrawalTransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "L1TokenOutputWithdrawal.l1_withdrawal_transaction"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lowuo *L1TokenOutputWithdrawalUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *L1TokenOutputWithdrawalUpdateOne {
	lowuo.modifiers = append(lowuo.modifiers, modifiers...)
	return lowuo
}

func (lowuo *L1TokenOutputWithdrawalUpdateOne) sqlSave(ctx context.Context) (_node *L1TokenOutputWithdrawal, err error) {
	if err := lowuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(l1tokenoutputwithdrawal.Table, l1tokenoutputwithdrawal.Columns, sqlgraph.NewFieldSpec(l1tokenoutputwithdrawal.FieldID, field.TypeUUID))
	id, ok := lowuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "L1TokenOutputWithdrawal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lowuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, l1tokenoutputwithdrawal.FieldID)
		for _, f := range fields {
			if !l1tokenoutputwithdrawal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != l1tokenoutputwithdrawal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lowuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lowuo.mutation.UpdateTime(); ok {
		_spec.SetField(l1tokenoutputwithdrawal.FieldUpdateTime, field.TypeTime, value)
	}
	if lowuo.mutation.TokenOutputCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.TokenOutputTable,
			Columns: []string{l1tokenoutputwithdrawal.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lowuo.mutation.TokenOutputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.TokenOutputTable,
			Columns: []string{l1tokenoutputwithdrawal.TokenOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokenoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lowuo.mutation.L1WithdrawalTransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.L1WithdrawalTransactionTable,
			Columns: []string{l1tokenoutputwithdrawal.L1WithdrawalTransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1withdrawaltransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lowuo.mutation.L1WithdrawalTransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   l1tokenoutputwithdrawal.L1WithdrawalTransactionTable,
			Columns: []string{l1tokenoutputwithdrawal.L1WithdrawalTransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1withdrawaltransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lowuo.mutation.JusticeTxCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   l1tokenoutputwithdrawal.JusticeTxTable,
			Columns: []string{l1tokenoutputwithdrawal.JusticeTxColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lowuo.mutation.JusticeTxIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   l1tokenoutputwithdrawal.JusticeTxTable,
			Columns: []string{l1tokenoutputwithdrawal.JusticeTxColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(lowuo.modifiers...)
	_node = &L1TokenOutputWithdrawal{config: lowuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lowuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{l1tokenoutputwithdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	lowuo.mutation.done = true
	return _node, nil
}
