// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/l1tokenoutputwithdrawal"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
)

// L1TokenJusticeTransaction is the model entity for the L1TokenJusticeTransaction schema.
type L1TokenJusticeTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Transaction ID of the justice transaction.
	JusticeTxHash schematype.TxID `json:"justice_tx_hash,omitempty"`
	// The time when the justice transaction was broadcast to the network.
	BroadcastAt time.Time `json:"broadcast_at,omitempty"`
	// Amount in satoshis claimed by the justice transaction.
	AmountSats uint64 `json:"amount_sats,omitempty"`
	// Transaction fee paid in satoshis for broadcasting the justice transaction.
	TxCostSats uint64 `json:"tx_cost_sats,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the L1TokenJusticeTransactionQuery when eager-loading is set.
	Edges                                L1TokenJusticeTransactionEdges `json:"edges"`
	l1token_output_withdrawal_justice_tx *uuid.UUID
	token_output_justice_tx              *uuid.UUID
	selectValues                         sql.SelectValues
}

// L1TokenJusticeTransactionEdges holds the relations/edges for other nodes in the graph.
type L1TokenJusticeTransactionEdges struct {
	// The token output that was invalidly withdrawn (the spent output being double-spent).
	TokenOutput *TokenOutput `json:"token_output,omitempty"`
	// The invalid withdrawal that triggered this justice transaction.
	L1TokenOutputWithdrawal *L1TokenOutputWithdrawal `json:"l1_token_output_withdrawal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TokenOutputOrErr returns the TokenOutput value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e L1TokenJusticeTransactionEdges) TokenOutputOrErr() (*TokenOutput, error) {
	if e.TokenOutput != nil {
		return e.TokenOutput, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tokenoutput.Label}
	}
	return nil, &NotLoadedError{edge: "token_output"}
}

// L1TokenOutputWithdrawalOrErr returns the L1TokenOutputWithdrawal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e L1TokenJusticeTransactionEdges) L1TokenOutputWithdrawalOrErr() (*L1TokenOutputWithdrawal, error) {
	if e.L1TokenOutputWithdrawal != nil {
		return e.L1TokenOutputWithdrawal, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: l1tokenoutputwithdrawal.Label}
	}
	return nil, &NotLoadedError{edge: "l1_token_output_withdrawal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*L1TokenJusticeTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case l1tokenjusticetransaction.FieldJusticeTxHash:
			values[i] = new(schematype.TxID)
		case l1tokenjusticetransaction.FieldAmountSats, l1tokenjusticetransaction.FieldTxCostSats:
			values[i] = new(sql.NullInt64)
		case l1tokenjusticetransaction.FieldCreateTime, l1tokenjusticetransaction.FieldUpdateTime, l1tokenjusticetransaction.FieldBroadcastAt:
			values[i] = new(sql.NullTime)
		case l1tokenjusticetransaction.FieldID:
			values[i] = new(uuid.UUID)
		case l1tokenjusticetransaction.ForeignKeys[0]: // l1token_output_withdrawal_justice_tx
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case l1tokenjusticetransaction.ForeignKeys[1]: // token_output_justice_tx
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the L1TokenJusticeTransaction fields.
func (ljt *L1TokenJusticeTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case l1tokenjusticetransaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ljt.ID = *value
			}
		case l1tokenjusticetransaction.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ljt.CreateTime = value.Time
			}
		case l1tokenjusticetransaction.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ljt.UpdateTime = value.Time
			}
		case l1tokenjusticetransaction.FieldJusticeTxHash:
			if value, ok := values[i].(*schematype.TxID); !ok {
				return fmt.Errorf("unexpected type %T for field justice_tx_hash", values[i])
			} else if value != nil {
				ljt.JusticeTxHash = *value
			}
		case l1tokenjusticetransaction.FieldBroadcastAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field broadcast_at", values[i])
			} else if value.Valid {
				ljt.BroadcastAt = value.Time
			}
		case l1tokenjusticetransaction.FieldAmountSats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_sats", values[i])
			} else if value.Valid {
				ljt.AmountSats = uint64(value.Int64)
			}
		case l1tokenjusticetransaction.FieldTxCostSats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tx_cost_sats", values[i])
			} else if value.Valid {
				ljt.TxCostSats = uint64(value.Int64)
			}
		case l1tokenjusticetransaction.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field l1token_output_withdrawal_justice_tx", values[i])
			} else if value.Valid {
				ljt.l1token_output_withdrawal_justice_tx = new(uuid.UUID)
				*ljt.l1token_output_withdrawal_justice_tx = *value.S.(*uuid.UUID)
			}
		case l1tokenjusticetransaction.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field token_output_justice_tx", values[i])
			} else if value.Valid {
				ljt.token_output_justice_tx = new(uuid.UUID)
				*ljt.token_output_justice_tx = *value.S.(*uuid.UUID)
			}
		default:
			ljt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the L1TokenJusticeTransaction.
// This includes values selected through modifiers, order, etc.
func (ljt *L1TokenJusticeTransaction) Value(name string) (ent.Value, error) {
	return ljt.selectValues.Get(name)
}

// QueryTokenOutput queries the "token_output" edge of the L1TokenJusticeTransaction entity.
func (ljt *L1TokenJusticeTransaction) QueryTokenOutput() *TokenOutputQuery {
	return NewL1TokenJusticeTransactionClient(ljt.config).QueryTokenOutput(ljt)
}

// QueryL1TokenOutputWithdrawal queries the "l1_token_output_withdrawal" edge of the L1TokenJusticeTransaction entity.
func (ljt *L1TokenJusticeTransaction) QueryL1TokenOutputWithdrawal() *L1TokenOutputWithdrawalQuery {
	return NewL1TokenJusticeTransactionClient(ljt.config).QueryL1TokenOutputWithdrawal(ljt)
}

// Update returns a builder for updating this L1TokenJusticeTransaction.
// Note that you need to call L1TokenJusticeTransaction.Unwrap() before calling this method if this L1TokenJusticeTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (ljt *L1TokenJusticeTransaction) Update() *L1TokenJusticeTransactionUpdateOne {
	return NewL1TokenJusticeTransactionClient(ljt.config).UpdateOne(ljt)
}

// Unwrap unwraps the L1TokenJusticeTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ljt *L1TokenJusticeTransaction) Unwrap() *L1TokenJusticeTransaction {
	_tx, ok := ljt.config.driver.(*txDriver)
	if !ok {
		panic("ent: L1TokenJusticeTransaction is not a transactional entity")
	}
	ljt.config.driver = _tx.drv
	return ljt
}

// String implements the fmt.Stringer.
func (ljt *L1TokenJusticeTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("L1TokenJusticeTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ljt.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ljt.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ljt.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("justice_tx_hash=")
	builder.WriteString(fmt.Sprintf("%v", ljt.JusticeTxHash))
	builder.WriteString(", ")
	builder.WriteString("broadcast_at=")
	builder.WriteString(ljt.BroadcastAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("amount_sats=")
	builder.WriteString(fmt.Sprintf("%v", ljt.AmountSats))
	builder.WriteString(", ")
	builder.WriteString("tx_cost_sats=")
	builder.WriteString(fmt.Sprintf("%v", ljt.TxCostSats))
	builder.WriteByte(')')
	return builder.String()
}

// L1TokenJusticeTransactions is a parsable slice of L1TokenJusticeTransaction.
type L1TokenJusticeTransactions []*L1TokenJusticeTransaction
