// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/l1tokenjusticetransaction"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// L1TokenJusticeTransactionDelete is the builder for deleting a L1TokenJusticeTransaction entity.
type L1TokenJusticeTransactionDelete struct {
	config
	hooks    []Hook
	mutation *L1TokenJusticeTransactionMutation
}

// Where appends a list predicates to the L1TokenJusticeTransactionDelete builder.
func (ljtd *L1TokenJusticeTransactionDelete) Where(ps ...predicate.L1TokenJusticeTransaction) *L1TokenJusticeTransactionDelete {
	ljtd.mutation.Where(ps...)
	return ljtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ljtd *L1TokenJusticeTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ljtd.sqlExec, ljtd.mutation, ljtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ljtd *L1TokenJusticeTransactionDelete) ExecX(ctx context.Context) int {
	n, err := ljtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ljtd *L1TokenJusticeTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(l1tokenjusticetransaction.Table, sqlgraph.NewFieldSpec(l1tokenjusticetransaction.FieldID, field.TypeUUID))
	if ps := ljtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ljtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ljtd.mutation.done = true
	return affected, err
}

// L1TokenJusticeTransactionDeleteOne is the builder for deleting a single L1TokenJusticeTransaction entity.
type L1TokenJusticeTransactionDeleteOne struct {
	ljtd *L1TokenJusticeTransactionDelete
}

// Where appends a list predicates to the L1TokenJusticeTransactionDelete builder.
func (ljtdo *L1TokenJusticeTransactionDeleteOne) Where(ps ...predicate.L1TokenJusticeTransaction) *L1TokenJusticeTransactionDeleteOne {
	ljtdo.ljtd.mutation.Where(ps...)
	return ljtdo
}

// Exec executes the deletion query.
func (ljtdo *L1TokenJusticeTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := ljtdo.ljtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{l1tokenjusticetransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ljtdo *L1TokenJusticeTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := ljtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
