// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/l1withdrawaltransaction"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// L1WithdrawalTransactionDelete is the builder for deleting a L1WithdrawalTransaction entity.
type L1WithdrawalTransactionDelete struct {
	config
	hooks    []Hook
	mutation *L1WithdrawalTransactionMutation
}

// Where appends a list predicates to the L1WithdrawalTransactionDelete builder.
func (ltd *L1WithdrawalTransactionDelete) Where(ps ...predicate.L1WithdrawalTransaction) *L1WithdrawalTransactionDelete {
	ltd.mutation.Where(ps...)
	return ltd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ltd *L1WithdrawalTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ltd.sqlExec, ltd.mutation, ltd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ltd *L1WithdrawalTransactionDelete) ExecX(ctx context.Context) int {
	n, err := ltd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ltd *L1WithdrawalTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(l1withdrawaltransaction.Table, sqlgraph.NewFieldSpec(l1withdrawaltransaction.FieldID, field.TypeUUID))
	if ps := ltd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ltd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ltd.mutation.done = true
	return affected, err
}

// L1WithdrawalTransactionDeleteOne is the builder for deleting a single L1WithdrawalTransaction entity.
type L1WithdrawalTransactionDeleteOne struct {
	ltd *L1WithdrawalTransactionDelete
}

// Where appends a list predicates to the L1WithdrawalTransactionDelete builder.
func (ltdo *L1WithdrawalTransactionDeleteOne) Where(ps ...predicate.L1WithdrawalTransaction) *L1WithdrawalTransactionDeleteOne {
	ltdo.ltd.mutation.Where(ps...)
	return ltdo
}

// Exec executes the deletion query.
func (ltdo *L1WithdrawalTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := ltdo.ltd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{l1withdrawaltransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ltdo *L1WithdrawalTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := ltdo.Exec(ctx); err != nil {
		panic(err)
	}
}
