// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/transfer"
	"github.com/lightsparkdev/spark/so/ent/transferreceiver"
)

// TransferReceiverQuery is the builder for querying TransferReceiver entities.
type TransferReceiverQuery struct {
	config
	ctx          *QueryContext
	order        []transferreceiver.OrderOption
	inters       []Interceptor
	predicates   []predicate.TransferReceiver
	withTransfer *TransferQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransferReceiverQuery builder.
func (trq *TransferReceiverQuery) Where(ps ...predicate.TransferReceiver) *TransferReceiverQuery {
	trq.predicates = append(trq.predicates, ps...)
	return trq
}

// Limit the number of records to be returned by this query.
func (trq *TransferReceiverQuery) Limit(limit int) *TransferReceiverQuery {
	trq.ctx.Limit = &limit
	return trq
}

// Offset to start from.
func (trq *TransferReceiverQuery) Offset(offset int) *TransferReceiverQuery {
	trq.ctx.Offset = &offset
	return trq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (trq *TransferReceiverQuery) Unique(unique bool) *TransferReceiverQuery {
	trq.ctx.Unique = &unique
	return trq
}

// Order specifies how the records should be ordered.
func (trq *TransferReceiverQuery) Order(o ...transferreceiver.OrderOption) *TransferReceiverQuery {
	trq.order = append(trq.order, o...)
	return trq
}

// QueryTransfer chains the current query on the "transfer" edge.
func (trq *TransferReceiverQuery) QueryTransfer() *TransferQuery {
	query := (&TransferClient{config: trq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := trq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := trq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transferreceiver.Table, transferreceiver.FieldID, selector),
			sqlgraph.To(transfer.Table, transfer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, transferreceiver.TransferTable, transferreceiver.TransferColumn),
		)
		fromU = sqlgraph.SetNeighbors(trq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TransferReceiver entity from the query.
// Returns a *NotFoundError when no TransferReceiver was found.
func (trq *TransferReceiverQuery) First(ctx context.Context) (*TransferReceiver, error) {
	nodes, err := trq.Limit(1).All(setContextOp(ctx, trq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transferreceiver.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (trq *TransferReceiverQuery) FirstX(ctx context.Context) *TransferReceiver {
	node, err := trq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TransferReceiver ID from the query.
// Returns a *NotFoundError when no TransferReceiver ID was found.
func (trq *TransferReceiverQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = trq.Limit(1).IDs(setContextOp(ctx, trq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transferreceiver.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (trq *TransferReceiverQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := trq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TransferReceiver entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TransferReceiver entity is found.
// Returns a *NotFoundError when no TransferReceiver entities are found.
func (trq *TransferReceiverQuery) Only(ctx context.Context) (*TransferReceiver, error) {
	nodes, err := trq.Limit(2).All(setContextOp(ctx, trq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transferreceiver.Label}
	default:
		return nil, &NotSingularError{transferreceiver.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (trq *TransferReceiverQuery) OnlyX(ctx context.Context) *TransferReceiver {
	node, err := trq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TransferReceiver ID in the query.
// Returns a *NotSingularError when more than one TransferReceiver ID is found.
// Returns a *NotFoundError when no entities are found.
func (trq *TransferReceiverQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = trq.Limit(2).IDs(setContextOp(ctx, trq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transferreceiver.Label}
	default:
		err = &NotSingularError{transferreceiver.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (trq *TransferReceiverQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := trq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TransferReceivers.
func (trq *TransferReceiverQuery) All(ctx context.Context) ([]*TransferReceiver, error) {
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryAll)
	if err := trq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TransferReceiver, *TransferReceiverQuery]()
	return withInterceptors[[]*TransferReceiver](ctx, trq, qr, trq.inters)
}

// AllX is like All, but panics if an error occurs.
func (trq *TransferReceiverQuery) AllX(ctx context.Context) []*TransferReceiver {
	nodes, err := trq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TransferReceiver IDs.
func (trq *TransferReceiverQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if trq.ctx.Unique == nil && trq.path != nil {
		trq.Unique(true)
	}
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryIDs)
	if err = trq.Select(transferreceiver.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (trq *TransferReceiverQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := trq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (trq *TransferReceiverQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryCount)
	if err := trq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, trq, querierCount[*TransferReceiverQuery](), trq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (trq *TransferReceiverQuery) CountX(ctx context.Context) int {
	count, err := trq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (trq *TransferReceiverQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, trq.ctx, ent.OpQueryExist)
	switch _, err := trq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (trq *TransferReceiverQuery) ExistX(ctx context.Context) bool {
	exist, err := trq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransferReceiverQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (trq *TransferReceiverQuery) Clone() *TransferReceiverQuery {
	if trq == nil {
		return nil
	}
	return &TransferReceiverQuery{
		config:       trq.config,
		ctx:          trq.ctx.Clone(),
		order:        append([]transferreceiver.OrderOption{}, trq.order...),
		inters:       append([]Interceptor{}, trq.inters...),
		predicates:   append([]predicate.TransferReceiver{}, trq.predicates...),
		withTransfer: trq.withTransfer.Clone(),
		// clone intermediate query.
		sql:       trq.sql.Clone(),
		path:      trq.path,
		modifiers: append([]func(*sql.Selector){}, trq.modifiers...),
	}
}

// WithTransfer tells the query-builder to eager-load the nodes that are connected to
// the "transfer" edge. The optional arguments are used to configure the query builder of the edge.
func (trq *TransferReceiverQuery) WithTransfer(opts ...func(*TransferQuery)) *TransferReceiverQuery {
	query := (&TransferClient{config: trq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	trq.withTransfer = query
	return trq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TransferReceiver.Query().
//		GroupBy(transferreceiver.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (trq *TransferReceiverQuery) GroupBy(field string, fields ...string) *TransferReceiverGroupBy {
	trq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransferReceiverGroupBy{build: trq}
	grbuild.flds = &trq.ctx.Fields
	grbuild.label = transferreceiver.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TransferReceiver.Query().
//		Select(transferreceiver.FieldCreateTime).
//		Scan(ctx, &v)
func (trq *TransferReceiverQuery) Select(fields ...string) *TransferReceiverSelect {
	trq.ctx.Fields = append(trq.ctx.Fields, fields...)
	sbuild := &TransferReceiverSelect{TransferReceiverQuery: trq}
	sbuild.label = transferreceiver.Label
	sbuild.flds, sbuild.scan = &trq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransferReceiverSelect configured with the given aggregations.
func (trq *TransferReceiverQuery) Aggregate(fns ...AggregateFunc) *TransferReceiverSelect {
	return trq.Select().Aggregate(fns...)
}

func (trq *TransferReceiverQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range trq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, trq); err != nil {
				return err
			}
		}
	}
	for _, f := range trq.ctx.Fields {
		if !transferreceiver.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if trq.path != nil {
		prev, err := trq.path(ctx)
		if err != nil {
			return err
		}
		trq.sql = prev
	}
	return nil
}

func (trq *TransferReceiverQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TransferReceiver, error) {
	var (
		nodes       = []*TransferReceiver{}
		_spec       = trq.querySpec()
		loadedTypes = [1]bool{
			trq.withTransfer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TransferReceiver).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TransferReceiver{config: trq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(trq.modifiers) > 0 {
		_spec.Modifiers = trq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, trq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := trq.withTransfer; query != nil {
		if err := trq.loadTransfer(ctx, query, nodes, nil,
			func(n *TransferReceiver, e *Transfer) { n.Edges.Transfer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (trq *TransferReceiverQuery) loadTransfer(ctx context.Context, query *TransferQuery, nodes []*TransferReceiver, init func(*TransferReceiver), assign func(*TransferReceiver, *Transfer)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TransferReceiver)
	for i := range nodes {
		fk := nodes[i].TransferID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(transfer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "transfer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (trq *TransferReceiverQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := trq.querySpec()
	if len(trq.modifiers) > 0 {
		_spec.Modifiers = trq.modifiers
	}
	_spec.Node.Columns = trq.ctx.Fields
	if len(trq.ctx.Fields) > 0 {
		_spec.Unique = trq.ctx.Unique != nil && *trq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, trq.driver, _spec)
}

func (trq *TransferReceiverQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transferreceiver.Table, transferreceiver.Columns, sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID))
	_spec.From = trq.sql
	if unique := trq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if trq.path != nil {
		_spec.Unique = true
	}
	if fields := trq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transferreceiver.FieldID)
		for i := range fields {
			if fields[i] != transferreceiver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if trq.withTransfer != nil {
			_spec.Node.AddColumnOnce(transferreceiver.FieldTransferID)
		}
	}
	if ps := trq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := trq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := trq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := trq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (trq *TransferReceiverQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(trq.driver.Dialect())
	t1 := builder.Table(transferreceiver.Table)
	columns := trq.ctx.Fields
	if len(columns) == 0 {
		columns = transferreceiver.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if trq.sql != nil {
		selector = trq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if trq.ctx.Unique != nil && *trq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range trq.modifiers {
		m(selector)
	}
	for _, p := range trq.predicates {
		p(selector)
	}
	for _, p := range trq.order {
		p(selector)
	}
	if offset := trq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := trq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (trq *TransferReceiverQuery) ForUpdate(opts ...sql.LockOption) *TransferReceiverQuery {
	if trq.driver.Dialect() == dialect.Postgres {
		trq.Unique(false)
	}
	trq.modifiers = append(trq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return trq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (trq *TransferReceiverQuery) ForShare(opts ...sql.LockOption) *TransferReceiverQuery {
	if trq.driver.Dialect() == dialect.Postgres {
		trq.Unique(false)
	}
	trq.modifiers = append(trq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return trq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (trq *TransferReceiverQuery) Modify(modifiers ...func(s *sql.Selector)) *TransferReceiverSelect {
	trq.modifiers = append(trq.modifiers, modifiers...)
	return trq.Select()
}

// TransferReceiverGroupBy is the group-by builder for TransferReceiver entities.
type TransferReceiverGroupBy struct {
	selector
	build *TransferReceiverQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (trgb *TransferReceiverGroupBy) Aggregate(fns ...AggregateFunc) *TransferReceiverGroupBy {
	trgb.fns = append(trgb.fns, fns...)
	return trgb
}

// Scan applies the selector query and scans the result into the given value.
func (trgb *TransferReceiverGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, trgb.build.ctx, ent.OpQueryGroupBy)
	if err := trgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferReceiverQuery, *TransferReceiverGroupBy](ctx, trgb.build, trgb, trgb.build.inters, v)
}

func (trgb *TransferReceiverGroupBy) sqlScan(ctx context.Context, root *TransferReceiverQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(trgb.fns))
	for _, fn := range trgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*trgb.flds)+len(trgb.fns))
		for _, f := range *trgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*trgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransferReceiverSelect is the builder for selecting fields of TransferReceiver entities.
type TransferReceiverSelect struct {
	*TransferReceiverQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (trs *TransferReceiverSelect) Aggregate(fns ...AggregateFunc) *TransferReceiverSelect {
	trs.fns = append(trs.fns, fns...)
	return trs
}

// Scan applies the selector query and scans the result into the given value.
func (trs *TransferReceiverSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, trs.ctx, ent.OpQuerySelect)
	if err := trs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferReceiverQuery, *TransferReceiverSelect](ctx, trs.TransferReceiverQuery, trs, trs.inters, v)
}

func (trs *TransferReceiverSelect) sqlScan(ctx context.Context, root *TransferReceiverQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(trs.fns))
	for _, fn := range trs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*trs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := trs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (trs *TransferReceiverSelect) Modify(modifiers ...func(s *sql.Selector)) *TransferReceiverSelect {
	trs.modifiers = append(trs.modifiers, modifiers...)
	return trs
}
