// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/transferleaf"
	"github.com/lightsparkdev/spark/so/ent/transferreceiver"
	"github.com/lightsparkdev/spark/so/ent/transfersender"
)

// TransferLeafUpdate is the builder for updating TransferLeaf entities.
type TransferLeafUpdate struct {
	config
	hooks     []Hook
	mutation  *TransferLeafMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TransferLeafUpdate builder.
func (tlu *TransferLeafUpdate) Where(ps ...predicate.TransferLeaf) *TransferLeafUpdate {
	tlu.mutation.Where(ps...)
	return tlu
}

// SetUpdateTime sets the "update_time" field.
func (tlu *TransferLeafUpdate) SetUpdateTime(t time.Time) *TransferLeafUpdate {
	tlu.mutation.SetUpdateTime(t)
	return tlu
}

// SetSecretCipher sets the "secret_cipher" field.
func (tlu *TransferLeafUpdate) SetSecretCipher(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetSecretCipher(b)
	return tlu
}

// ClearSecretCipher clears the value of the "secret_cipher" field.
func (tlu *TransferLeafUpdate) ClearSecretCipher() *TransferLeafUpdate {
	tlu.mutation.ClearSecretCipher()
	return tlu
}

// SetSignature sets the "signature" field.
func (tlu *TransferLeafUpdate) SetSignature(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetSignature(b)
	return tlu
}

// ClearSignature clears the value of the "signature" field.
func (tlu *TransferLeafUpdate) ClearSignature() *TransferLeafUpdate {
	tlu.mutation.ClearSignature()
	return tlu
}

// SetIntermediateRefundTx sets the "intermediate_refund_tx" field.
func (tlu *TransferLeafUpdate) SetIntermediateRefundTx(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetIntermediateRefundTx(b)
	return tlu
}

// SetIntermediateDirectRefundTx sets the "intermediate_direct_refund_tx" field.
func (tlu *TransferLeafUpdate) SetIntermediateDirectRefundTx(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetIntermediateDirectRefundTx(b)
	return tlu
}

// ClearIntermediateDirectRefundTx clears the value of the "intermediate_direct_refund_tx" field.
func (tlu *TransferLeafUpdate) ClearIntermediateDirectRefundTx() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateDirectRefundTx()
	return tlu
}

// SetIntermediateDirectFromCpfpRefundTx sets the "intermediate_direct_from_cpfp_refund_tx" field.
func (tlu *TransferLeafUpdate) SetIntermediateDirectFromCpfpRefundTx(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetIntermediateDirectFromCpfpRefundTx(b)
	return tlu
}

// ClearIntermediateDirectFromCpfpRefundTx clears the value of the "intermediate_direct_from_cpfp_refund_tx" field.
func (tlu *TransferLeafUpdate) ClearIntermediateDirectFromCpfpRefundTx() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateDirectFromCpfpRefundTx()
	return tlu
}

// SetIntermediateRefundTxid sets the "intermediate_refund_txid" field.
func (tlu *TransferLeafUpdate) SetIntermediateRefundTxid(si schematype.TxID) *TransferLeafUpdate {
	tlu.mutation.SetIntermediateRefundTxid(si)
	return tlu
}

// SetNillableIntermediateRefundTxid sets the "intermediate_refund_txid" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableIntermediateRefundTxid(si *schematype.TxID) *TransferLeafUpdate {
	if si != nil {
		tlu.SetIntermediateRefundTxid(*si)
	}
	return tlu
}

// ClearIntermediateRefundTxid clears the value of the "intermediate_refund_txid" field.
func (tlu *TransferLeafUpdate) ClearIntermediateRefundTxid() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateRefundTxid()
	return tlu
}

// SetIntermediateDirectRefundTxid sets the "intermediate_direct_refund_txid" field.
func (tlu *TransferLeafUpdate) SetIntermediateDirectRefundTxid(si schematype.TxID) *TransferLeafUpdate {
	tlu.mutation.SetIntermediateDirectRefundTxid(si)
	return tlu
}

// SetNillableIntermediateDirectRefundTxid sets the "intermediate_direct_refund_txid" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableIntermediateDirectRefundTxid(si *schematype.TxID) *TransferLeafUpdate {
	if si != nil {
		tlu.SetIntermediateDirectRefundTxid(*si)
	}
	return tlu
}

// ClearIntermediateDirectRefundTxid clears the value of the "intermediate_direct_refund_txid" field.
func (tlu *TransferLeafUpdate) ClearIntermediateDirectRefundTxid() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateDirectRefundTxid()
	return tlu
}

// SetIntermediateDirectFromCpfpRefundTxid sets the "intermediate_direct_from_cpfp_refund_txid" field.
func (tlu *TransferLeafUpdate) SetIntermediateDirectFromCpfpRefundTxid(si schematype.TxID) *TransferLeafUpdate {
	tlu.mutation.SetIntermediateDirectFromCpfpRefundTxid(si)
	return tlu
}

// SetNillableIntermediateDirectFromCpfpRefundTxid sets the "intermediate_direct_from_cpfp_refund_txid" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableIntermediateDirectFromCpfpRefundTxid(si *schematype.TxID) *TransferLeafUpdate {
	if si != nil {
		tlu.SetIntermediateDirectFromCpfpRefundTxid(*si)
	}
	return tlu
}

// ClearIntermediateDirectFromCpfpRefundTxid clears the value of the "intermediate_direct_from_cpfp_refund_txid" field.
func (tlu *TransferLeafUpdate) ClearIntermediateDirectFromCpfpRefundTxid() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateDirectFromCpfpRefundTxid()
	return tlu
}

// SetIntermediateRefundTimelock sets the "intermediate_refund_timelock" field.
func (tlu *TransferLeafUpdate) SetIntermediateRefundTimelock(u uint64) *TransferLeafUpdate {
	tlu.mutation.ResetIntermediateRefundTimelock()
	tlu.mutation.SetIntermediateRefundTimelock(u)
	return tlu
}

// SetNillableIntermediateRefundTimelock sets the "intermediate_refund_timelock" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableIntermediateRefundTimelock(u *uint64) *TransferLeafUpdate {
	if u != nil {
		tlu.SetIntermediateRefundTimelock(*u)
	}
	return tlu
}

// AddIntermediateRefundTimelock adds u to the "intermediate_refund_timelock" field.
func (tlu *TransferLeafUpdate) AddIntermediateRefundTimelock(u int64) *TransferLeafUpdate {
	tlu.mutation.AddIntermediateRefundTimelock(u)
	return tlu
}

// ClearIntermediateRefundTimelock clears the value of the "intermediate_refund_timelock" field.
func (tlu *TransferLeafUpdate) ClearIntermediateRefundTimelock() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateRefundTimelock()
	return tlu
}

// SetIntermediateDirectRefundTimelock sets the "intermediate_direct_refund_timelock" field.
func (tlu *TransferLeafUpdate) SetIntermediateDirectRefundTimelock(u uint64) *TransferLeafUpdate {
	tlu.mutation.ResetIntermediateDirectRefundTimelock()
	tlu.mutation.SetIntermediateDirectRefundTimelock(u)
	return tlu
}

// SetNillableIntermediateDirectRefundTimelock sets the "intermediate_direct_refund_timelock" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableIntermediateDirectRefundTimelock(u *uint64) *TransferLeafUpdate {
	if u != nil {
		tlu.SetIntermediateDirectRefundTimelock(*u)
	}
	return tlu
}

// AddIntermediateDirectRefundTimelock adds u to the "intermediate_direct_refund_timelock" field.
func (tlu *TransferLeafUpdate) AddIntermediateDirectRefundTimelock(u int64) *TransferLeafUpdate {
	tlu.mutation.AddIntermediateDirectRefundTimelock(u)
	return tlu
}

// ClearIntermediateDirectRefundTimelock clears the value of the "intermediate_direct_refund_timelock" field.
func (tlu *TransferLeafUpdate) ClearIntermediateDirectRefundTimelock() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateDirectRefundTimelock()
	return tlu
}

// SetIntermediateDirectFromCpfpRefundTimelock sets the "intermediate_direct_from_cpfp_refund_timelock" field.
func (tlu *TransferLeafUpdate) SetIntermediateDirectFromCpfpRefundTimelock(u uint64) *TransferLeafUpdate {
	tlu.mutation.ResetIntermediateDirectFromCpfpRefundTimelock()
	tlu.mutation.SetIntermediateDirectFromCpfpRefundTimelock(u)
	return tlu
}

// SetNillableIntermediateDirectFromCpfpRefundTimelock sets the "intermediate_direct_from_cpfp_refund_timelock" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableIntermediateDirectFromCpfpRefundTimelock(u *uint64) *TransferLeafUpdate {
	if u != nil {
		tlu.SetIntermediateDirectFromCpfpRefundTimelock(*u)
	}
	return tlu
}

// AddIntermediateDirectFromCpfpRefundTimelock adds u to the "intermediate_direct_from_cpfp_refund_timelock" field.
func (tlu *TransferLeafUpdate) AddIntermediateDirectFromCpfpRefundTimelock(u int64) *TransferLeafUpdate {
	tlu.mutation.AddIntermediateDirectFromCpfpRefundTimelock(u)
	return tlu
}

// ClearIntermediateDirectFromCpfpRefundTimelock clears the value of the "intermediate_direct_from_cpfp_refund_timelock" field.
func (tlu *TransferLeafUpdate) ClearIntermediateDirectFromCpfpRefundTimelock() *TransferLeafUpdate {
	tlu.mutation.ClearIntermediateDirectFromCpfpRefundTimelock()
	return tlu
}

// SetKeyTweak sets the "key_tweak" field.
func (tlu *TransferLeafUpdate) SetKeyTweak(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetKeyTweak(b)
	return tlu
}

// ClearKeyTweak clears the value of the "key_tweak" field.
func (tlu *TransferLeafUpdate) ClearKeyTweak() *TransferLeafUpdate {
	tlu.mutation.ClearKeyTweak()
	return tlu
}

// SetSenderKeyTweakProof sets the "sender_key_tweak_proof" field.
func (tlu *TransferLeafUpdate) SetSenderKeyTweakProof(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetSenderKeyTweakProof(b)
	return tlu
}

// ClearSenderKeyTweakProof clears the value of the "sender_key_tweak_proof" field.
func (tlu *TransferLeafUpdate) ClearSenderKeyTweakProof() *TransferLeafUpdate {
	tlu.mutation.ClearSenderKeyTweakProof()
	return tlu
}

// SetReceiverKeyTweak sets the "receiver_key_tweak" field.
func (tlu *TransferLeafUpdate) SetReceiverKeyTweak(b []byte) *TransferLeafUpdate {
	tlu.mutation.SetReceiverKeyTweak(b)
	return tlu
}

// ClearReceiverKeyTweak clears the value of the "receiver_key_tweak" field.
func (tlu *TransferLeafUpdate) ClearReceiverKeyTweak() *TransferLeafUpdate {
	tlu.mutation.ClearReceiverKeyTweak()
	return tlu
}

// SetTransferReceiverID sets the "transfer_receiver_id" field.
func (tlu *TransferLeafUpdate) SetTransferReceiverID(u uuid.UUID) *TransferLeafUpdate {
	tlu.mutation.SetTransferReceiverID(u)
	return tlu
}

// SetNillableTransferReceiverID sets the "transfer_receiver_id" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableTransferReceiverID(u *uuid.UUID) *TransferLeafUpdate {
	if u != nil {
		tlu.SetTransferReceiverID(*u)
	}
	return tlu
}

// ClearTransferReceiverID clears the value of the "transfer_receiver_id" field.
func (tlu *TransferLeafUpdate) ClearTransferReceiverID() *TransferLeafUpdate {
	tlu.mutation.ClearTransferReceiverID()
	return tlu
}

// SetTransferSenderID sets the "transfer_sender_id" field.
func (tlu *TransferLeafUpdate) SetTransferSenderID(u uuid.UUID) *TransferLeafUpdate {
	tlu.mutation.SetTransferSenderID(u)
	return tlu
}

// SetNillableTransferSenderID sets the "transfer_sender_id" field if the given value is not nil.
func (tlu *TransferLeafUpdate) SetNillableTransferSenderID(u *uuid.UUID) *TransferLeafUpdate {
	if u != nil {
		tlu.SetTransferSenderID(*u)
	}
	return tlu
}

// ClearTransferSenderID clears the value of the "transfer_sender_id" field.
func (tlu *TransferLeafUpdate) ClearTransferSenderID() *TransferLeafUpdate {
	tlu.mutation.ClearTransferSenderID()
	return tlu
}

// SetTransferReceiver sets the "transfer_receiver" edge to the TransferReceiver entity.
func (tlu *TransferLeafUpdate) SetTransferReceiver(t *TransferReceiver) *TransferLeafUpdate {
	return tlu.SetTransferReceiverID(t.ID)
}

// SetTransferSender sets the "transfer_sender" edge to the TransferSender entity.
func (tlu *TransferLeafUpdate) SetTransferSender(t *TransferSender) *TransferLeafUpdate {
	return tlu.SetTransferSenderID(t.ID)
}

// Mutation returns the TransferLeafMutation object of the builder.
func (tlu *TransferLeafUpdate) Mutation() *TransferLeafMutation {
	return tlu.mutation
}

// ClearTransferReceiver clears the "transfer_receiver" edge to the TransferReceiver entity.
func (tlu *TransferLeafUpdate) ClearTransferReceiver() *TransferLeafUpdate {
	tlu.mutation.ClearTransferReceiver()
	return tlu
}

// ClearTransferSender clears the "transfer_sender" edge to the TransferSender entity.
func (tlu *TransferLeafUpdate) ClearTransferSender() *TransferLeafUpdate {
	tlu.mutation.ClearTransferSender()
	return tlu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tlu *TransferLeafUpdate) Save(ctx context.Context) (int, error) {
	if err := tlu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, tlu.sqlSave, tlu.mutation, tlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tlu *TransferLeafUpdate) SaveX(ctx context.Context) int {
	affected, err := tlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tlu *TransferLeafUpdate) Exec(ctx context.Context) error {
	_, err := tlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlu *TransferLeafUpdate) ExecX(ctx context.Context) {
	if err := tlu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tlu *TransferLeafUpdate) defaults() error {
	if _, ok := tlu.mutation.UpdateTime(); !ok {
		if transferleaf.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized transferleaf.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := transferleaf.UpdateDefaultUpdateTime()
		tlu.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tlu *TransferLeafUpdate) check() error {
	if v, ok := tlu.mutation.IntermediateRefundTx(); ok {
		if err := transferleaf.IntermediateRefundTxValidator(v); err != nil {
			return &ValidationError{Name: "intermediate_refund_tx", err: fmt.Errorf(`ent: validator failed for field "TransferLeaf.intermediate_refund_tx": %w`, err)}
		}
	}
	if tlu.mutation.TransferCleared() && len(tlu.mutation.TransferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferLeaf.transfer"`)
	}
	if tlu.mutation.LeafCleared() && len(tlu.mutation.LeafIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferLeaf.leaf"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tlu *TransferLeafUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransferLeafUpdate {
	tlu.modifiers = append(tlu.modifiers, modifiers...)
	return tlu
}

func (tlu *TransferLeafUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tlu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferleaf.Table, transferleaf.Columns, sqlgraph.NewFieldSpec(transferleaf.FieldID, field.TypeUUID))
	if ps := tlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tlu.mutation.UpdateTime(); ok {
		_spec.SetField(transferleaf.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tlu.mutation.SecretCipher(); ok {
		_spec.SetField(transferleaf.FieldSecretCipher, field.TypeBytes, value)
	}
	if tlu.mutation.SecretCipherCleared() {
		_spec.ClearField(transferleaf.FieldSecretCipher, field.TypeBytes)
	}
	if value, ok := tlu.mutation.Signature(); ok {
		_spec.SetField(transferleaf.FieldSignature, field.TypeBytes, value)
	}
	if tlu.mutation.SignatureCleared() {
		_spec.ClearField(transferleaf.FieldSignature, field.TypeBytes)
	}
	if tlu.mutation.PreviousDirectRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldPreviousDirectRefundTx, field.TypeBytes)
	}
	if tlu.mutation.PreviousDirectFromCpfpRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldPreviousDirectFromCpfpRefundTx, field.TypeBytes)
	}
	if value, ok := tlu.mutation.IntermediateRefundTx(); ok {
		_spec.SetField(transferleaf.FieldIntermediateRefundTx, field.TypeBytes, value)
	}
	if value, ok := tlu.mutation.IntermediateDirectRefundTx(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectRefundTx, field.TypeBytes, value)
	}
	if tlu.mutation.IntermediateDirectRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectRefundTx, field.TypeBytes)
	}
	if value, ok := tlu.mutation.IntermediateDirectFromCpfpRefundTx(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectFromCpfpRefundTx, field.TypeBytes, value)
	}
	if tlu.mutation.IntermediateDirectFromCpfpRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectFromCpfpRefundTx, field.TypeBytes)
	}
	if value, ok := tlu.mutation.IntermediateRefundTxid(); ok {
		_spec.SetField(transferleaf.FieldIntermediateRefundTxid, field.TypeBytes, value)
	}
	if tlu.mutation.IntermediateRefundTxidCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateRefundTxid, field.TypeBytes)
	}
	if value, ok := tlu.mutation.IntermediateDirectRefundTxid(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectRefundTxid, field.TypeBytes, value)
	}
	if tlu.mutation.IntermediateDirectRefundTxidCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectRefundTxid, field.TypeBytes)
	}
	if value, ok := tlu.mutation.IntermediateDirectFromCpfpRefundTxid(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectFromCpfpRefundTxid, field.TypeBytes, value)
	}
	if tlu.mutation.IntermediateDirectFromCpfpRefundTxidCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectFromCpfpRefundTxid, field.TypeBytes)
	}
	if value, ok := tlu.mutation.IntermediateRefundTimelock(); ok {
		_spec.SetField(transferleaf.FieldIntermediateRefundTimelock, field.TypeUint64, value)
	}
	if value, ok := tlu.mutation.AddedIntermediateRefundTimelock(); ok {
		_spec.AddField(transferleaf.FieldIntermediateRefundTimelock, field.TypeUint64, value)
	}
	if tlu.mutation.IntermediateRefundTimelockCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateRefundTimelock, field.TypeUint64)
	}
	if value, ok := tlu.mutation.IntermediateDirectRefundTimelock(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectRefundTimelock, field.TypeUint64, value)
	}
	if value, ok := tlu.mutation.AddedIntermediateDirectRefundTimelock(); ok {
		_spec.AddField(transferleaf.FieldIntermediateDirectRefundTimelock, field.TypeUint64, value)
	}
	if tlu.mutation.IntermediateDirectRefundTimelockCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectRefundTimelock, field.TypeUint64)
	}
	if value, ok := tlu.mutation.IntermediateDirectFromCpfpRefundTimelock(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectFromCpfpRefundTimelock, field.TypeUint64, value)
	}
	if value, ok := tlu.mutation.AddedIntermediateDirectFromCpfpRefundTimelock(); ok {
		_spec.AddField(transferleaf.FieldIntermediateDirectFromCpfpRefundTimelock, field.TypeUint64, value)
	}
	if tlu.mutation.IntermediateDirectFromCpfpRefundTimelockCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectFromCpfpRefundTimelock, field.TypeUint64)
	}
	if value, ok := tlu.mutation.KeyTweak(); ok {
		_spec.SetField(transferleaf.FieldKeyTweak, field.TypeBytes, value)
	}
	if tlu.mutation.KeyTweakCleared() {
		_spec.ClearField(transferleaf.FieldKeyTweak, field.TypeBytes)
	}
	if value, ok := tlu.mutation.SenderKeyTweakProof(); ok {
		_spec.SetField(transferleaf.FieldSenderKeyTweakProof, field.TypeBytes, value)
	}
	if tlu.mutation.SenderKeyTweakProofCleared() {
		_spec.ClearField(transferleaf.FieldSenderKeyTweakProof, field.TypeBytes)
	}
	if value, ok := tlu.mutation.ReceiverKeyTweak(); ok {
		_spec.SetField(transferleaf.FieldReceiverKeyTweak, field.TypeBytes, value)
	}
	if tlu.mutation.ReceiverKeyTweakCleared() {
		_spec.ClearField(transferleaf.FieldReceiverKeyTweak, field.TypeBytes)
	}
	if tlu.mutation.TransferReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferReceiverTable,
			Columns: []string{transferleaf.TransferReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tlu.mutation.TransferReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferReceiverTable,
			Columns: []string{transferleaf.TransferReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tlu.mutation.TransferSenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferSenderTable,
			Columns: []string{transferleaf.TransferSenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transfersender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tlu.mutation.TransferSenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferSenderTable,
			Columns: []string{transferleaf.TransferSenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transfersender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tlu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferleaf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tlu.mutation.done = true
	return n, nil
}

// TransferLeafUpdateOne is the builder for updating a single TransferLeaf entity.
type TransferLeafUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TransferLeafMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (tluo *TransferLeafUpdateOne) SetUpdateTime(t time.Time) *TransferLeafUpdateOne {
	tluo.mutation.SetUpdateTime(t)
	return tluo
}

// SetSecretCipher sets the "secret_cipher" field.
func (tluo *TransferLeafUpdateOne) SetSecretCipher(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetSecretCipher(b)
	return tluo
}

// ClearSecretCipher clears the value of the "secret_cipher" field.
func (tluo *TransferLeafUpdateOne) ClearSecretCipher() *TransferLeafUpdateOne {
	tluo.mutation.ClearSecretCipher()
	return tluo
}

// SetSignature sets the "signature" field.
func (tluo *TransferLeafUpdateOne) SetSignature(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetSignature(b)
	return tluo
}

// ClearSignature clears the value of the "signature" field.
func (tluo *TransferLeafUpdateOne) ClearSignature() *TransferLeafUpdateOne {
	tluo.mutation.ClearSignature()
	return tluo
}

// SetIntermediateRefundTx sets the "intermediate_refund_tx" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateRefundTx(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetIntermediateRefundTx(b)
	return tluo
}

// SetIntermediateDirectRefundTx sets the "intermediate_direct_refund_tx" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateDirectRefundTx(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetIntermediateDirectRefundTx(b)
	return tluo
}

// ClearIntermediateDirectRefundTx clears the value of the "intermediate_direct_refund_tx" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateDirectRefundTx() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateDirectRefundTx()
	return tluo
}

// SetIntermediateDirectFromCpfpRefundTx sets the "intermediate_direct_from_cpfp_refund_tx" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateDirectFromCpfpRefundTx(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetIntermediateDirectFromCpfpRefundTx(b)
	return tluo
}

// ClearIntermediateDirectFromCpfpRefundTx clears the value of the "intermediate_direct_from_cpfp_refund_tx" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateDirectFromCpfpRefundTx() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateDirectFromCpfpRefundTx()
	return tluo
}

// SetIntermediateRefundTxid sets the "intermediate_refund_txid" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateRefundTxid(si schematype.TxID) *TransferLeafUpdateOne {
	tluo.mutation.SetIntermediateRefundTxid(si)
	return tluo
}

// SetNillableIntermediateRefundTxid sets the "intermediate_refund_txid" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableIntermediateRefundTxid(si *schematype.TxID) *TransferLeafUpdateOne {
	if si != nil {
		tluo.SetIntermediateRefundTxid(*si)
	}
	return tluo
}

// ClearIntermediateRefundTxid clears the value of the "intermediate_refund_txid" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateRefundTxid() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateRefundTxid()
	return tluo
}

// SetIntermediateDirectRefundTxid sets the "intermediate_direct_refund_txid" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateDirectRefundTxid(si schematype.TxID) *TransferLeafUpdateOne {
	tluo.mutation.SetIntermediateDirectRefundTxid(si)
	return tluo
}

// SetNillableIntermediateDirectRefundTxid sets the "intermediate_direct_refund_txid" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableIntermediateDirectRefundTxid(si *schematype.TxID) *TransferLeafUpdateOne {
	if si != nil {
		tluo.SetIntermediateDirectRefundTxid(*si)
	}
	return tluo
}

// ClearIntermediateDirectRefundTxid clears the value of the "intermediate_direct_refund_txid" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateDirectRefundTxid() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateDirectRefundTxid()
	return tluo
}

// SetIntermediateDirectFromCpfpRefundTxid sets the "intermediate_direct_from_cpfp_refund_txid" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateDirectFromCpfpRefundTxid(si schematype.TxID) *TransferLeafUpdateOne {
	tluo.mutation.SetIntermediateDirectFromCpfpRefundTxid(si)
	return tluo
}

// SetNillableIntermediateDirectFromCpfpRefundTxid sets the "intermediate_direct_from_cpfp_refund_txid" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableIntermediateDirectFromCpfpRefundTxid(si *schematype.TxID) *TransferLeafUpdateOne {
	if si != nil {
		tluo.SetIntermediateDirectFromCpfpRefundTxid(*si)
	}
	return tluo
}

// ClearIntermediateDirectFromCpfpRefundTxid clears the value of the "intermediate_direct_from_cpfp_refund_txid" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateDirectFromCpfpRefundTxid() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateDirectFromCpfpRefundTxid()
	return tluo
}

// SetIntermediateRefundTimelock sets the "intermediate_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateRefundTimelock(u uint64) *TransferLeafUpdateOne {
	tluo.mutation.ResetIntermediateRefundTimelock()
	tluo.mutation.SetIntermediateRefundTimelock(u)
	return tluo
}

// SetNillableIntermediateRefundTimelock sets the "intermediate_refund_timelock" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableIntermediateRefundTimelock(u *uint64) *TransferLeafUpdateOne {
	if u != nil {
		tluo.SetIntermediateRefundTimelock(*u)
	}
	return tluo
}

// AddIntermediateRefundTimelock adds u to the "intermediate_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) AddIntermediateRefundTimelock(u int64) *TransferLeafUpdateOne {
	tluo.mutation.AddIntermediateRefundTimelock(u)
	return tluo
}

// ClearIntermediateRefundTimelock clears the value of the "intermediate_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateRefundTimelock() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateRefundTimelock()
	return tluo
}

// SetIntermediateDirectRefundTimelock sets the "intermediate_direct_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateDirectRefundTimelock(u uint64) *TransferLeafUpdateOne {
	tluo.mutation.ResetIntermediateDirectRefundTimelock()
	tluo.mutation.SetIntermediateDirectRefundTimelock(u)
	return tluo
}

// SetNillableIntermediateDirectRefundTimelock sets the "intermediate_direct_refund_timelock" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableIntermediateDirectRefundTimelock(u *uint64) *TransferLeafUpdateOne {
	if u != nil {
		tluo.SetIntermediateDirectRefundTimelock(*u)
	}
	return tluo
}

// AddIntermediateDirectRefundTimelock adds u to the "intermediate_direct_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) AddIntermediateDirectRefundTimelock(u int64) *TransferLeafUpdateOne {
	tluo.mutation.AddIntermediateDirectRefundTimelock(u)
	return tluo
}

// ClearIntermediateDirectRefundTimelock clears the value of the "intermediate_direct_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateDirectRefundTimelock() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateDirectRefundTimelock()
	return tluo
}

// SetIntermediateDirectFromCpfpRefundTimelock sets the "intermediate_direct_from_cpfp_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) SetIntermediateDirectFromCpfpRefundTimelock(u uint64) *TransferLeafUpdateOne {
	tluo.mutation.ResetIntermediateDirectFromCpfpRefundTimelock()
	tluo.mutation.SetIntermediateDirectFromCpfpRefundTimelock(u)
	return tluo
}

// SetNillableIntermediateDirectFromCpfpRefundTimelock sets the "intermediate_direct_from_cpfp_refund_timelock" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableIntermediateDirectFromCpfpRefundTimelock(u *uint64) *TransferLeafUpdateOne {
	if u != nil {
		tluo.SetIntermediateDirectFromCpfpRefundTimelock(*u)
	}
	return tluo
}

// AddIntermediateDirectFromCpfpRefundTimelock adds u to the "intermediate_direct_from_cpfp_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) AddIntermediateDirectFromCpfpRefundTimelock(u int64) *TransferLeafUpdateOne {
	tluo.mutation.AddIntermediateDirectFromCpfpRefundTimelock(u)
	return tluo
}

// ClearIntermediateDirectFromCpfpRefundTimelock clears the value of the "intermediate_direct_from_cpfp_refund_timelock" field.
func (tluo *TransferLeafUpdateOne) ClearIntermediateDirectFromCpfpRefundTimelock() *TransferLeafUpdateOne {
	tluo.mutation.ClearIntermediateDirectFromCpfpRefundTimelock()
	return tluo
}

// SetKeyTweak sets the "key_tweak" field.
func (tluo *TransferLeafUpdateOne) SetKeyTweak(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetKeyTweak(b)
	return tluo
}

// ClearKeyTweak clears the value of the "key_tweak" field.
func (tluo *TransferLeafUpdateOne) ClearKeyTweak() *TransferLeafUpdateOne {
	tluo.mutation.ClearKeyTweak()
	return tluo
}

// SetSenderKeyTweakProof sets the "sender_key_tweak_proof" field.
func (tluo *TransferLeafUpdateOne) SetSenderKeyTweakProof(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetSenderKeyTweakProof(b)
	return tluo
}

// ClearSenderKeyTweakProof clears the value of the "sender_key_tweak_proof" field.
func (tluo *TransferLeafUpdateOne) ClearSenderKeyTweakProof() *TransferLeafUpdateOne {
	tluo.mutation.ClearSenderKeyTweakProof()
	return tluo
}

// SetReceiverKeyTweak sets the "receiver_key_tweak" field.
func (tluo *TransferLeafUpdateOne) SetReceiverKeyTweak(b []byte) *TransferLeafUpdateOne {
	tluo.mutation.SetReceiverKeyTweak(b)
	return tluo
}

// ClearReceiverKeyTweak clears the value of the "receiver_key_tweak" field.
func (tluo *TransferLeafUpdateOne) ClearReceiverKeyTweak() *TransferLeafUpdateOne {
	tluo.mutation.ClearReceiverKeyTweak()
	return tluo
}

// SetTransferReceiverID sets the "transfer_receiver_id" field.
func (tluo *TransferLeafUpdateOne) SetTransferReceiverID(u uuid.UUID) *TransferLeafUpdateOne {
	tluo.mutation.SetTransferReceiverID(u)
	return tluo
}

// SetNillableTransferReceiverID sets the "transfer_receiver_id" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableTransferReceiverID(u *uuid.UUID) *TransferLeafUpdateOne {
	if u != nil {
		tluo.SetTransferReceiverID(*u)
	}
	return tluo
}

// ClearTransferReceiverID clears the value of the "transfer_receiver_id" field.
func (tluo *TransferLeafUpdateOne) ClearTransferReceiverID() *TransferLeafUpdateOne {
	tluo.mutation.ClearTransferReceiverID()
	return tluo
}

// SetTransferSenderID sets the "transfer_sender_id" field.
func (tluo *TransferLeafUpdateOne) SetTransferSenderID(u uuid.UUID) *TransferLeafUpdateOne {
	tluo.mutation.SetTransferSenderID(u)
	return tluo
}

// SetNillableTransferSenderID sets the "transfer_sender_id" field if the given value is not nil.
func (tluo *TransferLeafUpdateOne) SetNillableTransferSenderID(u *uuid.UUID) *TransferLeafUpdateOne {
	if u != nil {
		tluo.SetTransferSenderID(*u)
	}
	return tluo
}

// ClearTransferSenderID clears the value of the "transfer_sender_id" field.
func (tluo *TransferLeafUpdateOne) ClearTransferSenderID() *TransferLeafUpdateOne {
	tluo.mutation.ClearTransferSenderID()
	return tluo
}

// SetTransferReceiver sets the "transfer_receiver" edge to the TransferReceiver entity.
func (tluo *TransferLeafUpdateOne) SetTransferReceiver(t *TransferReceiver) *TransferLeafUpdateOne {
	return tluo.SetTransferReceiverID(t.ID)
}

// SetTransferSender sets the "transfer_sender" edge to the TransferSender entity.
func (tluo *TransferLeafUpdateOne) SetTransferSender(t *TransferSender) *TransferLeafUpdateOne {
	return tluo.SetTransferSenderID(t.ID)
}

// Mutation returns the TransferLeafMutation object of the builder.
func (tluo *TransferLeafUpdateOne) Mutation() *TransferLeafMutation {
	return tluo.mutation
}

// ClearTransferReceiver clears the "transfer_receiver" edge to the TransferReceiver entity.
func (tluo *TransferLeafUpdateOne) ClearTransferReceiver() *TransferLeafUpdateOne {
	tluo.mutation.ClearTransferReceiver()
	return tluo
}

// ClearTransferSender clears the "transfer_sender" edge to the TransferSender entity.
func (tluo *TransferLeafUpdateOne) ClearTransferSender() *TransferLeafUpdateOne {
	tluo.mutation.ClearTransferSender()
	return tluo
}

// Where appends a list predicates to the TransferLeafUpdate builder.
func (tluo *TransferLeafUpdateOne) Where(ps ...predicate.TransferLeaf) *TransferLeafUpdateOne {
	tluo.mutation.Where(ps...)
	return tluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tluo *TransferLeafUpdateOne) Select(field string, fields ...string) *TransferLeafUpdateOne {
	tluo.fields = append([]string{field}, fields...)
	return tluo
}

// Save executes the query and returns the updated TransferLeaf entity.
func (tluo *TransferLeafUpdateOne) Save(ctx context.Context) (*TransferLeaf, error) {
	if err := tluo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tluo.sqlSave, tluo.mutation, tluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tluo *TransferLeafUpdateOne) SaveX(ctx context.Context) *TransferLeaf {
	node, err := tluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tluo *TransferLeafUpdateOne) Exec(ctx context.Context) error {
	_, err := tluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tluo *TransferLeafUpdateOne) ExecX(ctx context.Context) {
	if err := tluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tluo *TransferLeafUpdateOne) defaults() error {
	if _, ok := tluo.mutation.UpdateTime(); !ok {
		if transferleaf.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized transferleaf.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := transferleaf.UpdateDefaultUpdateTime()
		tluo.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tluo *TransferLeafUpdateOne) check() error {
	if v, ok := tluo.mutation.IntermediateRefundTx(); ok {
		if err := transferleaf.IntermediateRefundTxValidator(v); err != nil {
			return &ValidationError{Name: "intermediate_refund_tx", err: fmt.Errorf(`ent: validator failed for field "TransferLeaf.intermediate_refund_tx": %w`, err)}
		}
	}
	if tluo.mutation.TransferCleared() && len(tluo.mutation.TransferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferLeaf.transfer"`)
	}
	if tluo.mutation.LeafCleared() && len(tluo.mutation.LeafIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TransferLeaf.leaf"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tluo *TransferLeafUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransferLeafUpdateOne {
	tluo.modifiers = append(tluo.modifiers, modifiers...)
	return tluo
}

func (tluo *TransferLeafUpdateOne) sqlSave(ctx context.Context) (_node *TransferLeaf, err error) {
	if err := tluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transferleaf.Table, transferleaf.Columns, sqlgraph.NewFieldSpec(transferleaf.FieldID, field.TypeUUID))
	id, ok := tluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransferLeaf.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transferleaf.FieldID)
		for _, f := range fields {
			if !transferleaf.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transferleaf.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tluo.mutation.UpdateTime(); ok {
		_spec.SetField(transferleaf.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := tluo.mutation.SecretCipher(); ok {
		_spec.SetField(transferleaf.FieldSecretCipher, field.TypeBytes, value)
	}
	if tluo.mutation.SecretCipherCleared() {
		_spec.ClearField(transferleaf.FieldSecretCipher, field.TypeBytes)
	}
	if value, ok := tluo.mutation.Signature(); ok {
		_spec.SetField(transferleaf.FieldSignature, field.TypeBytes, value)
	}
	if tluo.mutation.SignatureCleared() {
		_spec.ClearField(transferleaf.FieldSignature, field.TypeBytes)
	}
	if tluo.mutation.PreviousDirectRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldPreviousDirectRefundTx, field.TypeBytes)
	}
	if tluo.mutation.PreviousDirectFromCpfpRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldPreviousDirectFromCpfpRefundTx, field.TypeBytes)
	}
	if value, ok := tluo.mutation.IntermediateRefundTx(); ok {
		_spec.SetField(transferleaf.FieldIntermediateRefundTx, field.TypeBytes, value)
	}
	if value, ok := tluo.mutation.IntermediateDirectRefundTx(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectRefundTx, field.TypeBytes, value)
	}
	if tluo.mutation.IntermediateDirectRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectRefundTx, field.TypeBytes)
	}
	if value, ok := tluo.mutation.IntermediateDirectFromCpfpRefundTx(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectFromCpfpRefundTx, field.TypeBytes, value)
	}
	if tluo.mutation.IntermediateDirectFromCpfpRefundTxCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectFromCpfpRefundTx, field.TypeBytes)
	}
	if value, ok := tluo.mutation.IntermediateRefundTxid(); ok {
		_spec.SetField(transferleaf.FieldIntermediateRefundTxid, field.TypeBytes, value)
	}
	if tluo.mutation.IntermediateRefundTxidCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateRefundTxid, field.TypeBytes)
	}
	if value, ok := tluo.mutation.IntermediateDirectRefundTxid(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectRefundTxid, field.TypeBytes, value)
	}
	if tluo.mutation.IntermediateDirectRefundTxidCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectRefundTxid, field.TypeBytes)
	}
	if value, ok := tluo.mutation.IntermediateDirectFromCpfpRefundTxid(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectFromCpfpRefundTxid, field.TypeBytes, value)
	}
	if tluo.mutation.IntermediateDirectFromCpfpRefundTxidCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectFromCpfpRefundTxid, field.TypeBytes)
	}
	if value, ok := tluo.mutation.IntermediateRefundTimelock(); ok {
		_spec.SetField(transferleaf.FieldIntermediateRefundTimelock, field.TypeUint64, value)
	}
	if value, ok := tluo.mutation.AddedIntermediateRefundTimelock(); ok {
		_spec.AddField(transferleaf.FieldIntermediateRefundTimelock, field.TypeUint64, value)
	}
	if tluo.mutation.IntermediateRefundTimelockCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateRefundTimelock, field.TypeUint64)
	}
	if value, ok := tluo.mutation.IntermediateDirectRefundTimelock(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectRefundTimelock, field.TypeUint64, value)
	}
	if value, ok := tluo.mutation.AddedIntermediateDirectRefundTimelock(); ok {
		_spec.AddField(transferleaf.FieldIntermediateDirectRefundTimelock, field.TypeUint64, value)
	}
	if tluo.mutation.IntermediateDirectRefundTimelockCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectRefundTimelock, field.TypeUint64)
	}
	if value, ok := tluo.mutation.IntermediateDirectFromCpfpRefundTimelock(); ok {
		_spec.SetField(transferleaf.FieldIntermediateDirectFromCpfpRefundTimelock, field.TypeUint64, value)
	}
	if value, ok := tluo.mutation.AddedIntermediateDirectFromCpfpRefundTimelock(); ok {
		_spec.AddField(transferleaf.FieldIntermediateDirectFromCpfpRefundTimelock, field.TypeUint64, value)
	}
	if tluo.mutation.IntermediateDirectFromCpfpRefundTimelockCleared() {
		_spec.ClearField(transferleaf.FieldIntermediateDirectFromCpfpRefundTimelock, field.TypeUint64)
	}
	if value, ok := tluo.mutation.KeyTweak(); ok {
		_spec.SetField(transferleaf.FieldKeyTweak, field.TypeBytes, value)
	}
	if tluo.mutation.KeyTweakCleared() {
		_spec.ClearField(transferleaf.FieldKeyTweak, field.TypeBytes)
	}
	if value, ok := tluo.mutation.SenderKeyTweakProof(); ok {
		_spec.SetField(transferleaf.FieldSenderKeyTweakProof, field.TypeBytes, value)
	}
	if tluo.mutation.SenderKeyTweakProofCleared() {
		_spec.ClearField(transferleaf.FieldSenderKeyTweakProof, field.TypeBytes)
	}
	if value, ok := tluo.mutation.ReceiverKeyTweak(); ok {
		_spec.SetField(transferleaf.FieldReceiverKeyTweak, field.TypeBytes, value)
	}
	if tluo.mutation.ReceiverKeyTweakCleared() {
		_spec.ClearField(transferleaf.FieldReceiverKeyTweak, field.TypeBytes)
	}
	if tluo.mutation.TransferReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferReceiverTable,
			Columns: []string{transferleaf.TransferReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tluo.mutation.TransferReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferReceiverTable,
			Columns: []string{transferleaf.TransferReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tluo.mutation.TransferSenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferSenderTable,
			Columns: []string{transferleaf.TransferSenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transfersender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tluo.mutation.TransferSenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   transferleaf.TransferSenderTable,
			Columns: []string{transferleaf.TransferSenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transfersender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tluo.modifiers...)
	_node = &TransferLeaf{config: tluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transferleaf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tluo.mutation.done = true
	return _node, nil
}
