// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/transferreceiver"
)

// TransferReceiverDelete is the builder for deleting a TransferReceiver entity.
type TransferReceiverDelete struct {
	config
	hooks    []Hook
	mutation *TransferReceiverMutation
}

// Where appends a list predicates to the TransferReceiverDelete builder.
func (trd *TransferReceiverDelete) Where(ps ...predicate.TransferReceiver) *TransferReceiverDelete {
	trd.mutation.Where(ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TransferReceiverDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, trd.sqlExec, trd.mutation, trd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TransferReceiverDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TransferReceiverDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(transferreceiver.Table, sqlgraph.NewFieldSpec(transferreceiver.FieldID, field.TypeUUID))
	if ps := trd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	trd.mutation.done = true
	return affected, err
}

// TransferReceiverDeleteOne is the builder for deleting a single TransferReceiver entity.
type TransferReceiverDeleteOne struct {
	trd *TransferReceiverDelete
}

// Where appends a list predicates to the TransferReceiverDelete builder.
func (trdo *TransferReceiverDeleteOne) Where(ps ...predicate.TransferReceiver) *TransferReceiverDeleteOne {
	trdo.trd.mutation.Where(ps...)
	return trdo
}

// Exec executes the deletion query.
func (trdo *TransferReceiverDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transferreceiver.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TransferReceiverDeleteOne) ExecX(ctx context.Context) {
	if err := trdo.Exec(ctx); err != nil {
		panic(err)
	}
}
