// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/transfer"
	"github.com/lightsparkdev/spark/so/ent/transfersender"
)

// TransferSenderQuery is the builder for querying TransferSender entities.
type TransferSenderQuery struct {
	config
	ctx          *QueryContext
	order        []transfersender.OrderOption
	inters       []Interceptor
	predicates   []predicate.TransferSender
	withTransfer *TransferQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TransferSenderQuery builder.
func (tsq *TransferSenderQuery) Where(ps ...predicate.TransferSender) *TransferSenderQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TransferSenderQuery) Limit(limit int) *TransferSenderQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TransferSenderQuery) Offset(offset int) *TransferSenderQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TransferSenderQuery) Unique(unique bool) *TransferSenderQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TransferSenderQuery) Order(o ...transfersender.OrderOption) *TransferSenderQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// QueryTransfer chains the current query on the "transfer" edge.
func (tsq *TransferSenderQuery) QueryTransfer() *TransferQuery {
	query := (&TransferClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(transfersender.Table, transfersender.FieldID, selector),
			sqlgraph.To(transfer.Table, transfer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, transfersender.TransferTable, transfersender.TransferColumn),
		)
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TransferSender entity from the query.
// Returns a *NotFoundError when no TransferSender was found.
func (tsq *TransferSenderQuery) First(ctx context.Context) (*TransferSender, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{transfersender.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TransferSenderQuery) FirstX(ctx context.Context) *TransferSender {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TransferSender ID from the query.
// Returns a *NotFoundError when no TransferSender ID was found.
func (tsq *TransferSenderQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{transfersender.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TransferSenderQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TransferSender entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TransferSender entity is found.
// Returns a *NotFoundError when no TransferSender entities are found.
func (tsq *TransferSenderQuery) Only(ctx context.Context) (*TransferSender, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{transfersender.Label}
	default:
		return nil, &NotSingularError{transfersender.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TransferSenderQuery) OnlyX(ctx context.Context) *TransferSender {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TransferSender ID in the query.
// Returns a *NotSingularError when more than one TransferSender ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TransferSenderQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{transfersender.Label}
	default:
		err = &NotSingularError{transfersender.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TransferSenderQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TransferSenders.
func (tsq *TransferSenderQuery) All(ctx context.Context) ([]*TransferSender, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryAll)
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TransferSender, *TransferSenderQuery]()
	return withInterceptors[[]*TransferSender](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TransferSenderQuery) AllX(ctx context.Context) []*TransferSender {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TransferSender IDs.
func (tsq *TransferSenderQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryIDs)
	if err = tsq.Select(transfersender.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TransferSenderQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TransferSenderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryCount)
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TransferSenderQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TransferSenderQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TransferSenderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, ent.OpQueryExist)
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TransferSenderQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TransferSenderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TransferSenderQuery) Clone() *TransferSenderQuery {
	if tsq == nil {
		return nil
	}
	return &TransferSenderQuery{
		config:       tsq.config,
		ctx:          tsq.ctx.Clone(),
		order:        append([]transfersender.OrderOption{}, tsq.order...),
		inters:       append([]Interceptor{}, tsq.inters...),
		predicates:   append([]predicate.TransferSender{}, tsq.predicates...),
		withTransfer: tsq.withTransfer.Clone(),
		// clone intermediate query.
		sql:       tsq.sql.Clone(),
		path:      tsq.path,
		modifiers: append([]func(*sql.Selector){}, tsq.modifiers...),
	}
}

// WithTransfer tells the query-builder to eager-load the nodes that are connected to
// the "transfer" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TransferSenderQuery) WithTransfer(opts ...func(*TransferQuery)) *TransferSenderQuery {
	query := (&TransferClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withTransfer = query
	return tsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TransferSender.Query().
//		GroupBy(transfersender.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tsq *TransferSenderQuery) GroupBy(field string, fields ...string) *TransferSenderGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TransferSenderGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = transfersender.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TransferSender.Query().
//		Select(transfersender.FieldCreateTime).
//		Scan(ctx, &v)
func (tsq *TransferSenderQuery) Select(fields ...string) *TransferSenderSelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TransferSenderSelect{TransferSenderQuery: tsq}
	sbuild.label = transfersender.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TransferSenderSelect configured with the given aggregations.
func (tsq *TransferSenderQuery) Aggregate(fns ...AggregateFunc) *TransferSenderSelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TransferSenderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !transfersender.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TransferSenderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TransferSender, error) {
	var (
		nodes       = []*TransferSender{}
		_spec       = tsq.querySpec()
		loadedTypes = [1]bool{
			tsq.withTransfer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TransferSender).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TransferSender{config: tsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tsq.withTransfer; query != nil {
		if err := tsq.loadTransfer(ctx, query, nodes, nil,
			func(n *TransferSender, e *Transfer) { n.Edges.Transfer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tsq *TransferSenderQuery) loadTransfer(ctx context.Context, query *TransferQuery, nodes []*TransferSender, init func(*TransferSender), assign func(*TransferSender, *Transfer)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TransferSender)
	for i := range nodes {
		fk := nodes[i].TransferID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(transfer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "transfer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tsq *TransferSenderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TransferSenderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(transfersender.Table, transfersender.Columns, sqlgraph.NewFieldSpec(transfersender.FieldID, field.TypeUUID))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transfersender.FieldID)
		for i := range fields {
			if fields[i] != transfersender.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tsq.withTransfer != nil {
			_spec.Node.AddColumnOnce(transfersender.FieldTransferID)
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TransferSenderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(transfersender.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = transfersender.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tsq.modifiers {
		m(selector)
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tsq *TransferSenderQuery) ForUpdate(opts ...sql.LockOption) *TransferSenderQuery {
	if tsq.driver.Dialect() == dialect.Postgres {
		tsq.Unique(false)
	}
	tsq.modifiers = append(tsq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tsq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tsq *TransferSenderQuery) ForShare(opts ...sql.LockOption) *TransferSenderQuery {
	if tsq.driver.Dialect() == dialect.Postgres {
		tsq.Unique(false)
	}
	tsq.modifiers = append(tsq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tsq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tsq *TransferSenderQuery) Modify(modifiers ...func(s *sql.Selector)) *TransferSenderSelect {
	tsq.modifiers = append(tsq.modifiers, modifiers...)
	return tsq.Select()
}

// TransferSenderGroupBy is the group-by builder for TransferSender entities.
type TransferSenderGroupBy struct {
	selector
	build *TransferSenderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TransferSenderGroupBy) Aggregate(fns ...AggregateFunc) *TransferSenderGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TransferSenderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, ent.OpQueryGroupBy)
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferSenderQuery, *TransferSenderGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TransferSenderGroupBy) sqlScan(ctx context.Context, root *TransferSenderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TransferSenderSelect is the builder for selecting fields of TransferSender entities.
type TransferSenderSelect struct {
	*TransferSenderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TransferSenderSelect) Aggregate(fns ...AggregateFunc) *TransferSenderSelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TransferSenderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, ent.OpQuerySelect)
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TransferSenderQuery, *TransferSenderSelect](ctx, tss.TransferSenderQuery, tss, tss.inters, v)
}

func (tss *TransferSenderSelect) sqlScan(ctx context.Context, root *TransferSenderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tss *TransferSenderSelect) Modify(modifiers ...func(s *sql.Selector)) *TransferSenderSelect {
	tss.modifiers = append(tss.modifiers, modifiers...)
	return tss
}
