// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/walletsetting"
)

// WalletSetting is the model entity for the WalletSetting schema.
type WalletSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Signing public key of the owner of the deposit address.
	OwnerIdentityPublicKey keys.Public `json:"owner_identity_public_key,omitempty"`
	// Indicates whether privacy features are enabled for this wallet.
	PrivateEnabled bool `json:"private_enabled,omitempty"`
	// The master identity public key that is allowed to bypass the privacy and read the wallet.
	MasterIdentityPublicKey *keys.Public `json:"master_identity_public_key,omitempty"`
	selectValues            sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WalletSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case walletsetting.FieldMasterIdentityPublicKey:
			values[i] = &sql.NullScanner{S: new(keys.Public)}
		case walletsetting.FieldOwnerIdentityPublicKey:
			values[i] = new(keys.Public)
		case walletsetting.FieldPrivateEnabled:
			values[i] = new(sql.NullBool)
		case walletsetting.FieldCreateTime, walletsetting.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case walletsetting.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WalletSetting fields.
func (ws *WalletSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case walletsetting.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ws.ID = *value
			}
		case walletsetting.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ws.CreateTime = value.Time
			}
		case walletsetting.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ws.UpdateTime = value.Time
			}
		case walletsetting.FieldOwnerIdentityPublicKey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field owner_identity_public_key", values[i])
			} else if value != nil {
				ws.OwnerIdentityPublicKey = *value
			}
		case walletsetting.FieldPrivateEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field private_enabled", values[i])
			} else if value.Valid {
				ws.PrivateEnabled = value.Bool
			}
		case walletsetting.FieldMasterIdentityPublicKey:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field master_identity_public_key", values[i])
			} else if value.Valid {
				ws.MasterIdentityPublicKey = new(keys.Public)
				*ws.MasterIdentityPublicKey = *value.S.(*keys.Public)
			}
		default:
			ws.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WalletSetting.
// This includes values selected through modifiers, order, etc.
func (ws *WalletSetting) Value(name string) (ent.Value, error) {
	return ws.selectValues.Get(name)
}

// Update returns a builder for updating this WalletSetting.
// Note that you need to call WalletSetting.Unwrap() before calling this method if this WalletSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (ws *WalletSetting) Update() *WalletSettingUpdateOne {
	return NewWalletSettingClient(ws.config).UpdateOne(ws)
}

// Unwrap unwraps the WalletSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ws *WalletSetting) Unwrap() *WalletSetting {
	_tx, ok := ws.config.driver.(*txDriver)
	if !ok {
		panic("ent: WalletSetting is not a transactional entity")
	}
	ws.config.driver = _tx.drv
	return ws
}

// String implements the fmt.Stringer.
func (ws *WalletSetting) String() string {
	var builder strings.Builder
	builder.WriteString("WalletSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ws.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ws.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ws.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_identity_public_key=")
	builder.WriteString(fmt.Sprintf("%v", ws.OwnerIdentityPublicKey))
	builder.WriteString(", ")
	builder.WriteString("private_enabled=")
	builder.WriteString(fmt.Sprintf("%v", ws.PrivateEnabled))
	builder.WriteString(", ")
	if v := ws.MasterIdentityPublicKey; v != nil {
		builder.WriteString("master_identity_public_key=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WalletSettings is a parsable slice of WalletSetting.
type WalletSettings []*WalletSetting
