// Code generated by ent, DO NOT EDIT.

package l1withdrawaltransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the l1withdrawaltransaction type in the database.
	Label = "l1withdrawal_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldConfirmationTxid holds the string denoting the confirmation_txid field in the database.
	FieldConfirmationTxid = "confirmation_txid"
	// FieldConfirmationBlockHash holds the string denoting the confirmation_block_hash field in the database.
	FieldConfirmationBlockHash = "confirmation_block_hash"
	// FieldConfirmationHeight holds the string denoting the confirmation_height field in the database.
	FieldConfirmationHeight = "confirmation_height"
	// FieldDetectedAt holds the string denoting the detected_at field in the database.
	FieldDetectedAt = "detected_at"
	// FieldOwnerSignature holds the string denoting the owner_signature field in the database.
	FieldOwnerSignature = "owner_signature"
	// EdgeWithdrawals holds the string denoting the withdrawals edge name in mutations.
	EdgeWithdrawals = "withdrawals"
	// EdgeSeEntity holds the string denoting the se_entity edge name in mutations.
	EdgeSeEntity = "se_entity"
	// Table holds the table name of the l1withdrawaltransaction in the database.
	Table = "l1withdrawal_transactions"
	// WithdrawalsTable is the table that holds the withdrawals relation/edge.
	WithdrawalsTable = "l1token_output_withdrawals"
	// WithdrawalsInverseTable is the table name for the L1TokenOutputWithdrawal entity.
	// It exists in this package in order to avoid circular dependency with the "l1tokenoutputwithdrawal" package.
	WithdrawalsInverseTable = "l1token_output_withdrawals"
	// WithdrawalsColumn is the table column denoting the withdrawals relation/edge.
	WithdrawalsColumn = "l1withdrawal_transaction_withdrawals"
	// SeEntityTable is the table that holds the se_entity relation/edge.
	SeEntityTable = "l1withdrawal_transactions"
	// SeEntityInverseTable is the table name for the EntityDkgKey entity.
	// It exists in this package in order to avoid circular dependency with the "entitydkgkey" package.
	SeEntityInverseTable = "entity_dkg_keys"
	// SeEntityColumn is the table column denoting the se_entity relation/edge.
	SeEntityColumn = "l1withdrawal_transaction_se_entity"
)

// Columns holds all SQL columns for l1withdrawaltransaction fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldConfirmationTxid,
	FieldConfirmationBlockHash,
	FieldConfirmationHeight,
	FieldDetectedAt,
	FieldOwnerSignature,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "l1withdrawal_transactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"l1withdrawal_transaction_se_entity",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the L1WithdrawalTransaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByConfirmationHeight orders the results by the confirmation_height field.
func ByConfirmationHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmationHeight, opts...).ToFunc()
}

// ByDetectedAt orders the results by the detected_at field.
func ByDetectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetectedAt, opts...).ToFunc()
}

// ByWithdrawalsCount orders the results by withdrawals count.
func ByWithdrawalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWithdrawalsStep(), opts...)
	}
}

// ByWithdrawals orders the results by withdrawals terms.
func ByWithdrawals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWithdrawalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySeEntityField orders the results by se_entity field.
func BySeEntityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeEntityStep(), sql.OrderByField(field, opts...))
	}
}
func newWithdrawalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WithdrawalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WithdrawalsTable, WithdrawalsColumn),
	)
}
func newSeEntityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeEntityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SeEntityTable, SeEntityColumn),
	)
}
