// Code generated by ent, DO NOT EDIT.

package idempotencykey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldUpdateTime, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldIdempotencyKey, v))
}

// MethodName applies equality check predicate on the "method_name" field. It's identical to MethodNameEQ.
func MethodName(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldMethodName, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldUpdateTime, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// MethodNameEQ applies the EQ predicate on the "method_name" field.
func MethodNameEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEQ(FieldMethodName, v))
}

// MethodNameNEQ applies the NEQ predicate on the "method_name" field.
func MethodNameNEQ(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNEQ(FieldMethodName, v))
}

// MethodNameIn applies the In predicate on the "method_name" field.
func MethodNameIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIn(FieldMethodName, vs...))
}

// MethodNameNotIn applies the NotIn predicate on the "method_name" field.
func MethodNameNotIn(vs ...string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotIn(FieldMethodName, vs...))
}

// MethodNameGT applies the GT predicate on the "method_name" field.
func MethodNameGT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGT(FieldMethodName, v))
}

// MethodNameGTE applies the GTE predicate on the "method_name" field.
func MethodNameGTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldGTE(FieldMethodName, v))
}

// MethodNameLT applies the LT predicate on the "method_name" field.
func MethodNameLT(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLT(FieldMethodName, v))
}

// MethodNameLTE applies the LTE predicate on the "method_name" field.
func MethodNameLTE(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldLTE(FieldMethodName, v))
}

// MethodNameContains applies the Contains predicate on the "method_name" field.
func MethodNameContains(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContains(FieldMethodName, v))
}

// MethodNameHasPrefix applies the HasPrefix predicate on the "method_name" field.
func MethodNameHasPrefix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasPrefix(FieldMethodName, v))
}

// MethodNameHasSuffix applies the HasSuffix predicate on the "method_name" field.
func MethodNameHasSuffix(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldHasSuffix(FieldMethodName, v))
}

// MethodNameEqualFold applies the EqualFold predicate on the "method_name" field.
func MethodNameEqualFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldEqualFold(FieldMethodName, v))
}

// MethodNameContainsFold applies the ContainsFold predicate on the "method_name" field.
func MethodNameContainsFold(v string) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldContainsFold(FieldMethodName, v))
}

// ResponseIsNil applies the IsNil predicate on the "response" field.
func ResponseIsNil() predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldIsNull(FieldResponse))
}

// ResponseNotNil applies the NotNil predicate on the "response" field.
func ResponseNotNil() predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.FieldNotNull(FieldResponse))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IdempotencyKey) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IdempotencyKey) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IdempotencyKey) predicate.IdempotencyKey {
	return predicate.IdempotencyKey(sql.NotPredicates(p))
}
