// Code generated by ent, DO NOT EDIT.

package l1tokenjusticetransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the l1tokenjusticetransaction type in the database.
	Label = "l1token_justice_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldJusticeTxHash holds the string denoting the justice_tx_hash field in the database.
	FieldJusticeTxHash = "justice_tx_hash"
	// FieldBroadcastAt holds the string denoting the broadcast_at field in the database.
	FieldBroadcastAt = "broadcast_at"
	// FieldAmountSats holds the string denoting the amount_sats field in the database.
	FieldAmountSats = "amount_sats"
	// FieldTxCostSats holds the string denoting the tx_cost_sats field in the database.
	FieldTxCostSats = "tx_cost_sats"
	// EdgeTokenOutput holds the string denoting the token_output edge name in mutations.
	EdgeTokenOutput = "token_output"
	// EdgeL1TokenOutputWithdrawal holds the string denoting the l1_token_output_withdrawal edge name in mutations.
	EdgeL1TokenOutputWithdrawal = "l1_token_output_withdrawal"
	// Table holds the table name of the l1tokenjusticetransaction in the database.
	Table = "l1token_justice_transactions"
	// TokenOutputTable is the table that holds the token_output relation/edge.
	TokenOutputTable = "l1token_justice_transactions"
	// TokenOutputInverseTable is the table name for the TokenOutput entity.
	// It exists in this package in order to avoid circular dependency with the "tokenoutput" package.
	TokenOutputInverseTable = "token_outputs"
	// TokenOutputColumn is the table column denoting the token_output relation/edge.
	TokenOutputColumn = "token_output_justice_tx"
	// L1TokenOutputWithdrawalTable is the table that holds the l1_token_output_withdrawal relation/edge.
	L1TokenOutputWithdrawalTable = "l1token_justice_transactions"
	// L1TokenOutputWithdrawalInverseTable is the table name for the L1TokenOutputWithdrawal entity.
	// It exists in this package in order to avoid circular dependency with the "l1tokenoutputwithdrawal" package.
	L1TokenOutputWithdrawalInverseTable = "l1token_output_withdrawals"
	// L1TokenOutputWithdrawalColumn is the table column denoting the l1_token_output_withdrawal relation/edge.
	L1TokenOutputWithdrawalColumn = "l1token_output_withdrawal_justice_tx"
)

// Columns holds all SQL columns for l1tokenjusticetransaction fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldJusticeTxHash,
	FieldBroadcastAt,
	FieldAmountSats,
	FieldTxCostSats,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "l1token_justice_transactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"l1token_output_withdrawal_justice_tx",
	"token_output_justice_tx",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the L1TokenJusticeTransaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByBroadcastAt orders the results by the broadcast_at field.
func ByBroadcastAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBroadcastAt, opts...).ToFunc()
}

// ByAmountSats orders the results by the amount_sats field.
func ByAmountSats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountSats, opts...).ToFunc()
}

// ByTxCostSats orders the results by the tx_cost_sats field.
func ByTxCostSats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxCostSats, opts...).ToFunc()
}

// ByTokenOutputField orders the results by token_output field.
func ByTokenOutputField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenOutputStep(), sql.OrderByField(field, opts...))
	}
}

// ByL1TokenOutputWithdrawalField orders the results by l1_token_output_withdrawal field.
func ByL1TokenOutputWithdrawalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newL1TokenOutputWithdrawalStep(), sql.OrderByField(field, opts...))
	}
}
func newTokenOutputStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenOutputInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TokenOutputTable, TokenOutputColumn),
	)
}
func newL1TokenOutputWithdrawalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(L1TokenOutputWithdrawalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, L1TokenOutputWithdrawalTable, L1TokenOutputWithdrawalColumn),
	)
}
