// Code generated by ent, DO NOT EDIT.

package l1tokenjusticetransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldUpdateTime, v))
}

// JusticeTxHash applies equality check predicate on the "justice_tx_hash" field. It's identical to JusticeTxHashEQ.
func JusticeTxHash(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldJusticeTxHash, v))
}

// BroadcastAt applies equality check predicate on the "broadcast_at" field. It's identical to BroadcastAtEQ.
func BroadcastAt(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldBroadcastAt, v))
}

// AmountSats applies equality check predicate on the "amount_sats" field. It's identical to AmountSatsEQ.
func AmountSats(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldAmountSats, v))
}

// TxCostSats applies equality check predicate on the "tx_cost_sats" field. It's identical to TxCostSatsEQ.
func TxCostSats(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldTxCostSats, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldUpdateTime, v))
}

// JusticeTxHashEQ applies the EQ predicate on the "justice_tx_hash" field.
func JusticeTxHashEQ(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldJusticeTxHash, v))
}

// JusticeTxHashNEQ applies the NEQ predicate on the "justice_tx_hash" field.
func JusticeTxHashNEQ(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldJusticeTxHash, v))
}

// JusticeTxHashIn applies the In predicate on the "justice_tx_hash" field.
func JusticeTxHashIn(vs ...schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldJusticeTxHash, vs...))
}

// JusticeTxHashNotIn applies the NotIn predicate on the "justice_tx_hash" field.
func JusticeTxHashNotIn(vs ...schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldJusticeTxHash, vs...))
}

// JusticeTxHashGT applies the GT predicate on the "justice_tx_hash" field.
func JusticeTxHashGT(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldJusticeTxHash, v))
}

// JusticeTxHashGTE applies the GTE predicate on the "justice_tx_hash" field.
func JusticeTxHashGTE(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldJusticeTxHash, v))
}

// JusticeTxHashLT applies the LT predicate on the "justice_tx_hash" field.
func JusticeTxHashLT(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldJusticeTxHash, v))
}

// JusticeTxHashLTE applies the LTE predicate on the "justice_tx_hash" field.
func JusticeTxHashLTE(v schematype.TxID) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldJusticeTxHash, v))
}

// BroadcastAtEQ applies the EQ predicate on the "broadcast_at" field.
func BroadcastAtEQ(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldBroadcastAt, v))
}

// BroadcastAtNEQ applies the NEQ predicate on the "broadcast_at" field.
func BroadcastAtNEQ(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldBroadcastAt, v))
}

// BroadcastAtIn applies the In predicate on the "broadcast_at" field.
func BroadcastAtIn(vs ...time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldBroadcastAt, vs...))
}

// BroadcastAtNotIn applies the NotIn predicate on the "broadcast_at" field.
func BroadcastAtNotIn(vs ...time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldBroadcastAt, vs...))
}

// BroadcastAtGT applies the GT predicate on the "broadcast_at" field.
func BroadcastAtGT(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldBroadcastAt, v))
}

// BroadcastAtGTE applies the GTE predicate on the "broadcast_at" field.
func BroadcastAtGTE(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldBroadcastAt, v))
}

// BroadcastAtLT applies the LT predicate on the "broadcast_at" field.
func BroadcastAtLT(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldBroadcastAt, v))
}

// BroadcastAtLTE applies the LTE predicate on the "broadcast_at" field.
func BroadcastAtLTE(v time.Time) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldBroadcastAt, v))
}

// AmountSatsEQ applies the EQ predicate on the "amount_sats" field.
func AmountSatsEQ(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldAmountSats, v))
}

// AmountSatsNEQ applies the NEQ predicate on the "amount_sats" field.
func AmountSatsNEQ(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldAmountSats, v))
}

// AmountSatsIn applies the In predicate on the "amount_sats" field.
func AmountSatsIn(vs ...uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldAmountSats, vs...))
}

// AmountSatsNotIn applies the NotIn predicate on the "amount_sats" field.
func AmountSatsNotIn(vs ...uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldAmountSats, vs...))
}

// AmountSatsGT applies the GT predicate on the "amount_sats" field.
func AmountSatsGT(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldAmountSats, v))
}

// AmountSatsGTE applies the GTE predicate on the "amount_sats" field.
func AmountSatsGTE(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldAmountSats, v))
}

// AmountSatsLT applies the LT predicate on the "amount_sats" field.
func AmountSatsLT(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldAmountSats, v))
}

// AmountSatsLTE applies the LTE predicate on the "amount_sats" field.
func AmountSatsLTE(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldAmountSats, v))
}

// TxCostSatsEQ applies the EQ predicate on the "tx_cost_sats" field.
func TxCostSatsEQ(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldEQ(FieldTxCostSats, v))
}

// TxCostSatsNEQ applies the NEQ predicate on the "tx_cost_sats" field.
func TxCostSatsNEQ(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNEQ(FieldTxCostSats, v))
}

// TxCostSatsIn applies the In predicate on the "tx_cost_sats" field.
func TxCostSatsIn(vs ...uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldIn(FieldTxCostSats, vs...))
}

// TxCostSatsNotIn applies the NotIn predicate on the "tx_cost_sats" field.
func TxCostSatsNotIn(vs ...uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldNotIn(FieldTxCostSats, vs...))
}

// TxCostSatsGT applies the GT predicate on the "tx_cost_sats" field.
func TxCostSatsGT(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGT(FieldTxCostSats, v))
}

// TxCostSatsGTE applies the GTE predicate on the "tx_cost_sats" field.
func TxCostSatsGTE(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldGTE(FieldTxCostSats, v))
}

// TxCostSatsLT applies the LT predicate on the "tx_cost_sats" field.
func TxCostSatsLT(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLT(FieldTxCostSats, v))
}

// TxCostSatsLTE applies the LTE predicate on the "tx_cost_sats" field.
func TxCostSatsLTE(v uint64) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.FieldLTE(FieldTxCostSats, v))
}

// HasTokenOutput applies the HasEdge predicate on the "token_output" edge.
func HasTokenOutput() predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TokenOutputTable, TokenOutputColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokenOutputWith applies the HasEdge predicate on the "token_output" edge with a given conditions (other predicates).
func HasTokenOutputWith(preds ...predicate.TokenOutput) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(func(s *sql.Selector) {
		step := newTokenOutputStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasL1TokenOutputWithdrawal applies the HasEdge predicate on the "l1_token_output_withdrawal" edge.
func HasL1TokenOutputWithdrawal() predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, L1TokenOutputWithdrawalTable, L1TokenOutputWithdrawalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasL1TokenOutputWithdrawalWith applies the HasEdge predicate on the "l1_token_output_withdrawal" edge with a given conditions (other predicates).
func HasL1TokenOutputWithdrawalWith(preds ...predicate.L1TokenOutputWithdrawal) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(func(s *sql.Selector) {
		step := newL1TokenOutputWithdrawalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.L1TokenJusticeTransaction) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.L1TokenJusticeTransaction) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.L1TokenJusticeTransaction) predicate.L1TokenJusticeTransaction {
	return predicate.L1TokenJusticeTransaction(sql.NotPredicates(p))
}
