// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: mock.proto

package mock

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CleanUpPreimageShareRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CleanUpPreimageShareRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CleanUpPreimageShareRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CleanUpPreimageShareRequestMultiError, or nil if none found.
func (m *CleanUpPreimageShareRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CleanUpPreimageShareRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PaymentHash

	if len(errors) > 0 {
		return CleanUpPreimageShareRequestMultiError(errors)
	}

	return nil
}

// CleanUpPreimageShareRequestMultiError is an error wrapping multiple
// validation errors returned by CleanUpPreimageShareRequest.ValidateAll() if
// the designated constraints aren't met.
type CleanUpPreimageShareRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CleanUpPreimageShareRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CleanUpPreimageShareRequestMultiError) AllErrors() []error { return m }

// CleanUpPreimageShareRequestValidationError is the validation error returned
// by CleanUpPreimageShareRequest.Validate if the designated constraints
// aren't met.
type CleanUpPreimageShareRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CleanUpPreimageShareRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CleanUpPreimageShareRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CleanUpPreimageShareRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CleanUpPreimageShareRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CleanUpPreimageShareRequestValidationError) ErrorName() string {
	return "CleanUpPreimageShareRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CleanUpPreimageShareRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCleanUpPreimageShareRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CleanUpPreimageShareRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CleanUpPreimageShareRequestValidationError{}

// Validate checks the field values on UpdateNodesStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateNodesStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateNodesStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateNodesStatusRequestMultiError, or nil if none found.
func (m *UpdateNodesStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateNodesStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateNodesStatusRequestMultiError(errors)
	}

	return nil
}

// UpdateNodesStatusRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateNodesStatusRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateNodesStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateNodesStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateNodesStatusRequestMultiError) AllErrors() []error { return m }

// UpdateNodesStatusRequestValidationError is the validation error returned by
// UpdateNodesStatusRequest.Validate if the designated constraints aren't met.
type UpdateNodesStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateNodesStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateNodesStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateNodesStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateNodesStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateNodesStatusRequestValidationError) ErrorName() string {
	return "UpdateNodesStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateNodesStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateNodesStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateNodesStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateNodesStatusRequestValidationError{}

// Validate checks the field values on TriggerTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerTaskRequestMultiError, or nil if none found.
func (m *TriggerTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskName

	if len(errors) > 0 {
		return TriggerTaskRequestMultiError(errors)
	}

	return nil
}

// TriggerTaskRequestMultiError is an error wrapping multiple validation errors
// returned by TriggerTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type TriggerTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerTaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerTaskRequestMultiError) AllErrors() []error { return m }

// TriggerTaskRequestValidationError is the validation error returned by
// TriggerTaskRequest.Validate if the designated constraints aren't met.
type TriggerTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerTaskRequestValidationError) ErrorName() string {
	return "TriggerTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerTaskRequestValidationError{}

// Validate checks the field values on QueryPreimageShareRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryPreimageShareRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryPreimageShareRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryPreimageShareRequestMultiError, or nil if none found.
func (m *QueryPreimageShareRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryPreimageShareRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PaymentHash

	if len(errors) > 0 {
		return QueryPreimageShareRequestMultiError(errors)
	}

	return nil
}

// QueryPreimageShareRequestMultiError is an error wrapping multiple validation
// errors returned by QueryPreimageShareRequest.ValidateAll() if the
// designated constraints aren't met.
type QueryPreimageShareRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryPreimageShareRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryPreimageShareRequestMultiError) AllErrors() []error { return m }

// QueryPreimageShareRequestValidationError is the validation error returned by
// QueryPreimageShareRequest.Validate if the designated constraints aren't met.
type QueryPreimageShareRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryPreimageShareRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryPreimageShareRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryPreimageShareRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryPreimageShareRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryPreimageShareRequestValidationError) ErrorName() string {
	return "QueryPreimageShareRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryPreimageShareRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryPreimageShareRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryPreimageShareRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryPreimageShareRequestValidationError{}

// Validate checks the field values on QueryPreimageShareResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryPreimageShareResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryPreimageShareResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryPreimageShareResponseMultiError, or nil if none found.
func (m *QueryPreimageShareResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryPreimageShareResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PreimageShare

	// no validation rules for Threshold

	// no validation rules for InvoiceString

	if len(errors) > 0 {
		return QueryPreimageShareResponseMultiError(errors)
	}

	return nil
}

// QueryPreimageShareResponseMultiError is an error wrapping multiple
// validation errors returned by QueryPreimageShareResponse.ValidateAll() if
// the designated constraints aren't met.
type QueryPreimageShareResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryPreimageShareResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryPreimageShareResponseMultiError) AllErrors() []error { return m }

// QueryPreimageShareResponseValidationError is the validation error returned
// by QueryPreimageShareResponse.Validate if the designated constraints aren't met.
type QueryPreimageShareResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryPreimageShareResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryPreimageShareResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryPreimageShareResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryPreimageShareResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryPreimageShareResponseValidationError) ErrorName() string {
	return "QueryPreimageShareResponseValidationError"
}

// Error satisfies the builtin error interface
func (e QueryPreimageShareResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryPreimageShareResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryPreimageShareResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryPreimageShareResponseValidationError{}
